# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing permissions
# and limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch
from _pytest.mark.structures import Mark, MarkDecorator

import flag_gems

from . import accuracy_utils as utils
from . import conftest as cfg

# ``_empty_affine_quantized`` starts with an underscore, and ``pytest.mark``
# refuses to generate a marker via attribute access for such names. Register it
# directly on the MarkGenerator so ``@pytest.mark._empty_affine_quantized`` and
# ``-m _empty_affine_quantized`` both work.
setattr(
    pytest.mark,
    "_empty_affine_quantized",
    MarkDecorator(
        Mark("_empty_affine_quantized", (), {}, _ispytest=True), _ispytest=True
    ),
)

device = flag_gems.device

# The factory is a quantized allocator: the data buffer is uninitialized, so the
# contract under test is the quantizer metadata (qscheme, scale, zero_point, the
# int_repr dtype) and the tensor geometry, never element values.
#
# ``quint4x2``/``quint2x4`` allocate fine and are quantized, but this build has
# no device ``int_repr`` kernel for them (``int_repr_quantized_cuda`` only
# covers QUInt8/QInt8/QInt32, measured on H20), so they are compared without
# going through ``int_repr``.
QTYPES = [torch.quint8, torch.qint8, torch.qint32, torch.quint4x2, torch.quint2x4]
PACKED_QTYPES = (torch.quint4x2, torch.quint2x4)
INT_REPR_DTYPE = {
    torch.qint8: torch.int8,
    torch.quint8: torch.uint8,
    torch.qint32: torch.int32,
    torch.quint4x2: torch.uint8,
    torch.quint2x4: torch.uint8,
}

# Shapes cover the allocation geometry the operator varies over: a plain 2-D
# case, the harness core shapes, a rank-3/rank-4 case, the zero-numel cases
# (which allocate no page at all) and the 0-dim case (which allocates one
# element).
SHAPES = [(2, 3), (64, 64), (4, 32, 32), (2, 3, 4, 5), (0,), (2, 0, 3), ()]
if cfg.QUICK_MODE:
    SHAPES = [(2, 3), (4, 32, 32), (0,), ()]

# Strides each shape/memory-format pair must produce, pinned from the measured
# native behaviour on H20 so the layout contract cannot drift silently.
DEFAULT_STRIDES = {
    (2, 3): (3, 1),
    (64, 64): (64, 1),
    (4, 32, 32): (1024, 32, 1),
    (2, 3, 4, 5): (60, 20, 5, 1),
    (2, 3, 4, 5, 6): (360, 60, 15, 5, 1),
    (0,): (1,),
    (2, 0, 3): (3, 3, 1),
    (): (),
}


def _call(size, *, dtype, scale=1.0, zero_point=0, memory_format=None, **kwargs):
    call_kwargs = dict(
        dtype=dtype, device=flag_gems.device, scale=scale, zero_point=zero_point
    )
    call_kwargs.update(kwargs)
    if memory_format is not None:
        call_kwargs["memory_format"] = memory_format
    return flag_gems._empty_affine_quantized(size, **call_kwargs)


def _reference(size, *, dtype, scale=1.0, zero_point=0, memory_format=None, **kwargs):
    ref_kwargs = dict(
        dtype=dtype,
        device="cpu" if cfg.TO_CPU else device,
        scale=scale,
        zero_point=zero_point,
    )
    ref_kwargs.update(kwargs)
    if memory_format is not None:
        ref_kwargs["memory_format"] = memory_format
    return torch.ops.aten._empty_affine_quantized(size, **ref_kwargs)


def _meta(t):
    """Harvest every output property an uninitialized factory still fixes."""
    meta = {
        "shape": tuple(t.shape),
        "dtype": t.dtype,
        # ``device_type`` is only comparable when both sides run on the same
        # device; under ``--ref=cpu`` the reference legitimately lives on the
        # host, so only the implementation side is pinned there.
        "device_type": t.device.type if not cfg.TO_CPU else None,
        "qscheme": t.qscheme(),
        "scale": t.q_scale(),
        "zero_point": t.q_zero_point(),
        "stride": tuple(t.stride()),
        "numel": t.numel(),
        "storage_bytes": t.untyped_storage().nbytes(),
        "is_quantized": t.is_quantized,
        "is_view": t._is_view(),
        "requires_grad": t.requires_grad,
        "is_contiguous": t.is_contiguous(),
        "layout": t.layout,
    }
    if t.dtype not in PACKED_QTYPES:
        int_repr = t.int_repr()
        meta["int_repr_dtype"] = int_repr.dtype
        meta["int_repr_shape"] = tuple(int_repr.shape)
    return meta


def _assert_same_meta(res, ref):
    res_meta = _meta(res)
    ref_meta = _meta(ref)
    assert set(res_meta) == set(
        ref_meta
    ), f"metadata key mismatch: {sorted(set(res_meta) ^ set(ref_meta))}"
    for key in sorted(ref_meta):
        got, want = res_meta[key], ref_meta[key]
        assert got == want, f"{key}: {got!r} != {want!r}"


@pytest.mark._empty_affine_quantized
@pytest.mark.parametrize("dtype", QTYPES)
@pytest.mark.parametrize("shape", SHAPES)
def test_accuracy__empty_affine_quantized_metadata(shape, dtype):
    # Main sweep: quantized dtype class x geometry. The quantizer metadata and
    # the tensor geometry must match the reference exactly; element values are
    # deliberately not compared (the storage is uninitialized on both sides).
    res = _call(list(shape), dtype=dtype, scale=0.5, zero_point=3)
    ref = _reference(list(shape), dtype=dtype, scale=0.5, zero_point=3)

    assert res.device.type == flag_gems.device
    if not cfg.TO_CPU:
        assert res.device.type == ref.device.type
    _assert_same_meta(res, ref)
    assert res.qscheme() == torch.per_tensor_affine
    assert res.is_quantized is True


@pytest.mark._empty_affine_quantized
@pytest.mark.parametrize("dtype", QTYPES)
def test_accuracy__empty_affine_quantized_int_repr_dtype(dtype):
    # The integer view of the storage maps the quantized dtype onto its
    # underlying integral type; that mapping is part of the contract.
    if dtype in PACKED_QTYPES:
        pytest.skip("this build has no device int_repr kernel for packed qtypes")
    res = _call([4, 8], dtype=dtype)
    ref = _reference([4, 8], dtype=dtype)

    assert res.int_repr().dtype == INT_REPR_DTYPE[dtype]
    assert res.int_repr().dtype == ref.int_repr().dtype
    assert tuple(res.int_repr().shape) == tuple(ref.int_repr().shape) == (4, 8)


@pytest.mark._empty_affine_quantized
@pytest.mark.parametrize(
    "scale,zero_point",
    [
        (1.0, 0),  # schema defaults
        (0.5, 3),
        (0.0, 0),  # accepted verbatim, no validation
        (-1.5, -3),  # negative scale/zero_point accepted verbatim
        (1.0, 999),  # out of the qint8 range, stored verbatim
        (1.0, -1),  # negative zero_point on an unsigned qtype
        (1234.5, 7),
    ],
)
def test_accuracy__empty_affine_quantized_qparams(scale, zero_point):
    # The factory stores the requested affine parameters verbatim; it validates
    # neither their range nor their sign.
    res = _call([4], dtype=torch.qint8, scale=scale, zero_point=zero_point)
    ref = _reference([4], dtype=torch.qint8, scale=scale, zero_point=zero_point)

    assert res.q_scale() == ref.q_scale() == scale
    assert res.q_zero_point() == ref.q_zero_point() == zero_point
    utils.gems_assert_close(
        torch.tensor(res.q_scale(), dtype=torch.float32),
        torch.tensor(ref.q_scale(), dtype=torch.float32),
        torch.float32,
    )


@pytest.mark._empty_affine_quantized
def test_accuracy__empty_affine_quantized_default_qparams():
    # Omitted scale/zero_point resolve to the schema defaults (1.0 / 0).
    res = _call([2, 3], dtype=torch.quint8)
    ref = _reference([2, 3], dtype=torch.quint8)

    assert res.q_scale() == ref.q_scale() == 1.0
    assert res.q_zero_point() == ref.q_zero_point() == 0
    _assert_same_meta(res, ref)


@pytest.mark._empty_affine_quantized
def test_accuracy__empty_affine_quantized_memory_format():
    # ``contiguous_format`` (the schema default) is the supported format for a
    # rank-N strided quantized tensor; ``channels_last`` is supported for
    # rank 4 and ``channels_last_3d`` for rank 5. Both sides must agree on the
    # resulting strides, and the strides are pinned from the measured native
    # behaviour so the layout contract cannot drift silently.
    for shape, mf, expected_stride in [
        ((2, 3, 4, 5), torch.contiguous_format, (60, 20, 5, 1)),
        ((2, 3, 4, 5), torch.channels_last, (60, 1, 15, 3)),
        ((2, 3, 4, 5, 6), torch.channels_last_3d, (360, 1, 90, 18, 3)),
        ((4, 8), torch.contiguous_format, (8, 1)),
    ]:
        res = _call(list(shape), dtype=torch.qint8, memory_format=mf)
        ref = _reference(list(shape), dtype=torch.qint8, memory_format=mf)
        assert res.stride() == ref.stride(), f"{shape} {mf}: strides differ"
        assert res.stride() == expected_stride, f"{shape} {mf}: wrong strides"
        _assert_same_meta(res, ref)

    # The schema default is contiguous_format, so an omitted argument must land
    # on the same layout as the explicit spelling.
    assert (
        _call([2, 3, 4, 5], dtype=torch.qint8).stride() == DEFAULT_STRIDES[(2, 3, 4, 5)]
    )
    assert (
        _call([2, 3, 4, 5], dtype=torch.qint8).stride()
        == _call(
            [2, 3, 4, 5], dtype=torch.qint8, memory_format=torch.contiguous_format
        ).stride()
    )


@pytest.mark._empty_affine_quantized
@pytest.mark.parametrize(
    "shape,memory_format",
    [
        ((2, 3, 4, 5), torch.preserve_format),
        ((2, 3, 4, 5), torch.channels_last_3d),
        ((4, 8), torch.channels_last),
    ],
)
def test_accuracy__empty_affine_quantized_unsupported_memory_format(
    shape, memory_format
):
    # ``preserve_format`` has no source layout to preserve in a factory, and the
    # rank mismatch between the shape and the requested format is rejected. Both
    # sides must raise the same error class.
    with pytest.raises(RuntimeError):
        _call(list(shape), dtype=torch.qint8, memory_format=memory_format)
    with pytest.raises(RuntimeError):
        _reference(list(shape), dtype=torch.qint8, memory_format=memory_format)


@pytest.mark._empty_affine_quantized
def test_accuracy__empty_affine_quantized_string_memory_format():
    # The supplied candidate normalized the string spellings of the memory-format
    # enum. The dispatched argument parser rejects strings outright (measured),
    # so this branch is only reachable through the direct python entry point; it
    # must land on the same layout as the enum spelling.
    as_string = flag_gems._empty_affine_quantized(
        [2, 3, 4, 5],
        dtype=torch.qint8,
        device=flag_gems.device,
        memory_format="channels_last",
    )
    as_enum = _call([2, 3, 4, 5], dtype=torch.qint8, memory_format=torch.channels_last)
    assert as_string.stride() == as_enum.stride()
    assert as_string.stride() == (60, 1, 15, 3)

    default_string = flag_gems._empty_affine_quantized(
        [2, 3], dtype=torch.qint8, device=flag_gems.device
    )
    assert default_string.stride() == (3, 1)


@pytest.mark._empty_affine_quantized
def test_accuracy__empty_affine_quantized_zero_numel_and_zero_dim():
    # A zero-numel output allocates no storage page at all (nbytes == 0 and a
    # null data_ptr); a 0-dim request allocates exactly one element. Both are
    # part of the geometry contract.
    for shape in [(0,), (2, 0, 3)]:
        res = _call(list(shape), dtype=torch.quint8)
        ref = _reference(list(shape), dtype=torch.quint8)
        assert res.numel() == 0
        assert res.untyped_storage().nbytes() == 0
        assert ref.untyped_storage().nbytes() == 0
        assert res.data_ptr() == 0
        _assert_same_meta(res, ref)

    res_0d = _call([], dtype=torch.quint8)
    ref_0d = _reference([], dtype=torch.quint8)
    assert res_0d.shape == ref_0d.shape == torch.Size([])
    assert res_0d.numel() == ref_0d.numel() == 1
    assert res_0d.untyped_storage().nbytes() == ref_0d.untyped_storage().nbytes() == 1
    _assert_same_meta(res_0d, ref_0d)


@pytest.mark._empty_affine_quantized
def test_accuracy__empty_affine_quantized_fresh_allocation():
    # Each call returns an independent allocation: a distinct data pointer, no
    # view relationship and no autograd history. (This is the aliasing half of
    # the contract; the "uninitialized" half is pinned by the kernel-parity
    # test below.)
    a = _call([64], dtype=torch.quint8)
    b = _call([64], dtype=torch.quint8)

    assert a.data_ptr() != b.data_ptr()
    assert a._is_view() is False
    assert a._base is None
    assert a.requires_grad is False

    ref = _reference([64], dtype=torch.quint8)
    assert ref._is_view() is False
    assert ref._base is None


@pytest.mark._empty_affine_quantized
def test_accuracy__empty_affine_quantized_does_not_write_storage():
    # The native factory returns *uninitialized* storage -- it hands back
    # whatever the caching allocator recycled and never writes the data buffer.
    # This implementation must not write it either: the supplied candidate
    # launched a no-op Triton kernel on a side stream, which cannot change the
    # returned values but adds a device launch to an otherwise launch-free
    # operator.
    #
    # The discriminator is the set of device kernels launched by the allocation
    # (measured on H20: the native base path launches none at all). Comparing
    # raw bytes after recycling a dirty block was rejected as a discriminator:
    # measured on this box, two independent native allocations read back
    # *identical* (the allocator recycled a zeroed page), so the comparison does
    # not fire. Kernel parity is deterministic and does catch an added launch.
    if cfg.TO_CPU:
        pytest.skip("kernel counting requires the device backend")

    from torch.profiler import ProfilerActivity, profile

    # Profiler bookkeeping entries are not device kernels of the operation.
    bookkeeping = {
        "Activity Buffer Request",
        "cudaLaunchKernel",
        "cudaDeviceSynchronize",
        "cudaStreamSynchronize",
        "cudaEventRecord",
        "cudaEventQuery",
        "cudaMemsetAsync",
    }

    def _launched_kernels(fn, iterations=5):
        for _ in range(5):
            fn()
        torch.cuda.synchronize()
        with profile(activities=[ProfilerActivity.CUDA]) as prof:
            for _ in range(iterations):
                fn()
            torch.cuda.synchronize()
        return sorted(
            event.key
            for event in prof.key_averages()
            if event.count and event.key not in bookkeeping
        )

    res_kernels = _launched_kernels(lambda: _call([512], dtype=torch.quint8))
    ref_kernels = _launched_kernels(lambda: _reference([512], dtype=torch.quint8))

    assert ref_kernels == [], (
        "the native allocation path is expected to launch no device kernel; "
        f"measured {ref_kernels}"
    )
    assert res_kernels == ref_kernels, (
        "the implementation launches device kernels the native allocation does "
        f"not: impl={res_kernels} ref={ref_kernels}"
    )


@pytest.mark._empty_affine_quantized
def test_accuracy__empty_affine_quantized_unsupported_dtype():
    # A non-quantized dtype is rejected: the device key has no kernel for it,
    # while the CPU kernel validates the dtype up front and raises
    # RuntimeError. The registrar necessarily also installs the implementation
    # on the plain device key (see the module docstring); that path must
    # reproduce the native rejection instead of re-entering itself, which would
    # surface as a RecursionError.
    for dtype in (torch.float32, torch.float16, torch.int32, torch.bool, None):
        with pytest.raises(NotImplementedError, match="CUDA backend"):
            flag_gems._empty_affine_quantized(
                [2, 3], dtype=dtype, device=flag_gems.device
            )

        # The CPU kernel validates the quantized dtype up front and raises
        # RuntimeError; the device key has no kernel at all and is answered by
        # the dispatcher with NotImplementedError.
        expected_error = RuntimeError if cfg.TO_CPU else NotImplementedError
        with pytest.raises(expected_error):
            _reference([2, 3], dtype=dtype)


@pytest.mark._empty_affine_quantized
def test_accuracy__empty_affine_quantized_device_resolution():
    # The output device comes from the ``device`` argument. Omitting it falls
    # back to the default device rather than following anything else.
    res = _call([2], dtype=torch.qint8)
    assert device == torch.device("cuda"), "flag_gems.device is not 'cuda'"
    assert res.device.type == flag_gems.device
    # The device string carries no index here (the argument was omitted), so
    # compare the device type rather than the full torch.device: torch.device
    # ("cuda") != torch.device("cuda:0").
    assert res.device.type == "cuda"

    # An explicit indexed device argument lands on that device.
    indexed = flag_gems._empty_affine_quantized(
        [2], dtype=torch.qint8, device=f"{flag_gems.device}:0"
    )
    assert indexed.device == torch.device("cuda:0")
    _assert_same_meta(indexed, res)

    # Layout other than strided has no kernel on this build's device key.
    with pytest.raises(NotImplementedError):
        flag_gems._empty_affine_quantized(
            [2],
            dtype=torch.qint8,
            layout=torch.sparse_coo,
            device=flag_gems.device,
        )

    # pin_memory is accepted on the device and is a no-op there.
    pinned = _call([2], dtype=torch.qint8, pin_memory=True)
    assert pinned.device.type == flag_gems.device
    assert pinned.q_scale() == 1.0
    _assert_same_meta(pinned, _call([2], dtype=torch.qint8))


@pytest.mark._empty_affine_quantized
def test_accuracy__empty_affine_quantized_dispatched_path():
    # The operator is a factory, so ATen's dispatch table for it has no plain
    # device key that a quantized request can reach: a per-key sentinel probe on
    # this build (one fresh process per key) measured that the CUDA key is only
    # ever entered for a *non-quantized* dtype, that the Autograd and
    # QuantizedCUDA/QuantizedCPU keys are not reachable from the
    # ``torch.ops.aten`` packet for this operator, and that
    # ``ADInplaceOrView`` is reached for every quantized request. The
    # registration must therefore carry that extra key, and a dispatched call
    # through the aten packet must execute the submitted implementation.
    config_entries = [
        entry
        for entry in flag_gems._FULL_CONFIG
        if entry and entry[0] == "_empty_affine_quantized"
    ]
    assert config_entries, "no _FULL_CONFIG entry for the operator"
    extra_keys = tuple(config_entries[0][3]) if len(config_entries[0]) > 3 else ()
    assert extra_keys == ("ADInplaceOrView",), (
        "the dispatched path needs the ADInplaceOrView key (measured), got "
        f"{extra_keys!r}"
    )

    from torch.library import Library

    lib = Library("aten", "IMPL")
    hits = []

    def sentinel(
        size,
        *,
        dtype=None,
        layout=None,
        device=None,
        pin_memory=None,
        scale=1.0,
        zero_point=0,
        memory_format=None,
    ):
        hits.append(scale)
        # Delegate to the submitted implementation. Its own delegation excludes
        # this key, so this wrapper is entered exactly once per dispatched call.
        return flag_gems._empty_affine_quantized(
            size,
            dtype=dtype,
            layout=layout,
            device=device,
            pin_memory=pin_memory,
            scale=scale,
            zero_point=zero_point,
            memory_format=(
                memory_format if memory_format is not None else torch.contiguous_format
            ),
        )

    lib.impl("_empty_affine_quantized", sentinel, "ADInplaceOrView")
    try:
        dispatched = torch.ops.aten._empty_affine_quantized(
            [4, 8], dtype=torch.quint8, device=flag_gems.device, scale=0.5, zero_point=3
        )
        assert hits == [0.5], f"dispatched call did not reach the impl: {hits}"
        assert dispatched.shape == torch.Size([4, 8])
        assert dispatched.q_scale() == 0.5
        assert dispatched.q_zero_point() == 3
        assert dispatched.qscheme() == torch.per_tensor_affine

        # Repeated dispatched calls stay routed and do not recurse.
        for _ in range(2):
            again = torch.ops.aten._empty_affine_quantized(
                [4, 8], dtype=torch.quint8, device=flag_gems.device
            )
            assert again.qscheme() == torch.per_tensor_affine
        assert hits == [0.5, 1.0, 1.0], f"repeat dispatches lost routing: {hits}"

        # The ``torch._empty_affine_quantized`` builtin is *not* dispatched
        # through this key (measured on this build: zero sentinel hits), so it
        # keeps running the native kernel. Pinned so the difference stays
        # visible rather than being assumed away: the tested call path through
        # which this registration executes the submitted implementation is the
        # ``torch.ops.aten`` packet.
        before = len(hits)
        via_builtin = torch._empty_affine_quantized(
            [4, 8], dtype=torch.quint8, device=flag_gems.device
        )
        assert len(hits) == before, "the torch builtin unexpectedly routed through it"
        assert via_builtin.qscheme() == torch.per_tensor_affine
        _assert_same_meta(via_builtin, _call([4, 8], dtype=torch.quint8))
    finally:
        lib._destroy()

    # After removing the sentinel the dispatched path is native again and still
    # consistent with the submitted implementation.
    after = torch.ops.aten._empty_affine_quantized(
        [4, 8], dtype=torch.quint8, device=flag_gems.device
    )
    assert after.qscheme() == torch.per_tensor_affine
    _assert_same_meta(after, _call([4, 8], dtype=torch.quint8))


@pytest.mark._empty_affine_quantized
def test_accuracy__empty_affine_quantized_dispatch_stability():
    # Repeated calls (plus an unrelated aten dispatch in between) must not
    # recurse, drift or leak state: the re-entrancy marker is per-thread and must
    # be released by the finally block on every path, including the failing one.
    for _ in range(3):
        res = _call([4, 8], dtype=torch.quint8, scale=0.5, zero_point=3)
        assert res.q_scale() == 0.5
        assert res.q_zero_point() == 3
        assert torch.ops.aten.dim(torch.randn(2, device=flag_gems.device)) == 1

    # Interleaving a failing unsupported-dtype call must not leave the marker
    # set: a following valid call still has to work.
    for _ in range(2):
        with pytest.raises(NotImplementedError):
            flag_gems._empty_affine_quantized(
                [4, 8], dtype=torch.float32, device=flag_gems.device
            )
        ok = _call([4, 8], dtype=torch.quint8)
        assert ok.q_scale() == 1.0
        assert ok.qscheme() == torch.per_tensor_affine


@pytest.mark._empty_affine_quantized
def test_accuracy__empty_affine_quantized_out_overload():
    # ``.out`` is a CompositeExplicitAutograd kernel whose buffer handling lives
    # in the composite body; the implementation does not override it (the
    # ``.out`` overload carries no dtype/device argument, and the measured
    # routing of the extra key does not reach it), so it must keep working while
    # the base overload is registered. Verified against native behaviour: the
    # passed buffer receives the new quantizer parameters and is returned by
    # identity.
    # ``out_buffer`` must live on the reference's device for the phase's call to
    # be meaningful: under ``--ref=cpu`` the reference runs on the host, so the
    # buffer is derived from the reference side rather than converted
    # independently (the same trap that broke PR #641 in reverse).
    if cfg.TO_CPU:
        out_buffer = _reference([2, 3], dtype=torch.qint8, scale=1.0, zero_point=0)
    else:
        out_buffer = _call([2, 3], dtype=torch.qint8, scale=1.0, zero_point=0)
    returned = torch.ops.aten._empty_affine_quantized.out(
        [2, 3], scale=0.25, zero_point=2, out=out_buffer
    )

    assert returned is out_buffer
    assert returned.shape == torch.Size([2, 3])
    assert returned.q_scale() == 0.25
    assert returned.q_zero_point() == 2
    assert returned.qscheme() == torch.per_tensor_affine
    assert returned.int_repr().dtype == torch.int8

    # A differently-quantized out buffer keeps its quantized dtype; the new
    # affine parameters replace the old ones.
    qint32_buffer = _reference([2], dtype=torch.qint32, scale=1.0, zero_point=0)
    refilled = torch.ops.aten._empty_affine_quantized.out(
        [2], scale=3.0, zero_point=5, out=qint32_buffer
    )
    assert refilled is qint32_buffer
    assert refilled.dtype == torch.qint32
    assert refilled.q_scale() == 3.0
    assert refilled.q_zero_point() == 5

    # Resizing a populated out buffer is not supported: the composite body
    # forwards to aten::resize_ with a quantized tensor, and neither this
    # build's device key nor its QuantizedCPU key implements that. The
    # rejection is therefore part of the contract on both sides.
    populated = _reference([2, 3], dtype=torch.qint8)
    with pytest.raises(NotImplementedError):
        torch.ops.aten._empty_affine_quantized.out(
            [4, 5], scale=2.0, zero_point=9, out=populated
        )

    # A non-quantized buffer is rejected: the .out schema has no dtype argument,
    # so the buffer's own dtype is what the composite body forwards, and a
    # non-quantized dtype has no kernel on device (nor on the host, where the
    # rejection is the CPU stub's RuntimeError).
    int8_buffer = torch.empty(
        [2, 3], dtype=torch.int8, device="cpu" if cfg.TO_CPU else flag_gems.device
    )
    with pytest.raises(RuntimeError if cfg.TO_CPU else NotImplementedError):
        torch.ops.aten._empty_affine_quantized.out(
            [2, 3], scale=1.0, zero_point=0, out=int8_buffer
        )

    # The implementation does not override the .out kernel: the extra key that
    # routes the base overload does not intercept this one (measured), so this
    # call is answered by the native composite body.
    if not cfg.TO_CPU:
        from torch.library import Library

        lib = Library("aten", "IMPL")
        hits = []

        def sentinel(size, **kwargs):
            hits.append(size)
            with torch._C._ExcludeDispatchKeyGuard(
                torch._C.DispatchKeySet(torch._C.DispatchKey.ADInplaceOrView)
            ):
                return torch.ops.aten._empty_affine_quantized(size, **kwargs)

        lib.impl("_empty_affine_quantized", sentinel, "ADInplaceOrView")
        try:
            probe_buffer = _call([2, 0], dtype=torch.qint8)
            before = len(hits)
            torch.ops.aten._empty_affine_quantized.out(
                [2, 0], scale=1.0, zero_point=0, out=probe_buffer
            )
            assert (
                len(hits) == before
            ), "the .out overload unexpectedly routed into the base override"
        finally:
            lib._destroy()
