# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch
from _pytest.mark.structures import Mark, MarkDecorator

import flag_gems

from . import accuracy_utils as utils
from .conftest import QUICK_MODE

# ``_slow_conv2d_forward`` starts with an underscore, and ``pytest.mark`` refuses
# to generate a marker via attribute access for such names. Register it directly
# on the MarkGenerator so ``@pytest.mark._slow_conv2d_forward`` and
# ``-m _slow_conv2d_forward`` both work.
setattr(
    pytest.mark,
    "_slow_conv2d_forward",
    MarkDecorator(Mark("_slow_conv2d_forward", (), {}, _ispytest=True), _ispytest=True),
)

ATEN_OP = torch.ops.aten._slow_conv2d_forward.default

# (N, C_in, H, W, C_out, KH, KW, stride_h, stride_w, pad_h, pad_w). The schema
# has no dilation or groups argument.
# The implementation picks its kernel configuration from K = C_in*KH*KW and
# C_out: fp32 uses kChunk = min(64, next_pow2(K)) with a masked tail chunk and
# the config table (C_out<=32 -> 128/32/4; K>=1024 -> 64/64/16; else 64/64/8);
# fp16/bf16 use C_out<=32 with K<=128 -> 128/64/8 and K>128 -> 128/32/4, and
# C_out>32 -> 32/64/8. fp64 takes the separate naive direct-conv kernel.
CONV2D_CASES = [
    # small 3x3, C_out <= 32 (fp32 128/32/4 branch; fp16/bf16 K>128 branch)
    (1, 2, 5, 5, 3, 3, 3, 1, 1, 0, 0),
    # stride 2 with padding: the plastic (masked) taps of both kernels
    (2, 3, 9, 9, 5, 3, 3, 2, 2, 1, 1),
    # 1x1 pointwise: K = C_in <= 128 (fp16/bf16 128/64/8 branch)
    (2, 8, 7, 7, 4, 1, 1, 1, 1, 0, 0),
    # C_out > 32 (fp32 64/64/8 branch; fp16/bf16 32/64/8 branch)
    (2, 8, 12, 12, 40, 3, 3, 1, 1, 1, 1),
    # deep reduction: K = 128*3*3 = 1152 >= 1024 (fp32 64/64/16 branch)
    (1, 128, 10, 10, 48, 3, 3, 1, 1, 1, 1),
    # asymmetric kernel and asymmetric stride/padding
    (2, 4, 11, 13, 6, 5, 3, 2, 1, 2, 0),
    # N > 1, wide kernel, stride/padding on both axes
    (3, 2, 17, 19, 2, 3, 3, 1, 3, 2, 1),
    # K = 3*5*5 = 75 -> kChunk 64, NCHUNK 2 with a masked tail chunk
    (1, 3, 9, 9, 33, 5, 5, 2, 2, 2, 3),
]
if QUICK_MODE:
    CONV2D_CASES = [
        (1, 2, 5, 5, 3, 3, 3, 1, 1, 0, 0),
        (2, 8, 12, 12, 40, 3, 3, 1, 1, 1, 1),
    ]

FLOAT_DTYPES = utils.FLOAT_DTYPES if not QUICK_MODE else [torch.float32]
# fp64 selects the naive direct-conv kernel (tl.dot has no fp64 lowering).
FP64_DTYPES = [torch.float64] if utils.fp64_is_supported else []


def _gen_input(shape, dtype):
    return torch.randn(shape, dtype=dtype, device=flag_gems.device)


def _h_out(case, index):
    (n, c_in, h, w, c_out, kh, kw, sh, sw, ph, pw) = case
    if index == 0:
        return (h + 2 * ph - kh) // sh + 1
    return (w + 2 * pw - kw) // sw + 1


def _assert_matches(case, dtype, res_out, ref_out):
    (n, c_in, h, w, c_out, kh, kw, sh, sw, ph, pw) = case
    assert res_out.shape == (n, c_out, _h_out(case, 0), _h_out(case, 1))
    assert res_out.dtype == dtype
    # Native allocates a fresh contiguous output for every input layout.
    assert res_out.is_contiguous()
    assert res_out.is_contiguous() == ref_out.is_contiguous()
    assert res_out.stride() == ref_out.stride()
    assert res_out.shape == ref_out.shape
    # Reduction-length-scaled atol: the fp32 kernel's fp16x3 split dot and the
    # fp16/bf16 tensor-core dot accumulate over K = C_in*KH*KW products (repo
    # convention for the conv reductions, cf. test_conv2d / test_cudnn_rnn_backward).
    utils.gems_assert_close(
        res_out, ref_out.to(dtype), dtype, reduce_dim=c_in * kh * kw
    )


@pytest.mark._slow_conv2d_forward
@pytest.mark.parametrize("case", CONV2D_CASES)
@pytest.mark.parametrize("dtype", FLOAT_DTYPES + FP64_DTYPES)
@pytest.mark.parametrize("bias", [False, True])
def test_accuracy__slow_conv2d_forward(case, dtype, bias):
    (n, c_in, h, w, c_out, kh, kw, sh, sw, ph, pw) = case
    inp = _gen_input((n, c_in, h, w), dtype)
    weight = _gen_input((c_out, c_in, kh, kw), dtype)
    b = _gen_input((c_out,), dtype) if bias else None

    ref_out = ATEN_OP(
        utils.to_reference(inp, True),
        utils.to_reference(weight, True),
        [kh, kw],
        utils.to_reference(b, True),
        [sh, sw],
        [ph, pw],
    )
    res_out = flag_gems._slow_conv2d_forward(
        inp, weight, [kh, kw], b, [sh, sw], [ph, pw]
    )

    _assert_matches(case, dtype, res_out, ref_out)
    assert res_out.data_ptr() != inp.data_ptr()
    assert res_out._base is None


@pytest.mark._slow_conv2d_forward
@pytest.mark.parametrize(
    "case",
    (
        [(1, 2, 5, 5, 3, 3, 3, 1, 1, 0, 0), (2, 3, 9, 9, 5, 3, 3, 2, 2, 1, 1)]
        if QUICK_MODE
        else [
            (1, 2, 5, 5, 3, 3, 3, 1, 1, 0, 0),
            (2, 3, 9, 9, 5, 3, 3, 2, 2, 1, 1),
            (1, 4, 6, 6, 6, 3, 3, 1, 1, 1, 1),
            (2, 4, 11, 13, 6, 5, 3, 2, 1, 2, 0),
        ]
    ),
)
@pytest.mark.parametrize("layout", ["input_nc", "weight_nc", "both_nc"])
@pytest.mark.parametrize("dtype", FLOAT_DTYPES + FP64_DTYPES)
def test_accuracy__slow_conv2d_forward_non_contiguous(case, layout, dtype):
    """Non-contiguous operands (same logical shape, channels-last storage).

    The submitted wrapper materializes a contiguous copy of each operand
    before the launch; native's CUDA kernel accepts strided operands directly.
    The measured result is value-identical, so both sides are compared as-is.
    """
    (n, c_in, h, w, c_out, kh, kw, sh, sw, ph, pw) = case
    inp = _gen_input((n, c_in, h, w), dtype)
    weight = _gen_input((c_out, c_in, kh, kw), dtype)
    if layout in ("input_nc", "both_nc"):
        inp = torch.randn(n, h, w, c_in, dtype=dtype, device=flag_gems.device)
        inp = inp.permute(0, 3, 1, 2)
        assert not inp.is_contiguous()
    if layout in ("weight_nc", "both_nc"):
        weight = torch.randn(c_out, kh, kw, c_in, dtype=dtype, device=flag_gems.device)
        weight = weight.permute(0, 3, 1, 2)
        assert not weight.is_contiguous()

    ref_out = ATEN_OP(
        utils.to_reference(inp, True),
        utils.to_reference(weight, True),
        [kh, kw],
        None,
        [sh, sw],
        [ph, pw],
    )
    res_out = flag_gems._slow_conv2d_forward(
        inp, weight, [kh, kw], None, [sh, sw], [ph, pw]
    )

    _assert_matches(case, dtype, res_out, ref_out)


@pytest.mark._slow_conv2d_forward
@pytest.mark.parametrize("dtype", FLOAT_DTYPES + FP64_DTYPES)
def test_accuracy__slow_conv2d_forward_transposed_operands(dtype):
    """A transposed (2,3)-swapped) operand keeps its logical shape but is not
    contiguous -- a second flavour of the strided path."""
    inp = _gen_input((1, 4, 6, 6), dtype).transpose(2, 3)
    weight = _gen_input((3, 4, 3, 3), dtype).transpose(2, 3)
    assert not inp.is_contiguous()
    assert not weight.is_contiguous()
    case = (1, 4, 6, 6, 3, 3, 3, 1, 1, 1, 1)

    ref_out = ATEN_OP(
        utils.to_reference(inp, True),
        utils.to_reference(weight, True),
        [3, 3],
        None,
        [1, 1],
        [1, 1],
    )
    res_out = flag_gems._slow_conv2d_forward(inp, weight, [3, 3], None, [1, 1], [1, 1])

    _assert_matches(case, dtype, res_out, ref_out)


@pytest.mark._slow_conv2d_forward
@pytest.mark.parametrize("dtype", FLOAT_DTYPES + FP64_DTYPES)
@pytest.mark.parametrize("bias_present", [False, True])
def test_accuracy__slow_conv2d_forward_batch4_cases(dtype, bias_present):
    """Coverage of the kernel-configuration branches plus asymmetric
    stride/padding and a masked K tail chunk, on one tensor-generation
    function shared with the main sweep."""
    for case in CONV2D_CASES:
        (n, c_in, h, w, c_out, kh, kw, sh, sw, ph, pw) = case
        inp = _gen_input((n, c_in, h, w), dtype)
        weight = _gen_input((c_out, c_in, kh, kw), dtype)
        b = _gen_input((c_out,), dtype) if bias_present else None
        ref_out = ATEN_OP(
            utils.to_reference(inp, True),
            utils.to_reference(weight, True),
            [kh, kw],
            utils.to_reference(b, True),
            [sh, sw],
            [ph, pw],
        )
        res_out = flag_gems._slow_conv2d_forward(
            inp, weight, [kh, kw], b, [sh, sw], [ph, pw]
        )
        _assert_matches(case, dtype, res_out, ref_out)


@pytest.mark._slow_conv2d_forward
@pytest.mark.parametrize("dtype", FLOAT_DTYPES + FP64_DTYPES)
def test_accuracy__slow_conv2d_forward_single_element(dtype):
    """Smallest legal convolution: 1x1 input, 1x1 kernel, no padding."""
    inp = _gen_input((1, 1, 1, 1), dtype)
    weight = _gen_input((1, 1, 1, 1), dtype)
    b = _gen_input((1,), dtype)
    case = (1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0)

    ref_out = ATEN_OP(
        utils.to_reference(inp, True),
        utils.to_reference(weight, True),
        [1, 1],
        utils.to_reference(b, True),
        [1, 1],
        [0, 0],
    )
    res_out = flag_gems._slow_conv2d_forward(inp, weight, [1, 1], b, [1, 1], [0, 0])

    _assert_matches(case, dtype, res_out, ref_out)


@pytest.mark._slow_conv2d_forward
@pytest.mark.parametrize("dtype", FLOAT_DTYPES + FP64_DTYPES)
def test_accuracy__slow_conv2d_forward_empty_batch(dtype):
    """N == 0 is the only zero-extent dimension native accepts. The output
    keeps the empty batch dimension and the kernel's n-indexed output pointer
    arithmetic is never executed."""
    inp = _gen_input((0, 3, 5, 5), dtype)
    weight = _gen_input((4, 3, 3, 3), dtype)

    ref_out = ATEN_OP(
        utils.to_reference(inp, True),
        utils.to_reference(weight, True),
        [3, 3],
        None,
        [1, 1],
        [1, 1],
    )
    res_out = flag_gems._slow_conv2d_forward(inp, weight, [3, 3], None, [1, 1], [1, 1])

    assert res_out.shape == ref_out.shape == (0, 4, 3, 3)
    assert res_out.numel() == 0
    assert res_out.dtype == dtype
    utils.gems_assert_close(res_out, ref_out.to(dtype), dtype)


@pytest.mark._slow_conv2d_forward
def test_accuracy__slow_conv2d_forward_dispatch_stability():
    """Repeated dispatch plus an unrelated aten op must not corrupt results
    (no shared mutable state across calls: the wrapper allocates a fresh
    output and a fresh transposed weight copy on every call)."""
    inp = _gen_input((2, 3, 7, 7), torch.float32)
    weight = _gen_input((5, 3, 3, 3), torch.float32)

    ref_out = ATEN_OP(
        utils.to_reference(inp, True),
        utils.to_reference(weight, True),
        [3, 3],
        None,
        [1, 1],
        [1, 1],
    )
    for _ in range(3):
        res_out = flag_gems._slow_conv2d_forward(
            inp, weight, [3, 3], None, [1, 1], [1, 1]
        )
        utils.gems_assert_close(res_out, ref_out, torch.float32)
        assert torch.ops.aten.dim(inp) == 4


# ---------------------------------------------------------------------------
# Error behaviour. Native validates the input rank first, then the weight
# shape, then the output size, and nested checks use different wording on the
# CPU and CUDA kernels ("[2, 2]" vs "(2 x 2)"). Assert the exception CLASS on
# both sides plus only those fragments that are identical on every path
# (batch addendum A1: never pin one build's full sentence).
# ---------------------------------------------------------------------------
@pytest.mark._slow_conv2d_forward
@pytest.mark.parametrize("bad_shape", [(2, 5, 5), (1, 1, 2, 5, 5), ()])
def test_accuracy__slow_conv2d_forward_bad_input_rank(bad_shape):
    inp = torch.randn(bad_shape, device=flag_gems.device)
    weight = torch.randn((3, 2, 3, 3), device=flag_gems.device)

    ref_inp = utils.to_reference(inp)
    ref_weight = utils.to_reference(weight)
    with pytest.raises(RuntimeError, match="4D input"):
        ATEN_OP(ref_inp, ref_weight, [3, 3], None, [1, 1], [0, 0])
    with pytest.raises(RuntimeError, match="4D input"):
        flag_gems._slow_conv2d_forward(inp, weight, [3, 3], None, [1, 1], [0, 0])


@pytest.mark._slow_conv2d_forward
def test_accuracy__slow_conv2d_forward_kernel_larger_than_input():
    """Kernel larger than the padded input (H_out <= 0 / W_out <= 0). The
    supplied source returned an empty tensor here; measured native raises
    RuntimeError on the CPU reference and on the CUDA kernel, so the
    implementation mirrors that instead (guard added, computation unchanged)."""
    inp = torch.randn((1, 2, 2, 2), device=flag_gems.device)
    weight = torch.randn((3, 2, 3, 3), device=flag_gems.device)
    fragment = "Kernel size can't be greater than actual input size"

    with pytest.raises(RuntimeError, match=fragment):
        ATEN_OP(
            utils.to_reference(inp),
            utils.to_reference(weight),
            [3, 3],
            None,
            [1, 1],
            [0, 0],
        )
    with pytest.raises(RuntimeError, match=fragment):
        flag_gems._slow_conv2d_forward(inp, weight, [3, 3], None, [1, 1], [0, 0])


@pytest.mark._slow_conv2d_forward
def test_accuracy__slow_conv2d_forward_zero_spatial_dim():
    """A zero-extent spatial dim is rejected by both paths but with different
    wordings (native CPU: 'Expected non-zero size for input dimension 2'
    l10n; native CUDA: 'non-empty input tensor expected'; the wrapper's
    output-size guard: the kernel-size message). Only the class is asserted."""
    inp = torch.randn((1, 2, 0, 5), device=flag_gems.device)
    weight = torch.randn((3, 2, 1, 1), device=flag_gems.device)

    with pytest.raises(RuntimeError):
        ATEN_OP(
            utils.to_reference(inp),
            utils.to_reference(weight),
            [1, 1],
            None,
            [1, 1],
            [0, 0],
        )
    with pytest.raises(RuntimeError):
        flag_gems._slow_conv2d_forward(inp, weight, [1, 1], None, [1, 1], [0, 0])


@pytest.mark._slow_conv2d_forward
@pytest.mark.parametrize("weight_dtype", [torch.float64, torch.float16, torch.int64])
def test_accuracy__slow_conv2d_forward_mixed_dtypes(weight_dtype):
    """Native rejects an input/weight dtype mismatch (measured: 'expected
    scalar type Float but found Double' on CPU and CUDA). The wrapper's
    guard raises the same class; only the class is asserted."""
    inp = torch.randn((1, 2, 5, 5), device=flag_gems.device)
    weight = torch.randn((3, 2, 3, 3), dtype=weight_dtype, device=flag_gems.device)

    with pytest.raises(RuntimeError):
        ATEN_OP(
            utils.to_reference(inp),
            utils.to_reference(weight),
            [3, 3],
            None,
            [1, 1],
            [0, 0],
        )
    with pytest.raises(RuntimeError):
        flag_gems._slow_conv2d_forward(inp, weight, [3, 3], None, [1, 1], [0, 0])


@pytest.mark._slow_conv2d_forward
@pytest.mark.parametrize("bad_len", [2, 4, 8])
def test_accuracy__slow_conv2d_forward_bias_length_mismatch(bad_len):
    """A bias whose length differs from C_out is rejected by native (measured
    on CPU and CUDA: 'Expected bias to have shape [3] but got [4]'). Without
    a guard the naive kernel would read past the end of the bias tensor."""
    inp = torch.randn((1, 2, 5, 5), device=flag_gems.device)
    weight = torch.randn((3, 2, 3, 3), device=flag_gems.device)
    b = torch.randn((bad_len,), device=flag_gems.device)

    with pytest.raises(RuntimeError, match="bias"):
        ATEN_OP(
            utils.to_reference(inp),
            utils.to_reference(weight),
            [3, 3],
            utils.to_reference(b),
            [1, 1],
            [0, 0],
        )
    with pytest.raises(RuntimeError, match="bias"):
        flag_gems._slow_conv2d_forward(inp, weight, [3, 3], b, [1, 1], [0, 0])
