# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch
from _pytest.mark.structures import Mark, MarkDecorator

import flag_gems

from . import accuracy_utils as utils
from .conftest import QUICK_MODE

# The operator name starts with a letter, so the marker is a normal attribute
# access; the setattr form is kept for symmetry with the underscore-prefixed
# KernelGen tests and is harmless.
setattr(
    pytest.mark,
    "slow_conv_dilated3d",
    MarkDecorator(Mark("slow_conv_dilated3d", (), {}, _ispytest=True), _ispytest=True),
)
setattr(
    pytest.mark,
    "slow_conv_dilated3d_out",
    MarkDecorator(
        Mark("slow_conv_dilated3d_out", (), {}, _ispytest=True), _ispytest=True
    ),
)

# 3-D conv is memory-hungry (the input is 5-D and the contraction is
# C_in * kD * kH * kW). Every shape below is chosen to stay small but still
# cover a real branch of the implementation:
#
#   * `_pick` branch (a): per_n_p < 1024            -> BC=16, BP=16
#   * `_pick` branch (b): KVOL3 == 1 (1x1x1 GEMM)   -> BC=16, BP=128
#   * `_pick` branch (c): COUT <= 16, big spatial    -> BC=16, BP=128
#   * `_pick` branch (d): COUT <= 32, K >= 800       -> BC=16, BP=64
#   * `_pick` branch (e): COUT <= 32, K <  800       -> BC=32, BP=32
#   * `_pick` branch (f): COUT >= 64, K >= 1024      -> BC=32, BP=64
#   * `_pick` branch (g): COUT >= 64, K <  1024      -> BC=32, BP=32
#   * num_warps = 8 (tile > 2048) vs 4
#   * PREC = 0 (fp32 small K, ieee), 1 (fp32 K >= 1024, tf32x3), 2 (fp16/bf16,
#     default tl.dot precision)
#   * HAS_BIAS True/False, FP64 True/False
SHAPES = [
    ((1, 2, 5, 5, 5), (5, 2, 3, 3, 3), (3, 3, 3), 1, 0, 1),  # (a) tiny spatial
    ((1, 4, 9, 9, 9), (5, 4, 1, 1, 1), (1, 1, 1), 1, 0, 1),  # (b) 1x1x1
    ((2, 8, 7, 7, 7), (8, 8, 3, 3, 3), (3, 3, 3), 1, 1, 1),  # (c) COUT <= 16
    ((2, 16, 7, 7, 7), (24, 16, 3, 3, 3), (3, 3, 3), 1, 0, 1),  # (d) K >= 800
    ((2, 4, 7, 7, 7), (24, 4, 2, 2, 2), (2, 2, 2), 1, 0, 1),  # (e) K < 800
    ((1, 16, 5, 5, 5), (64, 16, 3, 3, 3), (3, 3, 3), 1, 1, 1),  # (f) K >= 1024
    ((2, 8, 5, 5, 5), (64, 8, 2, 2, 2), (2, 2, 2), 1, 0, 1),  # (g) K < 1024
]
if QUICK_MODE:
    # One representative per `_pick` family, plus (a) which also carries the
    # tiny-spatial branch; dtype coverage is trimmed in QUICK_MODE only where
    # the dtype itself is unsupported by the hardware.
    SHAPES = [SHAPES[0], SHAPES[2], SHAPES[5]]

# Geometry sweep (applied to the small (1, 2, 5, 5, 5) base shape):
# dilated geometry (dilation > 1), strided geometry, and negative padding.
GEOMETRY = (
    [((1, 2, 7, 7, 7), (3, 2, 3, 3, 3), (3, 3, 3), 1, 0, 2)]
    if QUICK_MODE
    else [
        ((1, 2, 7, 7, 7), (3, 2, 3, 3, 3), (3, 3, 3), 1, 0, 2),
        ((1, 2, 9, 9, 9), (3, 2, 2, 2, 2), (2, 2, 2), 2, 1, 1),
        ((1, 2, 8, 8, 8), (3, 2, 3, 3, 3), (3, 3, 3), 3, 2, 2),
        ((2, 2, 6, 6, 6), (3, 2, 4, 5, 6), (4, 5, 6), 1, 0, 1),
        # negative padding shrinks the output (native supports it; measured)
        ((1, 2, 7, 7, 7), (3, 2, 3, 3, 3), (3, 3, 3), 1, -1, 1),
        # stride larger than the kernel with asymmetric padding
        ((1, 2, 9, 9, 9), (3, 2, 3, 3, 3), (3, 3, 3), 3, 1, 2),
    ]
)

# Dtypes the kernel itself handles: FP64 (FP64=True, fp32 accumulation), fp32
# (PREC=0/1) and the two half-width lanes (PREC=2). Native accepts int64 on
# CPU but NOT on CUDA (AT_DISPATCH_FLOATING_TYPES_AND2(kHalf, kBFloat16) in the
# CUDA kernel), so int64 is deliberately not part of the CUDA sweep.
FLOAT_DTYPES = (
    [torch.float32]
    if QUICK_MODE
    else [torch.float16, torch.bfloat16, torch.float32, torch.float64]
)


@pytest.fixture(autouse=True)
def _high_precision_reference():
    """Switch the native CUDA lane out of TF32 for every test in this file."""
    _disable_tf32()
    yield


def _disable_tf32():
    """The native CUDA fp32 lane multiplies through TF32 unless it is switched
    off (measured: 2.7e-4 relative error against its own fp64 reference with the
    default allow_tf32=True, 2.7e-6 with it off). Tests that compare native fp32
    against a high-precision reference switch it off, exactly as
    tests/test_conv3d.py does; the submitted kernel is unaffected (it uses
    ieee for K < 1024 and tf32x3 above, measured at 2e-7..5e-7 relative)."""
    if flag_gems.device == "cuda":
        torch.backends.cuda.matmul.allow_tf32 = False
        torch.backends.cudnn.allow_tf32 = False


def _t(v):
    if isinstance(v, (tuple, list)):
        return list(int(x) for x in v)
    return [int(v)] * 3


def _native(x, w, ks, bias, s, p, d, out=None):
    """Call the ATen reference. Under --ref=cpu the tensors are CPU copies."""
    if out is None:
        return torch.ops.aten.slow_conv_dilated3d(
            x, w, _t(ks), bias, _t(s), _t(p), _t(d)
        )
    return torch.ops.aten.slow_conv_dilated3d.out(
        x, w, _t(ks), bias, _t(s), _t(p), _t(d), out=out
    )


def _out_size(n, dil, k, s, p):
    return (n + 2 * p - dil * (k - 1) - 1) // s + 1


def _make(shape, dtype, seed=0):
    torch.manual_seed(seed)
    if dtype in (torch.float16, torch.bfloat16, torch.float32, torch.float64):
        return torch.randn(shape, dtype=torch.float32, device=flag_gems.device).to(
            dtype
        )
    raise AssertionError(f"unsupported dtype in test helper: {dtype}")


@pytest.mark.slow_conv_dilated3d
@pytest.mark.parametrize("dtype", FLOAT_DTYPES)
@pytest.mark.parametrize("shape, kshape, ks, s, p, d", SHAPES)
@pytest.mark.parametrize("bias_on", [False, True])
def test_accuracy_slow_conv_dilated3d(shape, kshape, ks, s, p, d, dtype, bias_on):
    x = _make(shape, dtype)
    w = _make(kshape, dtype, seed=1)
    bias = _make((kshape[0],), dtype, seed=2) if bias_on else None

    ref_x = utils.to_reference(x, upcast=True)
    ref_w = utils.to_reference(w, upcast=True)
    ref_b = utils.to_reference(bias, upcast=True) if bias is not None else None
    # Compare at the SAME precision on both sides. Under --ref=cpu the
    # reference is upcast to fp64 on CPU; the implementation computes in fp32
    # (fp16/bf16 inputs go through the PREC=2 tl.dot lane, fp64 inputs through
    # the FP64 fp32-accumulate lane), so an exact equality assertion against a
    # CPU-fp64 reference would be pinning a cross-backend bit-for-bit match
    # that neither side promises. gems_assert_close with the dtype's resolution
    # is the repository's contract for this class of op.
    ref_out = _native(ref_x, ref_w, ks, ref_b, s, p, d)

    res_out = flag_gems.slow_conv_dilated3d(
        x, w, _t(ks), bias=bias, stride=_t(s), padding=_t(p), dilation=_t(d)
    )

    n, cin, dd, hh, ww = shape
    cout = kshape[0]
    kd, kh, kw = ks
    sd, sh, sw = (s, s, s) if isinstance(s, int) else s
    pd, ph, pw = (p, p, p) if isinstance(p, int) else p
    dl, dh, dw = (d, d, d) if isinstance(d, int) else d
    expected = (
        n,
        cout,
        _out_size(dd, dl, kd, sd, pd),
        _out_size(hh, dh, kh, sh, ph),
        _out_size(ww, dw, kw, sw, pw),
    )
    assert res_out.shape == expected
    assert res_out.shape == tuple(ref_out.shape)
    assert res_out.dtype == dtype
    assert res_out.is_contiguous()
    utils.gems_assert_close(res_out, ref_out, dtype)


@pytest.mark.slow_conv_dilated3d
@pytest.mark.parametrize("shape, kshape, ks, s, p, d", GEOMETRY)
@pytest.mark.parametrize("dtype", [torch.float32])
def test_accuracy_slow_conv_dilated3d_geometry(shape, kshape, ks, s, p, d, dtype):
    # Dilation geometry (dilation > 1 widens the receptive field, so every tap
    # lands at `oh * stride + kh * dilation - padding`), stride geometry and
    # NEGATIVE padding (which shrinks the output) must match native exactly.
    x = _make(shape, dtype, seed=3)
    w = _make(kshape, dtype, seed=4)
    bias = _make((kshape[0],), dtype, seed=5)

    ref_x = utils.to_reference(x, upcast=True)
    ref_w = utils.to_reference(w, upcast=True)
    ref_b = utils.to_reference(bias, upcast=True)
    ref_out = _native(ref_x, ref_w, ks, ref_b, s, p, d)

    res_out = flag_gems.slow_conv_dilated3d(
        x, w, _t(ks), bias=bias, stride=_t(s), padding=_t(p), dilation=_t(d)
    )

    utils.gems_assert_close(res_out, ref_out, dtype)


@pytest.mark.slow_conv_dilated3d
@pytest.mark.parametrize("ks", [(3, 3, 3), (1, 1, 1), (2, 3, 4)])
def test_accuracy_slow_conv_dilated3d_int_geometry_args(ks):
    # kernel_size/stride/padding/dilation accept a single int (broadcast to all
    # three axes) or a 3-element sequence; both forms are exercised, and the
    # int form must equal the explicit triple.
    # Input 8^3 keeps every stride/dilation pair here on a positive output size:
    # with a 6^3 input the (2, 3, 4) kernel at stride/dilation 2 gives
    # DO=2, HO=1, WO=0, and this build's native CUDA reference refuses to launch
    # a zero-sized grid ("N > 0 INTERNAL ASSERT FAILED ... blocks must be
    # positive", measured), so an 8^3 input (out 3, 2, 2) is used instead.
    x = _make((1, 2, 8, 8, 8), torch.float32, seed=6)
    w = _make((4, 2) + ks, torch.float32, seed=7)
    ref_x = utils.to_reference(x, upcast=True)
    ref_w = utils.to_reference(w, upcast=True)

    for scalar, triple in ((1, _t(1)), (2, _t(2))):
        res_i = flag_gems.slow_conv_dilated3d(x, w, ks, stride=scalar, dilation=scalar)
        res_s = flag_gems.slow_conv_dilated3d(
            x, w, _t(ks), stride=triple, dilation=triple
        )
        # Native requires 3-element lists, so the reference always takes the
        # explicit triple; the int form must be its equal.
        ref_out = _native(ref_x, ref_w, ks, None, triple, 0, triple)
        assert res_i.shape == tuple(ref_out.shape)
        assert res_s.shape == tuple(ref_out.shape)
        assert res_i.data_ptr() != res_s.data_ptr()
        torch.testing.assert_close(res_i, res_s, atol=0.0, rtol=0.0)
        utils.gems_assert_close(res_i, ref_out, torch.float32)
        utils.gems_assert_close(res_s, ref_out, torch.float32)


@pytest.mark.slow_conv_dilated3d
@pytest.mark.parametrize("dtype", [torch.float32] if QUICK_MODE else FLOAT_DTYPES)
def test_accuracy_slow_conv_dilated3d_bias_broadcast(dtype):
    # The bias is added per output channel over the whole spatial extent
    # (acc += bias[:, None] in the kernel); a nonzero bias with a zero weight
    # isolates exactly that term, and the no-bias result must equal the
    # zero-bias result.
    x = _make((1, 2, 5, 5, 5), dtype, seed=8)
    w = torch.zeros((4, 2, 3, 3, 3), dtype=dtype, device=flag_gems.device)
    bias = _make((4,), dtype, seed=9)

    ref_x = utils.to_reference(x, upcast=True)
    ref_w = utils.to_reference(w, upcast=True)
    ref_b = utils.to_reference(bias, upcast=True)

    ref_bias = _native(ref_x, ref_w, (3, 3, 3), ref_b, 1, 0, 1)
    res_bias = flag_gems.slow_conv_dilated3d(x, w, [3, 3, 3], bias=bias)

    ref_none = _native(ref_x, ref_w, (3, 3, 3), None, 1, 0, 1)
    res_none = flag_gems.slow_conv_dilated3d(x, w, [3, 3, 3])

    utils.gems_assert_close(res_bias, ref_bias, dtype)
    utils.gems_assert_close(res_none, ref_none, dtype)
    # With a zero weight every output is exactly the channel bias. `got` is on
    # the reference's device (to_cpu), so the expectation is derived from the
    # already-converted reference bias, never from the CUDA-side tensor.
    got = utils.to_cpu(res_bias, ref_bias).reshape(4, -1)
    expected = ref_b.to(torch.float32).reshape(4, 1).expand_as(got)
    assert torch.equal(got, expected.to(got.dtype).to(got.device))


@pytest.mark.slow_conv_dilated3d
@pytest.mark.parametrize("n", [0, 1, 3])
def test_accuracy_slow_conv_dilated3d_batch(n):
    # The grid's third axis is the batch index; N=0 (empty output, short-circuit
    # before launch) and N>1 (per-batch offsets n * CIN * DHW) both matter.
    x = _make((n, 2, 5, 5, 5), torch.float32, seed=10)
    w = _make((3, 2, 3, 3, 3), torch.float32, seed=11)
    bias = _make((3,), torch.float32, seed=12)

    ref_x = utils.to_reference(x, upcast=True)
    ref_w = utils.to_reference(w, upcast=True)
    ref_b = utils.to_reference(bias, upcast=True)
    ref_out = _native(ref_x, ref_w, (3, 3, 3), ref_b, 1, 0, 1)
    res_out = flag_gems.slow_conv_dilated3d(x, w, [3, 3, 3], bias=bias)

    assert res_out.shape == (n, 3, 3, 3, 3)
    assert res_out.numel() == n * 3 * 27
    utils.gems_assert_close(res_out, ref_out, torch.float32)
    if n > 1:
        # Per-batch isolation: batch element n must not be affected by its
        # neighbours (the kernel's grid axis 2 is the batch index and the input
        # offset is n * CIN * DHW). Compare each slice against a single-batch
        # reference computed with the SAME weights and bias.
        for i in range(n):
            ref_i = _native(ref_x[i : i + 1], ref_w, (3, 3, 3), ref_b, 1, 0, 1)
            utils.gems_assert_close(res_out[i : i + 1], ref_i, torch.float32)


@pytest.mark.slow_conv_dilated3d
def test_accuracy_slow_conv_dilated3d_unbatched_input():
    # Native accepts a 4-D input (no batch dimension) and returns a 4-D result.
    # The contract is pinned against the 5-D lane, NOT against native's own 4-D
    # path: on CUDA this build's native 4-D call disagrees with its 5-D call by
    # 3.26 max abs (measured, job slow_conv_dilated3d-other-a1-090c2023), while
    # on CPU the two agree exactly and the submitted implementation answers the
    # 4-D case as the unsqueezed 5-D case (0.0 between its own two forms).
    x4 = _make((2, 5, 5, 5), torch.float32, seed=47)
    w = _make((3, 2, 3, 3, 3), torch.float32, seed=48)
    bias = _make((3,), torch.float32, seed=49)

    ref_x4 = utils.to_reference(x4, upcast=True)
    ref_w = utils.to_reference(w, upcast=True)
    ref_b = utils.to_reference(bias, upcast=True)
    ref_5d = _native(ref_x4.unsqueeze(0), ref_w, (3, 3, 3), ref_b, 1, 0, 1)
    res_out = flag_gems.slow_conv_dilated3d(x4, w, [3, 3, 3], bias=bias)
    res_5d = flag_gems.slow_conv_dilated3d(x4.unsqueeze(0), w, [3, 3, 3], bias=bias)

    assert res_out.shape == (3, 3, 3, 3)
    assert tuple(res_out.shape) == tuple(ref_5d.shape[1:])
    # The batched form of the same computation agrees bit-for-bit, and both
    # agree with the batched native result.
    torch.testing.assert_close(res_out, res_5d[0], atol=0.0, rtol=0.0)
    utils.gems_assert_close(res_out, ref_5d[0], torch.float32)
    # The 4-D result is a view of the freshly allocated 5-D storage.
    assert res_out.data_ptr() != x4.data_ptr()
    assert res_out.storage().size() == 3 * 3 * 3 * 3


@pytest.mark.slow_conv_dilated3d
def test_accuracy_slow_conv_dilated3d_unbatched_degenerate():
    # A 4-D input must keep its 4-D rank through the short-circuits too: an
    # empty output, a zero channel count and the CIN=0 fill.
    w3 = _make((3, 2, 3, 3, 3), torch.float32, seed=50)
    x3 = _make((2, 5, 5, 5), torch.float32, seed=51)

    assert tuple(flag_gems.slow_conv_dilated3d(x3, w3, [3, 3, 3]).shape) == (3, 3, 3, 3)

    # A kernel one step LARGER than the input gives the empty output (measured:
    # kernel == input yields size 1, not 0, on both sides).
    x_small = _make((2, 3, 3, 3), torch.float32, seed=57)
    w_empty = _make((2, 2, 4, 4, 4), torch.float32, seed=52)
    assert tuple(flag_gems.slow_conv_dilated3d(x_small, w_empty, [4, 4, 4]).shape) == (
        2,
        0,
        0,
        0,
    )

    xc0 = _make((0, 5, 5, 5), torch.float32, seed=53)
    wc0 = _make((3, 0, 3, 3, 3), torch.float32, seed=54)
    bias = _make((3,), torch.float32, seed=55)
    got = flag_gems.slow_conv_dilated3d(xc0, wc0, [3, 3, 3], bias=bias)
    assert tuple(got.shape) == (3, 3, 3, 3)
    expected = bias.reshape(3, 1, 1, 1).expand(3, 3, 3, 3)
    torch.testing.assert_close(got, expected, atol=0.0, rtol=0.0)

    w0 = _make((0, 2, 3, 3, 3), torch.float32, seed=56)
    assert tuple(flag_gems.slow_conv_dilated3d(x3, w0, [3, 3, 3]).shape) == (0, 3, 3, 3)


@pytest.mark.slow_conv_dilated3d
def test_accuracy_slow_conv_dilated3d_zero_spatial_output():
    # A kernel larger than the (unpadded) input yields DO == 0: native returns
    # an empty output, which the P_TOTAL <= 0 short-circuit must reproduce
    # without launching the kernel.
    x = _make((1, 2, 3, 3, 3), torch.float32, seed=13)
    w = _make((2, 2, 4, 4, 4), torch.float32, seed=14)

    # Kernel one step larger than the input -> output size 0 (measured; kernel
    # EQUAL to the input gives 1, and a NEGATIVE size is rejected outright).
    # The empty-shape contract is pinned against the CPU reference: this build's
    # CUDA reference launches with a zero-sized grid and trips "N > 0 INTERNAL
    # ASSERT FAILED ... CUDA kernel launch blocks must be positive" (measured,
    # job slow_conv_dilated3d-other-a1-090c2023), so CPU is the only side that
    # can answer here. The submitted implementation returns the empty tensor
    # without launching.
    ref_out = _native(
        *[utils.to_reference(t, upcast=True).cpu() for t in (x, w)],
        (4, 4, 4),
        None,
        1,
        0,
        1,
    )
    res_out = flag_gems.slow_conv_dilated3d(x, w, [4, 4, 4])

    assert tuple(ref_out.shape) == (1, 2, 0, 0, 0)
    assert tuple(res_out.shape) == tuple(ref_out.shape)
    assert res_out.numel() == 0


@pytest.mark.slow_conv_dilated3d
def test_accuracy_slow_conv_dilated3d_zero_out_channels():
    # COUT == 0: empty output, short-circuited.
    x = _make((1, 2, 5, 5, 5), torch.float32, seed=15)
    w = _make((0, 2, 3, 3, 3), torch.float32, seed=16)

    ref_out = _native(
        *[utils.to_reference(t, upcast=True) for t in (x, w)], (3, 3, 3), None, 1, 0, 1
    )
    res_out = flag_gems.slow_conv_dilated3d(x, w, [3, 3, 3])

    assert res_out.shape == (1, 0, 3, 3, 3)
    assert tuple(res_out.shape) == tuple(ref_out.shape)
    utils.gems_assert_close(res_out, ref_out, torch.float32)


@pytest.mark.slow_conv_dilated3d
def test_accuracy_slow_conv_dilated3d_zero_in_channels():
    # CIN == 0: the native kernels pre-fill the output with the bias (or zeros)
    # and then perform no accumulation at all, so the result is exactly that
    # fill -- verified for both the bias and the no-bias path (measured against
    # native on CPU: `out == bias.view(1, -1, 1, 1, 1)`).
    x = _make((1, 0, 5, 5, 5), torch.float32, seed=17)
    w = _make((3, 0, 3, 3, 3), torch.float32, seed=18)
    bias = _make((3,), torch.float32, seed=19)

    # Native CUDA cannot answer this case: with CIN == 0 it launches a
    # zero-sized grid and trips "N > 0 INTERNAL ASSERT FAILED ... blocks must
    # be positive" (measured, job probe2). The contract is therefore pinned
    # against the CPU reference (which DOES answer) plus the exact fill value.
    ref_x = utils.to_reference(x).cpu()
    ref_w = utils.to_reference(w).cpu()
    ref_b = utils.to_reference(bias).cpu()
    ref_out = _native(ref_x, ref_w, (3, 3, 3), ref_b, 1, 0, 1)
    res_out = flag_gems.slow_conv_dilated3d(x, w, [3, 3, 3], bias=bias)

    assert res_out.shape == (1, 3, 3, 3, 3)
    got = utils.to_cpu(res_out, ref_out).reshape(3, -1)
    expected = ref_b.reshape(3, 1).expand_as(got)
    assert torch.equal(got, expected.to(got.dtype).to(got.device))
    assert torch.equal(got.float().cpu(), ref_out.reshape(3, -1).float())

    res_none = flag_gems.slow_conv_dilated3d(x, w, [3, 3, 3])
    assert bool((res_none == 0).all())
    ref_none = _native(ref_x, ref_w, (3, 3, 3), None, 1, 0, 1)
    assert bool((ref_none == 0).all())
    assert tuple(res_none.shape) == tuple(ref_none.shape)


@pytest.mark.slow_conv_dilated3d
def test_accuracy_slow_conv_dilated3d_non_contiguous_input():
    # The kernel indexes the input with the plain contiguous offset formula, so
    # a transposed (strided) input must be materialised first. Native does the
    # same (`input.contiguous()` in NaiveDilatedConvolution.cpp), and the
    # values must match the contiguous call exactly.
    base = _make((1, 5, 5, 5, 2), torch.float32, seed=20)
    x = base.transpose(1, 4)
    assert not x.is_contiguous()
    w = _make((3, 2, 3, 3, 3), torch.float32, seed=21)

    ref_x, ref_w, _ = _refs(x, w, None, upcast=True)
    ref_out = _native(ref_x, ref_w, (3, 3, 3), None, 1, 0, 1)
    res_out = flag_gems.slow_conv_dilated3d(x, w, [3, 3, 3])
    res_contig = flag_gems.slow_conv_dilated3d(x.contiguous(), w, [3, 3, 3])

    assert res_out.shape == tuple(ref_out.shape)
    utils.gems_assert_close(res_out, ref_out, torch.float32)
    utils.gems_assert_close(res_contig, ref_out, torch.float32)
    # Same precision on both sides (see the note in the main sweep): the
    # non-contiguous path is only declared equivalent to the contiguous one.
    torch.testing.assert_close(res_out, res_contig, atol=0.0, rtol=0.0)


@pytest.mark.slow_conv_dilated3d
def test_accuracy_slow_conv_dilated3d_non_contiguous_weight():
    base = _make((3, 3, 3, 3, 2), torch.float32, seed=22)
    w = base.transpose(1, 4)
    assert not w.is_contiguous()
    x = _make((1, 2, 5, 5, 5), torch.float32, seed=23)

    ref_x, ref_w, _ = _refs(x, w, None, upcast=True)
    ref_out = _native(ref_x, ref_w, (3, 3, 3), None, 1, 0, 1)
    res_out = flag_gems.slow_conv_dilated3d(x, w, [3, 3, 3])
    res_contig = flag_gems.slow_conv_dilated3d(x, w.contiguous(), [3, 3, 3])

    assert res_out.shape == tuple(ref_out.shape)
    utils.gems_assert_close(res_out, ref_out, torch.float32)
    # Same precision on both sides (see the note in the main sweep): the
    # non-contiguous path is only declared equivalent to the contiguous one.
    torch.testing.assert_close(res_out, res_contig, atol=0.0, rtol=0.0)


@pytest.mark.slow_conv_dilated3d
def test_accuracy_slow_conv_dilated3d_non_contiguous_bias():
    # A strided bias of the RIGHT length 3 (base.t()[0] would be length 2).
    base = _make((3, 2), torch.float32, seed=24)
    bias = base.t()[0]
    assert bias.shape == (3,)
    assert not bias.is_contiguous()
    x = _make((1, 2, 5, 5, 5), torch.float32, seed=25)
    w = _make((3, 2, 3, 3, 3), torch.float32, seed=26)

    ref_x, ref_w, ref_b = _refs(x, w, bias, upcast=True)
    ref_out = _native(ref_x, ref_w, (3, 3, 3), ref_b, 1, 0, 1)
    res_out = flag_gems.slow_conv_dilated3d(x, w, [3, 3, 3], bias=bias)

    utils.gems_assert_close(res_out, ref_out, torch.float32)

    # The strided bias must produce the same result as its contiguous copy.
    res_contig = flag_gems.slow_conv_dilated3d(x, w, [3, 3, 3], bias=bias.contiguous())
    torch.testing.assert_close(res_out, res_contig, atol=0.0, rtol=0.0)


@pytest.mark.slow_conv_dilated3d
def test_accuracy_slow_conv_dilated3d_all_ones_identity():
    # An all-ones input with an all-ones weight: every interior output element
    # (all taps in range) is exactly C_in * prod(kernel_size) — a closed-form
    # check that does not depend on the reference at all.
    x = torch.ones((2, 3, 6, 6, 6), dtype=torch.float32, device=flag_gems.device)
    w = torch.ones((4, 3, 2, 3, 2), dtype=torch.float32, device=flag_gems.device)

    ref_x = utils.to_reference(x, upcast=True)
    ref_w = utils.to_reference(w, upcast=True)
    ref_out = _native(ref_x, ref_w, (2, 3, 2), None, 1, 0, (2, 1, 2))
    res_out = flag_gems.slow_conv_dilated3d(x, w, [2, 3, 2], dilation=[2, 1, 2])

    utils.gems_assert_close(res_out, ref_out, torch.float32)
    got = utils.to_cpu(res_out, ref_out)
    assert tuple(got.shape) == (2, 4, 4, 4, 4)
    # Interior position (od=2, oh=3, ow=2): taps id in {2,4}, ih in {3,4,5},
    # iw in {2,4}; all in range -> C_in * kD * kH * kW = 3*2*3*2 = 36.
    assert bool((got[:, :, 2, 3, 2] == 3 * 2 * 3 * 2).all())


@pytest.mark.slow_conv_dilated3d
def test_accuracy_slow_conv_dilated3d_fresh_allocation():
    # The output is a fresh allocation: mutating the inputs afterwards must not
    # change it, and it must not alias either input.
    x = _make((1, 2, 5, 5, 5), torch.float32, seed=27)
    w = _make((3, 2, 3, 3, 3), torch.float32, seed=28)

    ref_x, ref_w, _ = _refs(x, w, None, upcast=True)
    ref_out = _native(ref_x, ref_w, (3, 3, 3), None, 1, 0, 1)
    res_out = flag_gems.slow_conv_dilated3d(x, w, [3, 3, 3])
    snapshot = res_out.clone()

    x.fill_(99.0)
    w.fill_(99.0)
    torch.testing.assert_close(res_out, snapshot, atol=0.0, rtol=0.0)
    assert res_out.data_ptr() != x.data_ptr()
    assert res_out.data_ptr() != w.data_ptr()
    utils.gems_assert_close(res_out, ref_out, torch.float32)


@pytest.mark.slow_conv_dilated3d
@pytest.mark.slow_conv_dilated3d_out
@pytest.mark.parametrize("dtype", [torch.float32])
def test_accuracy_slow_conv_dilated3d_out_variant(dtype):
    # `slow_conv_dilated3d.out` writes into the supplied buffer and returns it
    # (identity, not a copy) -- both facts are asserted.
    x = _make((1, 2, 5, 5, 5), dtype, seed=29)
    w = _make((3, 2, 3, 3, 3), dtype, seed=30)
    bias = _make((3,), dtype, seed=31)

    # The native lane goes through TF32 by default, so it is pinned against the
    # upcast fp64 reference with TF32 off (the tests/test_conv3d.py pattern).
    # The reference buffer lives on the REFERENCE's device: under --ref=cpu
    # (CI's quick phase) the reference inputs are CPU copies while the
    # implementation's buffer is CUDA, and native .out rejects a device
    # mismatch.
    ref_x = utils.to_reference(x, upcast=True)
    ref_w = utils.to_reference(w, upcast=True)
    ref_b = utils.to_reference(bias, upcast=True)
    ref_out = torch.full((1, 3, 3, 3, 3), -7.0, dtype=dtype, device=ref_x.device)
    ref_ret = _native(
        ref_x.to(dtype),
        ref_w.to(dtype),
        (3, 3, 3),
        ref_b.to(dtype),
        1,
        0,
        1,
        out=ref_out,
    )
    assert ref_ret.data_ptr() == ref_out.data_ptr()
    assert not bool((ref_out == -7.0).any()), "reference .out buffer not written"

    out = torch.full((1, 3, 3, 3, 3), -7.0, dtype=dtype, device=flag_gems.device)
    # `flag_gems.slow_conv_dilated3d` is the BASE function object; the .out
    # overload is exported alongside it as `slow_conv_dilated3d_out`.
    ret = flag_gems.slow_conv_dilated3d_out(
        x, w, [3, 3, 3], bias, [1, 1, 1], [0, 0, 0], [1, 1, 1], out=out
    )

    assert ret.data_ptr() == out.data_ptr()
    assert ret is out
    assert not bool((out == -7.0).any()), "out buffer was not written"
    # Values: the .out result against the high-precision reference (both the
    # .out reference and the default-overload reference), and the default
    # overload against the .out buffer.
    utils.gems_assert_close(ret, ref_ret, dtype)
    utils.gems_assert_close(
        ret,
        _native(ref_x.to(dtype), ref_w.to(dtype), (3, 3, 3), ref_b.to(dtype), 1, 0, 1),
        dtype,
    )
    torch.testing.assert_close(
        ret,
        flag_gems.slow_conv_dilated3d(x, w, [3, 3, 3], bias=bias),
        atol=0.0,
        rtol=0.0,
    )


@pytest.mark.slow_conv_dilated3d
@pytest.mark.slow_conv_dilated3d_out
def test_accuracy_slow_conv_dilated3d_out_visible_through_registration():
    # Registered-path check: the aten .out call must reach the submitted
    # implementation (registered on the backend key) and return the same
    # buffer identity as the native .out (autogen CompositeExplicitAutograd on
    # this build -- so a plain device-key registration intercepts it, measured
    # via the CPU sentinel probe probe_out_dispatch_cpu.py).
    x = _make((1, 2, 5, 5, 5), torch.float32, seed=32)
    w = _make((3, 2, 3, 3, 3), torch.float32, seed=33)
    ref_x = utils.to_reference(x, upcast=True)
    ref_w = utils.to_reference(w, upcast=True)
    ref_out = _native(ref_x, ref_w, (3, 3, 3), None, 1, 0, 1)

    out = torch.full(
        (1, 3, 3, 3, 3), -7.0, dtype=torch.float32, device=flag_gems.device
    )
    ret = torch.ops.aten.slow_conv_dilated3d.out(
        x, w, [3, 3, 3], None, [1, 1, 1], [0, 0, 0], [1, 1, 1], out=out
    )
    assert ret is out
    assert not bool((out == -7.0).any()), "out buffer was not written"
    utils.gems_assert_close(out, ref_out, torch.float32)
    # The registered .out path must agree with the direct default call.
    direct = flag_gems.slow_conv_dilated3d(x, w, [3, 3, 3])
    torch.testing.assert_close(
        utils.to_cpu(out, ref_out),
        utils.to_cpu(direct, ref_out),
        atol=1e-4,
        rtol=1.3e-6,
    )


@pytest.mark.slow_conv_dilated3d
def test_accuracy_slow_conv_dilated3d_repeated_dispatch():
    # The same input dispatched repeatedly (interleaved with an unrelated aten
    # op) must be stable, and a different geometry in between must not leak
    # state into the next call.
    x = _make((1, 2, 5, 5, 5), torch.float32, seed=34)
    w = _make((3, 2, 3, 3, 3), torch.float32, seed=35)
    ref_x = utils.to_reference(x, upcast=True)
    ref_w = utils.to_reference(w, upcast=True)

    ref_a = _native(ref_x, ref_w, (3, 3, 3), None, 1, 0, 1)
    ref_b = _native(ref_x, ref_w, (3, 3, 3), None, 2, 1, 2)
    ref_a = ref_a.float()
    ref_b = ref_b.float()
    first_a = None
    for _ in range(3):
        res_a = flag_gems.slow_conv_dilated3d(x, w, [3, 3, 3])
        # Repeat stability: bit-identical across repeats of the same call.
        if first_a is None:
            first_a = res_a.clone()
        else:
            torch.testing.assert_close(res_a, first_a, atol=0.0, rtol=0.0)
        utils.gems_assert_close(res_a, ref_a, torch.float32)
        assert torch.ops.aten.dim(x) == 5
        res_b = flag_gems.slow_conv_dilated3d(
            x, w, [3, 3, 3], stride=[2, 2, 2], padding=[1, 1, 1], dilation=[2, 2, 2]
        )
        utils.gems_assert_close(res_b, ref_b, torch.float32)
        # The interleaved different geometry must not perturb the first one.
        torch.testing.assert_close(
            flag_gems.slow_conv_dilated3d(x, w, [3, 3, 3]),
            first_a,
            atol=0.0,
            rtol=0.0,
        )


@pytest.mark.slow_conv_dilated3d
@pytest.mark.parametrize(
    "case",
    [
        "ks_wrong_len",
        "stride_zero",
        "dilation_zero",
        "dilation_negative",
        "kernel_not_positive",
    ],
)
def test_accuracy_slow_conv_dilated3d_invalid_geometry(case):
    # Rejected by BOTH sides. The exception CLASS is asserted per side (never
    # identity between the two), and no message text is pinned: the reference
    # and the implementation (via torch.empty / the dispatcher's own
    # validation) raise from different validators on different torch builds.
    x = _make((1, 2, 5, 5, 5), torch.float32, seed=36)
    w = _make((3, 2, 3, 3, 3), torch.float32, seed=37)
    ref_x = utils.to_reference(x, upcast=True)
    ref_w = utils.to_reference(w, upcast=True)

    # The fragment comes from the IMPLEMENTATION's documented validation
    # (mirroring ATen's DilatedConvolutionUtils.h), never from the reference's
    # wording: CI runs on a different torch build whose validator text can
    # differ (A1).
    if case == "ks_wrong_len":
        ks, s, p, d = [3, 3], 1, 0, 1
        fragment = "kernel sizes length should be 3"
    elif case == "stride_zero":
        ks, s, p, d = [3, 3, 3], [0, 0, 0], 0, 1
        fragment = "stride should be greater than zero"
    elif case == "dilation_zero":
        ks, s, p, d = [3, 3, 3], 1, 0, [0, 0, 0]
        fragment = "dilation should be greater than zero"
    elif case == "dilation_negative":
        ks, s, p, d = [3, 3, 3], 1, 0, [-1, 1, 1]
        fragment = "dilation should be greater than zero"
    else:
        ks, s, p, d = [0, 0, 0], 1, 0, 1
        fragment = "kernel size should be greater than zero"

    # Class only for the reference (its validator lives in the torch build).
    with pytest.raises(RuntimeError):
        _native(ref_x, ref_w, ks, None, s, p, d)
    with pytest.raises(RuntimeError, match=fragment):
        flag_gems.slow_conv_dilated3d(
            x, w, ks, stride=_t(s), padding=_t(p), dilation=_t(d)
        )


@pytest.mark.slow_conv_dilated3d
def test_accuracy_slow_conv_dilated3d_output_too_small():
    # A kernel that does not fit the input under the given dilation is rejected
    # by native ("calculated output size ... is too small"); the implementation
    # rejects it too (the empty() of a negative-size output cannot succeed).
    x = _make((1, 2, 4, 4, 4), torch.float32, seed=38)
    w = _make((3, 2, 5, 5, 5), torch.float32, seed=39)
    ref_x = utils.to_reference(x, upcast=True)
    ref_w = utils.to_reference(w, upcast=True)

    # (5,5,5) is exactly input-sized and yields the (valid) empty output
    # (1, 3, 0, 0, 0) on both sides -- measured; a NEGATIVE output size needs a
    # kernel one step bigger.
    with pytest.raises(RuntimeError):
        _native(ref_x, ref_w, [6, 6, 6], None, 1, 0, 1)
    with pytest.raises(RuntimeError, match="is too small"):
        flag_gems.slow_conv_dilated3d(x, w, [6, 6, 6])


@pytest.mark.slow_conv_dilated3d
def test_accuracy_slow_conv_dilated3d_dtype_mismatch_rejected():
    # Mixed x/w dtypes are rejected on both sides -- again asserting the class
    # only, since the reference raises from the dtype-promotion layer while the
    # implementation's tl.load would raise from the device code.
    x = _make((1, 2, 5, 5, 5), torch.float32, seed=40)
    w = _make((3, 2, 3, 3, 3), torch.float64, seed=41)

    with pytest.raises(RuntimeError):
        _native(x, w, [3, 3, 3], None, 1, 0, 1)
    # The implementation reaches the kernel and tl.load fails against the
    # mismatched pointer type; WHICH class triton raises for that is a
    # device-code detail that varies across triton/torch builds, so only the
    # fact that it is raised at all is pinned here (never a class identity
    # between the two sides).
    with pytest.raises(Exception):  # noqa: B017
        flag_gems.slow_conv_dilated3d(x, w, [3, 3, 3])


@pytest.mark.slow_conv_dilated3d
def test_accuracy_slow_conv_dilated3d_weight_rank_rejected():
    x = _make((1, 2, 5, 5, 5), torch.float32, seed=42)
    w = _make((3, 2, 3, 3), torch.float32, seed=43)
    with pytest.raises(RuntimeError):
        _native(x, w, [3, 3, 3], None, 1, 0, 1)
    # A 4-D weight is rejected by the implementation's own rank check before
    # any launch. Class per side; the fragment is from the IMPLEMENTATION's
    # wording, never the reference's.
    with pytest.raises(RuntimeError, match="weight must be 5D"):
        flag_gems.slow_conv_dilated3d(x, w, [3, 3, 3])


@pytest.mark.slow_conv_dilated3d
@pytest.mark.parametrize("dtype", FLOAT_DTYPES)
def test_accuracy_slow_conv_dilated3d_single_output_element(dtype):
    # The smallest possible launch: 1 output element, exercising the masks for
    # BLOCK_P/BLOCK_CO tails (grid == (1, 1, 1)).
    x = _make((1, 1, 3, 3, 3), dtype, seed=44)
    w = _make((1, 1, 3, 3, 3), dtype, seed=45)
    bias = _make((1,), dtype, seed=46)

    ref_x, ref_w, ref_b = _refs(x, w, bias, upcast=True)
    ref_out = _native(ref_x, ref_w, (3, 3, 3), ref_b, 1, 0, 1)
    res_out = flag_gems.slow_conv_dilated3d(x, w, [3, 3, 3], bias=bias)
    assert res_out.shape == (1, 1, 1, 1, 1)
    utils.gems_assert_close(res_out, ref_out, dtype)


def _refs(x, w, bias, upcast=False):
    return (
        utils.to_reference(x, upcast=upcast),
        utils.to_reference(w, upcast=upcast),
        None if bias is None else utils.to_reference(bias, upcast=upcast),
    )
