# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import math

import pytest
import torch

import flag_gems
from flag_gems.runtime import torch_device_fn
from flag_gems.utils.random_utils import set_philox_state

from . import accuracy_utils as utils
from .conftest import TO_CPU


def make_qkv(batch, num_head, q_seq_len, kv_seq_len, head_size, dtype, device):
    dev = torch_device_fn.current_device()
    set_philox_state(1234567890, 0, dev)
    Q = torch.empty(
        batch, q_seq_len, num_head, head_size, dtype=dtype, device=device
    ).uniform_(-0.05, 0.05)
    K = torch.empty(
        batch, kv_seq_len, num_head, head_size, dtype=dtype, device=device
    ).uniform_(-0.05, 0.05)
    V = torch.empty(
        batch, kv_seq_len, num_head, head_size, dtype=dtype, device=device
    ).uniform_(-0.05, 0.05)
    return Q, K, V


def cudnn_attn_forward_native(
    Q,
    K,
    V,
    attn_bias=None,
    is_causal=False,
    dropout_p=0.0,
    softmax_scale=None,
):
    Q_bhsd = Q.permute(0, 2, 1, 3).contiguous()
    K_bhsd = K.permute(0, 2, 1, 3).contiguous()
    V_bhsd = V.permute(0, 2, 1, 3).contiguous()

    scale = softmax_scale or (1.0 / math.sqrt(Q.shape[-1]))

    results = torch.ops.aten._scaled_dot_product_cudnn_attention(
        Q_bhsd,
        K_bhsd,
        V_bhsd,
        attn_bias,
        compute_log_sumexp=True,
        dropout_p=dropout_p,
        is_causal=is_causal,
        return_debug_mask=False,
        scale=scale,
    )
    out_bhsd = results[0]
    lse_4d = results[1]
    philox_seed = results[2]
    philox_offset = results[3]

    out = out_bhsd.permute(0, 2, 1, 3).contiguous()
    lse = lse_4d.float()
    return out, lse, philox_seed, philox_offset


QM_NS = [
    (2, 4, 512, 512),
    (1, 2, 512, 1024),
    (1, 1, 64, 64),
    (4, 8, 128, 128),
    (2, 4, 128, 512),
    (1, 2, 768, 768),
]


@pytest.mark.skipif(not torch.cuda.is_available(), reason="CUDA is required")
@pytest.mark.cudnn_attention_backward
@pytest.mark.parametrize("batch, num_head, q_seq_len, kv_seq_len", QM_NS)
@pytest.mark.parametrize("head_size", [64, 128])
@pytest.mark.parametrize("is_causal", [False, True])
@pytest.mark.parametrize("has_attn_bias", [False, True])
@pytest.mark.parametrize("dtype", [torch.float16, torch.bfloat16])
def test_cudnn_attention_backward(
    batch,
    num_head,
    q_seq_len,
    kv_seq_len,
    head_size,
    is_causal,
    has_attn_bias,
    dtype,
):
    if TO_CPU:
        pytest.skip(
            "_cudnn_attention_backward is CUDA-only, " "cannot run in quick-cpu mode"
        )
    if is_causal and has_attn_bias:
        pytest.skip("causal + attn_bias combination: skip")

    scale = float(1.0 / math.sqrt(head_size))

    Q, K, V = make_qkv(
        batch,
        num_head,
        q_seq_len,
        kv_seq_len,
        head_size,
        dtype,
        flag_gems.device,
    )
    dOut = torch.randn(
        batch,
        q_seq_len,
        num_head,
        head_size,
        dtype=dtype,
        device=flag_gems.device,
    )

    attn_bias = None
    if has_attn_bias:
        attn_bias = (
            torch.randn(
                batch,
                num_head,
                q_seq_len,
                kv_seq_len,
                dtype=dtype,
                device=flag_gems.device,
            )
            * 0.1
        )

    out, lse, philox_seed, philox_offset = cudnn_attn_forward_native(
        Q,
        K,
        V,
        attn_bias=attn_bias,
        is_causal=is_causal,
        softmax_scale=scale,
    )

    Q_bhsd = Q.permute(0, 2, 1, 3).contiguous()
    K_bhsd = K.permute(0, 2, 1, 3).contiguous()
    V_bhsd = V.permute(0, 2, 1, 3).contiguous()
    out_bhsd = out.permute(0, 2, 1, 3).contiguous()
    dOut_bhsd = dOut.permute(0, 2, 1, 3).contiguous()

    ref_dOut_bhsd = utils.to_reference(dOut_bhsd)
    ref_Q_bhsd = utils.to_reference(Q_bhsd)
    ref_K_bhsd = utils.to_reference(K_bhsd)
    ref_V_bhsd = utils.to_reference(V_bhsd)
    ref_out_bhsd = utils.to_reference(out_bhsd)
    ref_lse = utils.to_reference(lse)

    (
        ref_dQ_bhsd,
        ref_dK_bhsd,
        ref_dV_bhsd,
    ) = torch.ops.aten._cudnn_attention_backward(
        ref_dOut_bhsd,
        ref_Q_bhsd,
        ref_K_bhsd,
        ref_V_bhsd,
        ref_out_bhsd,
        ref_lse,
        philox_seed,
        philox_offset,
        attn_bias,
        None,
        None,
        q_seq_len,
        kv_seq_len,
        0.0,
        is_causal,
        scale=scale,
    )
    ref_dQ = ref_dQ_bhsd.permute(0, 2, 1, 3).contiguous()
    ref_dK = ref_dK_bhsd.permute(0, 2, 1, 3).contiguous()
    ref_dV = ref_dV_bhsd.permute(0, 2, 1, 3).contiguous()

    with flag_gems.use_gems():
        (
            dQ_bhsd,
            dK_bhsd,
            dV_bhsd,
        ) = torch.ops.aten._cudnn_attention_backward(
            dOut_bhsd,
            Q_bhsd,
            K_bhsd,
            V_bhsd,
            out_bhsd,
            lse,
            philox_seed,
            philox_offset,
            attn_bias,
            None,
            None,
            q_seq_len,
            kv_seq_len,
            0.0,
            is_causal,
            scale=scale,
        )

    dQ = dQ_bhsd.permute(0, 2, 1, 3).contiguous()
    dK = dK_bhsd.permute(0, 2, 1, 3).contiguous()
    dV = dV_bhsd.permute(0, 2, 1, 3).contiguous()

    utils.gems_assert_close(dQ, ref_dQ, dtype, equal_nan=True)
    utils.gems_assert_close(dK, ref_dK, dtype, equal_nan=True)
    utils.gems_assert_close(dV, ref_dV, dtype, equal_nan=True)
