# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing permissions
# and limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch

import flag_gems

from . import accuracy_utils as utils

# can_cast takes no tensor: its whole domain is the (from_, to) dtype pair, so
# coverage is driven by the dtype grid instead of shapes. The exhaustive
# 13-dtype ATen promotion grid is cheap (pure metadata lookups, no tensor
# allocation), so it is NOT trimmed in QUICK_MODE -- the full grid runs in
# both accuracy phases. The string-spelling branch of the supplied
# implementation is exercised through the direct Python entry (the dispatched
# API rejects strings before any implementation is reached).
DTYPES13 = [
    torch.bool,
    torch.uint8,
    torch.int8,
    torch.int16,
    torch.int32,
    torch.int64,
    torch.float16,
    torch.bfloat16,
    torch.float32,
    torch.float64,
    torch.complex32,
    torch.complex64,
    torch.complex128,
]

# A pinned copy of native literals, captured in a flag_gems-free environment
# (runs/can_cast/probe/probe4_native_grid.py), independent of the live native
# reference the grid tests use.
NATIVE_TABLE_SNIPPET = {
    (torch.bool, torch.int8): True,
    (torch.int8, torch.bool): False,
    (torch.float32, torch.int32): False,
    (torch.int32, torch.float32): True,
    (torch.float64, torch.float16): True,
    (torch.complex64, torch.float32): False,
    (torch.float16, torch.complex128): True,
}

# Exotic dtype attributes, guarded by hasattr: the pinned H20 build exposes
# int1-int7/uint1-uint7/qint/quint/bits*/uint16-64 and every float8 flavour,
# but the tests stay importable on builds that lack them.
EXOTIC_DTYPES = [
    name
    for name in (
        "int1",
        "int2",
        "int3",
        "int4",
        "int5",
        "int6",
        "int7",
        "uint1",
        "uint2",
        "uint3",
        "uint4",
        "uint5",
        "uint6",
        "uint7",
        "uint16",
        "uint32",
        "uint64",
        "qint8",
        "qint32",
        "quint8",
        "quint4x2",
        "quint2x4",
        "bits1x8",
        "bits2x4",
        "bits4x2",
        "bits8",
        "bits16",
        "float8_e4m3fn",
        "float8_e5m2",
        "float8_e4m3fnuz",
        "float8_e5m2fnuz",
        "float8_e8m0fnu",
        "float4_e2m1fn_x2",
    )
    if hasattr(torch, name)
]


@pytest.mark.can_cast
@pytest.mark.parametrize("from_", DTYPES13)
@pytest.mark.parametrize("to", DTYPES13)
def test_accuracy_can_cast_grid(from_, to):
    res = flag_gems.can_cast(from_, to)
    ref = torch.can_cast(from_, to)
    assert isinstance(res, bool), f"expected python bool, got {type(res)}"
    assert res is ref, f"({from_}, {to}): got {res!r}, native {ref!r}"


@pytest.mark.can_cast
def test_accuracy_can_cast_aten_reference():
    # The same grid against the aten packet (the operator that is registered).
    for from_ in DTYPES13:
        for to in DTYPES13:
            res = flag_gems.can_cast(from_, to)
            ref = torch.ops.aten.can_cast(from_, to)
            assert res == ref, f"aten ({from_}, {to}): got {res!r}, native {ref!r}"


@pytest.mark.can_cast
@pytest.mark.parametrize(
    "dtype",
    utils.BOOL_TYPES + utils.INT_DTYPES + utils.FLOAT_DTYPES,
)
def test_accuracy_can_cast_repo_dtype_sweep(dtype):
    # The repository dtype lists drive one allowed and one rejected cast per
    # sweep dtype (to float32 and back to bool), keeping the repo-standard
    # dtype sweep meaningful for a metadata operator.
    assert flag_gems.can_cast(dtype, torch.float32) is torch.can_cast(
        dtype, torch.float32
    )
    assert flag_gems.can_cast(dtype, torch.bool) is torch.can_cast(dtype, torch.bool)


@pytest.mark.can_cast
def test_accuracy_can_cast_matches_native_table():
    for (from_, to), expected in NATIVE_TABLE_SNIPPET.items():
        res = flag_gems.can_cast(from_, to)
        assert res is expected, f"({from_}, {to}): got {res!r}, pinned {expected!r}"


def _exotic(name):
    return getattr(torch, name, None)


# Pinned exotic-dtype expectations, measured against native torch.can_cast in
# a flag_gems-free environment (runs/can_cast/probe/probe16_exotic_matrices.py
# on the pinned H20 image, torch 2.8.0a0+nv25.05; identical on 2.11.0+cu129).
# They follow ATen's c10::canCast predicate rather than the promotion-rank
# model of the core grid: int1-int7/uint1-uint7/qint/quint/bits belong to NO
# ATen category, so float32 -> int1 casts (True) while float32 -> int32 does
# not (False); uint16/32/64 ARE in ATen's integral set (float32 -> uint16 is
# False); float8/float4 are floating (float8 -> int32 is False, float8 ->
# uint2 is True because uint2 is outside the integral set). Entries are
# guarded so the module stays importable on builds lacking a dtype.
_EXOTIC_PAIRS = {
    ("int1", "int32"): True,
    ("int32", "int1"): True,
    ("int7", "int1"): True,
    ("float32", "int1"): True,
    ("int1", "float32"): True,
    ("int1", "bool"): False,
    ("bool", "uint7"): True,
    ("uint3", "float32"): True,
    ("uint16", "int32"): True,
    ("int32", "uint16"): True,
    ("float32", "uint16"): False,
    ("uint16", "float32"): True,
    ("float32", "bits8"): True,
    ("bits8", "float32"): True,
    ("qint8", "float32"): True,
    ("float32", "qint8"): True,
    ("complex64", "int1"): False,
    ("complex128", "bits16"): False,
    ("float8_e4m3fn", "int32"): False,
    ("int32", "float8_e4m3fn"): True,
    ("float8_e5m2", "uint2"): True,
    ("float8_e5m2", "uint16"): False,
    ("uint16", "float8_e5m2"): True,
    ("float4_e2m1fn_x2", "int64"): False,
    ("float8_e8m0fnu", "complex128"): True,
}
EXOTIC_NATIVE_PINNED = {
    (_exotic(a), _exotic(b)): expected
    for (a, b), expected in _EXOTIC_PAIRS.items()
    if _exotic(a) is not None and _exotic(b) is not None
}


@pytest.mark.can_cast
@pytest.mark.parametrize(
    "from_,to,expected",
    [
        (from_, to, expected)
        for (from_, to), expected in sorted(
            EXOTIC_NATIVE_PINNED.items(), key=lambda kv: (str(kv[0][0]), str(kv[0][1]))
        )
    ],
)
def test_accuracy_can_cast_exotic_pinned(from_, to, expected):
    # Direct-entry behaviour for dtype pairs outside the 13-dtype table: the
    # native c10::canCast predicate, not a KeyError and not a blanket False.
    res = flag_gems.can_cast(from_, to)
    assert res is expected, f"({from_}, {to}): got {res!r}, pinned native {expected!r}"


@pytest.mark.can_cast
@pytest.mark.parametrize("name", EXOTIC_DTYPES)
def test_accuracy_can_cast_exotic_family_rules(name):
    # Family-level invariants of ATen's three-prohibition rule for every
    # exotic dtype the build exposes (all values pinned from probe16).
    dtype = getattr(torch, name)
    # bool is its own category: nothing but bool casts into it.
    assert flag_gems.can_cast(dtype, torch.bool) is False
    assert flag_gems.can_cast(torch.bool, dtype) is True
    # No exotic dtype is complex, so complex -> exotic is always rejected.
    assert flag_gems.can_cast(torch.complex64, dtype) is False
    if name.startswith(("float8", "float4")):
        # ATen floating: rejected toward ATen-integral, allowed elsewhere.
        assert flag_gems.can_cast(dtype, torch.int32) is False
        assert flag_gems.can_cast(dtype, torch.float32) is True
        assert flag_gems.can_cast(dtype, torch.float64) is True
    elif name in ("uint16", "uint32", "uint64"):
        # ATen integral: reachable from anything non-bool/non-complex, but
        # floating sources are rejected toward it.
        assert flag_gems.can_cast(dtype, torch.float32) is True
        assert flag_gems.can_cast(torch.float32, dtype) is False
        assert flag_gems.can_cast(torch.int32, dtype) is True
    else:
        # int1-7/uint1-7/qint/quint/bits are in no ATen set: only the bool and
        # complex prohibitions apply, everything else casts both ways.
        assert flag_gems.can_cast(dtype, torch.int32) is True
        assert flag_gems.can_cast(torch.int32, dtype) is True
        assert flag_gems.can_cast(dtype, torch.float32) is True
        assert flag_gems.can_cast(torch.float32, dtype) is True


@pytest.mark.can_cast
def test_accuracy_can_cast_exotic_dispatched_path():
    # The reported failure mode: exotic dtypes through the dispatched entry
    # points must return the pinned native booleans, not raise KeyError.
    # (After `import flag_gems` the dispatched calls route into the submitted
    # implementation, so the pinned literals are the meaningful reference.)
    for (from_, to), expected in sorted(
        EXOTIC_NATIVE_PINNED.items(), key=lambda kv: (str(kv[0][0]), str(kv[0][1]))
    ):
        assert (
            torch.can_cast(from_, to) is expected
        ), f"torch.can_cast({from_}, {to}) diverged from pinned native"
        assert torch.ops.aten.can_cast(from_, to) is expected
        assert flag_gems.can_cast(from_, to) is expected


@pytest.mark.can_cast
@pytest.mark.parametrize(
    "from_,to,expected",
    [
        ("float16", "float32", True),
        ("torch.float16", "torch.float32", True),
        ("float32", "int32", False),
        ("bool", "float16", True),
        ("complex64", "float32", False),
        ("float8_e4m3fn", "float16", True),
    ],
)
def test_accuracy_can_cast_string_spellings(from_, to, expected):
    # The supplied implementation accepts string spellings defensively
    # (same-kind pairs only: its table builds (dtype, dtype) and
    # (str, str) keys, so a mixed dtype/str pair is a KeyError). Native
    # torch.can_cast rejects strings outright, so expected values are pinned
    # here rather than taken from the reference.
    res = flag_gems.can_cast(from_, to)
    assert res is expected, f"({from_!r}, {to!r}): got {res!r}, expected {expected!r}"


@pytest.mark.can_cast
@pytest.mark.parametrize(
    "from_,to",
    [
        (torch.float16, "float32"),
        ("float16", torch.float32),
    ],
)
def test_accuracy_can_cast_mixed_kind_pairs_raise(from_, to):
    # Disclosed behaviour of the supplied table: string and torch.dtype keys
    # are not interchangeable within one pair. Pinned so a future change to
    # that contract is visible rather than silent.
    with pytest.raises(KeyError):
        flag_gems.can_cast(from_, to)


@pytest.mark.can_cast
def test_accuracy_can_cast_float8():
    f8 = torch.float8_e4m3fn
    res = flag_gems.can_cast(f8, torch.float16)
    ref = torch.can_cast(f8, torch.float16)
    assert res is ref is True
    res = flag_gems.can_cast(torch.float16, f8)
    ref = torch.can_cast(torch.float16, f8)
    assert res is ref is True
    res = flag_gems.can_cast(f8, torch.bool)
    ref = torch.can_cast(f8, torch.bool)
    assert res is ref is False


@pytest.mark.can_cast
def test_accuracy_can_cast_kwargs_call():
    assert flag_gems.can_cast(from_=torch.int8, to=torch.int64) is True
    assert flag_gems.can_cast(from_=torch.float64, to=torch.int64) is False


@pytest.mark.can_cast
def test_accuracy_can_cast_return_type():
    res = flag_gems.can_cast(torch.float32, torch.float64)
    assert type(res) is bool
    res = flag_gems.can_cast(torch.int8, torch.bool)
    assert type(res) is bool and res is False


@pytest.mark.can_cast
def test_accuracy_can_cast_dispatched_path():
    # The registration is only meaningful if the dispatched calls route into
    # the submitted implementation. Registering the impl through the repo's
    # registrar pattern (device key + the CompositeImplicitAutograd key ATen
    # itself uses) and then calling torch.can_cast / torch.ops.aten.can_cast
    # must execute it: the sentinel counting wrapper proves the routing.
    from torch.library import Library

    lib = Library("aten", "IMPL")
    hits = []

    def sentinel(from_, to):
        hits.append((from_, to))
        return flag_gems.can_cast(from_, to)

    lib.impl("can_cast", sentinel, "CUDA")
    lib.impl("can_cast", sentinel, "CompositeImplicitAutograd")
    try:
        assert torch.can_cast(torch.float32, torch.float64) is True
        assert torch.ops.aten.can_cast(torch.int8, torch.bool) is False
        assert len(hits) == 2, f"dispatched calls did not reach the impl: {hits}"
        assert hits == [
            (torch.float32, torch.float64),
            (torch.int8, torch.bool),
        ]
    finally:
        lib._destroy()
    # After destroying the sentinel library the dispatched path is native
    # again and still consistent with the submitted implementation.
    assert torch.can_cast(torch.int8, torch.bool) is False
    assert flag_gems.can_cast(torch.int8, torch.bool) is False


@pytest.mark.can_cast
def test_accuracy_can_cast_repeated_dispatch():
    # Repeated routed calls must be stable (no recursion, no state drift):
    # the implementation is a pure lookup over an immutable table.
    for _ in range(5):
        assert torch.can_cast(torch.float16, torch.float32) is True
        assert torch.can_cast(torch.float32, torch.float16) is True
        assert torch.can_cast(torch.int32, torch.bool) is False
        assert flag_gems.can_cast(torch.int32, torch.bool) is False
        assert torch.ops.aten.can_cast(torch.bool, torch.complex64) is True
