# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing permissions
# and limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch
from _pytest.mark.structures import Mark, MarkDecorator

import flag_gems

from . import accuracy_utils as utils
from . import conftest as cfg

# ``_empty_per_channel_affine_quantized`` starts with an underscore, and
# ``pytest.mark`` refuses to generate a marker via attribute access for such
# names. Register it directly on the MarkGenerator so
# ``@pytest.mark._empty_per_channel_affine_quantized`` and ``-m <name>`` work.
setattr(
    pytest.mark,
    "_empty_per_channel_affine_quantized",
    MarkDecorator(
        Mark("_empty_per_channel_affine_quantized", (), {}, _ispytest=True),
        _ispytest=True,
    ),
)

device = flag_gems.device

# The factory is a quantized allocator: the data buffer is uninitialized, so
# the contract under test is the quantizer metadata (qscheme, axis, the scales
# and zero_points storage) and the tensor geometry, never element values.
#
# ``quint4x2``/``quint2x4`` allocate fine but this build has no CUDA
# ``int_repr`` kernel for them (``int_repr_quantized_cuda`` is only defined
# for QUInt8/QInt8/QInt32), so those two are compared without int_repr.
QTYPES = [torch.quint8, torch.qint8, torch.qint32, torch.quint4x2, torch.quint2x4]
PACKED_QTYPES = (torch.quint4x2, torch.quint2x4)

QP_LEN = 8
QP_SHAPES = [(4, 8), (2, 3, 4), (8,), (1, 8)]
if cfg.QUICK_MODE:
    QP_SHAPES = [(4, 8)]


def _make_qparams(length, dtype=torch.quint8, on_cpu=False):
    # Deterministic, all-positive scales with a matching-length integral
    # zero_point vector: the ``per_channel_affine`` (integral zero points)
    # flavour, distinct from ``per_channel_affine_float_qparams``.
    dev = "cpu" if on_cpu else device
    scales = (torch.arange(length, dtype=torch.float32, device=dev) + 1.0) / 4.0
    zero_points = torch.arange(length, dtype=torch.int64, device=dev)
    return scales, zero_points


def _meta(t):
    """Harvest every output property that an uninitialized factory still fixes."""
    scales = t.q_per_channel_scales()
    zero_points = t.q_per_channel_zero_points()
    meta = {
        "shape": tuple(t.shape),
        "dtype": t.dtype,
        "device_type": t.device.type,
        "qscheme": t.qscheme(),
        "axis": t.q_per_channel_axis(),
        "scales": scales.to("cpu"),
        "scales_dtype": scales.dtype,
        "zero_points": zero_points.to("cpu"),
        "zero_points_dtype": zero_points.dtype,
        "stride": tuple(t.stride()),
        "numel": t.numel(),
        "storage_bytes": t.untyped_storage().nbytes(),
        "is_quantized": t.is_quantized,
        "is_leaf": t.is_leaf,
        "requires_grad": t.requires_grad,
    }
    if t.dtype not in PACKED_QTYPES:
        meta["int_repr_dtype"] = t.int_repr().dtype
        meta["int_repr_shape"] = tuple(t.int_repr().shape)
        meta["int_repr_device_type"] = t.int_repr().device.type
        dequantized = t.dequantize()
        meta["dequantized_dtype"] = dequantized.dtype
        meta["dequantized_shape"] = tuple(dequantized.shape)
    return meta


def _assert_same_meta(res, ref):
    res_meta = _meta(res)
    ref_meta = _meta(ref)
    assert set(res_meta) == set(
        ref_meta
    ), f"metadata key mismatch: {sorted(set(res_meta) ^ set(ref_meta))}"
    for key in sorted(ref_meta):
        got, want = res_meta[key], ref_meta[key]
        if isinstance(want, torch.Tensor):
            assert got.dtype == want.dtype, f"{key}: dtype {got.dtype} != {want.dtype}"
            assert torch.equal(got, want), f"{key}: {got.tolist()} != {want.tolist()}"
        else:
            assert got == want, f"{key}: {got!r} != {want!r}"


def _call(size, *, scales, zero_points, axis, dtype, memory_format=None):
    kwargs = {}
    if memory_format is not None:
        kwargs["memory_format"] = memory_format
    return flag_gems._empty_per_channel_affine_quantized(
        size,
        scales=scales,
        zero_points=zero_points,
        axis=axis,
        dtype=dtype,
        device=flag_gems.device,
        **kwargs,
    )


def _reference(size, *, scales, zero_points, axis, dtype, memory_format=None):
    expected_dev = "cpu" if cfg.TO_CPU else device
    kwargs = {}
    if memory_format is not None:
        kwargs["memory_format"] = memory_format
    return torch.ops.aten._empty_per_channel_affine_quantized(
        size,
        scales=utils.to_reference(scales),
        zero_points=utils.to_reference(zero_points),
        axis=axis,
        dtype=dtype,
        device=expected_dev,
        **kwargs,
    )


@pytest.mark._empty_per_channel_affine_quantized
@pytest.mark.parametrize("dtype", QTYPES)
@pytest.mark.parametrize("shape", QP_SHAPES)
@pytest.mark.parametrize("axis", [0, 1, -1])
def test_accuracy__empty_per_channel_affine_quantized_metadata(shape, dtype, axis):
    # Main sweep: dtype class x rank x axis (positive, trailing, negative).
    # The quantizer metadata must match the reference exactly; element values
    # are deliberately not compared (uninitialized data on both sides).
    scales, zero_points = _make_qparams(shape[axis % len(shape)])
    res = _call(
        list(shape), scales=scales, zero_points=zero_points, axis=axis, dtype=dtype
    )
    ref = _reference(
        list(shape), scales=scales, zero_points=zero_points, axis=axis, dtype=dtype
    )

    assert res.device.type == ref.device.type
    _assert_same_meta(res, ref)
    assert res.qscheme() == torch.per_channel_affine
    assert res.q_per_channel_axis() == axis


@pytest.mark._empty_per_channel_affine_quantized
@pytest.mark.parametrize("axis", [0, 1, -1, -2, 2, 5, -3])
def test_accuracy__empty_per_channel_affine_quantized_axis_values(axis):
    # Native does not validate ``axis``: any int is stored verbatim and read
    # back verbatim, including values outside ``[-ndim, ndim)``. Pinned so the
    # delegated path keeps the same non-validating contract.
    scales, zero_points = _make_qparams(QP_LEN)
    res = _call(
        [4, 8], scales=scales, zero_points=zero_points, axis=axis, dtype=torch.quint8
    )
    ref = _reference(
        [4, 8], scales=scales, zero_points=zero_points, axis=axis, dtype=torch.quint8
    )

    assert res.q_per_channel_axis() == axis
    assert ref.q_per_channel_axis() == axis
    _assert_same_meta(res, ref)


@pytest.mark._empty_per_channel_affine_quantized
@pytest.mark.parametrize("length", [0, 1, 2, 3, QP_LEN])
def test_accuracy__empty_per_channel_affine_quantized_qparam_length(length):
    # Native does not cross-check the qparam length against the size of the
    # selected dimension either: a mismatched length is stored as given.
    scales, zero_points = _make_qparams(length)
    res = _call(
        [4, 8], scales=scales, zero_points=zero_points, axis=1, dtype=torch.quint8
    )
    ref = _reference(
        [4, 8], scales=scales, zero_points=zero_points, axis=1, dtype=torch.quint8
    )

    assert res.q_per_channel_scales().shape == torch.Size([length])
    _assert_same_meta(res, ref)


@pytest.mark._empty_per_channel_affine_quantized
@pytest.mark.parametrize(
    "scales_dtype,zp_dtype,expected_scheme",
    [
        (torch.float64, torch.int64, torch.per_channel_affine),
        (torch.float32, torch.int64, torch.per_channel_affine),
        (torch.float16, torch.int64, torch.per_channel_affine),
        # Float zero points select the float-qparams flavour.
        (torch.float32, torch.float32, torch.per_channel_affine_float_qparams),
        (torch.float64, torch.float32, torch.per_channel_affine_float_qparams),
    ],
)
def test_accuracy__empty_per_channel_affine_quantized_qparam_dtypes(
    scales_dtype, zp_dtype, expected_scheme
):
    # The scale/zero_point dtype combination is what decides the stored
    # qscheme and the dtype the qparams are coerced to. These rules are
    # native (the implementation delegates), so they must survive verbatim.
    scales = (torch.arange(QP_LEN, dtype=torch.float32, device=device) + 1.0).to(
        scales_dtype
    )
    zero_points = torch.arange(QP_LEN, device=device).to(zp_dtype)

    res = _call(
        [4, 8], scales=scales, zero_points=zero_points, axis=1, dtype=torch.quint8
    )
    ref = _reference(
        [4, 8], scales=scales, zero_points=zero_points, axis=1, dtype=torch.quint8
    )

    assert res.qscheme() == expected_scheme
    assert ref.qscheme() == expected_scheme
    _assert_same_meta(res, ref)


@pytest.mark._empty_per_channel_affine_quantized
@pytest.mark.parametrize("shape", [(0,), (0, 8), (4, 0), (1,), (1, 1)])
def test_accuracy__empty_per_channel_affine_quantized_empty_and_small(shape):
    # Zero-sized outputs carry no backing page (nbytes == 0, data_ptr == 0);
    # size-1 outputs still allocate. Both must keep the metadata contract.
    scales, zero_points = _make_qparams(QP_LEN)
    res = _call(
        shape, scales=scales, zero_points=zero_points, axis=0, dtype=torch.quint8
    )
    ref = _reference(
        shape, scales=scales, zero_points=zero_points, axis=0, dtype=torch.quint8
    )

    if res.numel() == 0:
        assert res.untyped_storage().nbytes() == 0
        assert ref.untyped_storage().nbytes() == 0
    _assert_same_meta(res, ref)


@pytest.mark._empty_per_channel_affine_quantized
def test_accuracy__empty_per_channel_affine_quantized_zero_dim():
    scales, zero_points = _make_qparams(QP_LEN)
    res = _call([], scales=scales, zero_points=zero_points, axis=0, dtype=torch.quint8)
    ref = _reference(
        [], scales=scales, zero_points=zero_points, axis=0, dtype=torch.quint8
    )

    assert res.shape == ref.shape == torch.Size([])
    assert res.numel() == 1
    _assert_same_meta(res, ref)


@pytest.mark._empty_per_channel_affine_quantized
def test_accuracy__empty_per_channel_affine_quantized_memory_format():
    # ``contiguous_format`` (the schema default) is accepted; the unsupported
    # formats raise, and both behaviours must match the reference.
    scales, zero_points = _make_qparams(QP_LEN)
    res = _call(
        [4, 8],
        scales=scales,
        zero_points=zero_points,
        axis=1,
        dtype=torch.quint8,
        memory_format=torch.contiguous_format,
    )
    ref = _reference(
        [4, 8],
        scales=scales,
        zero_points=zero_points,
        axis=1,
        dtype=torch.quint8,
        memory_format=torch.contiguous_format,
    )
    _assert_same_meta(res, ref)

    # The string spelling of the enum is accepted by the implementation's
    # normalization layer and must land on the same layout.
    as_string = flag_gems._empty_per_channel_affine_quantized(
        [4, 8],
        scales=scales,
        zero_points=zero_points,
        axis=1,
        dtype=torch.quint8,
        device=flag_gems.device,
        memory_format="contiguous_format",
    )
    assert as_string.stride() == res.stride()

    for unsupported in (torch.preserve_format, torch.channels_last):
        with pytest.raises(RuntimeError):
            _call(
                [4, 8],
                scales=scales,
                zero_points=zero_points,
                axis=1,
                dtype=torch.quint8,
                memory_format=unsupported,
            )


@pytest.mark._empty_per_channel_affine_quantized
def test_accuracy__empty_per_channel_affine_quantized_device_resolution():
    # Native takes the output device from the ``device`` argument only -- the
    # qparam tensors do not select it -- and then moves the qparams onto that
    # device. Both halves of that rule are pinned here.
    scales, zero_points = _make_qparams(QP_LEN)
    with_device = _call(
        [4, 8], scales=scales, zero_points=zero_points, axis=1, dtype=torch.quint8
    )
    assert with_device.device.type == flag_gems.device
    assert with_device.q_per_channel_scales().device.type == flag_gems.device
    assert with_device.q_per_channel_zero_points().device.type == flag_gems.device

    # Qparams on the host with an explicit device still produce a device
    # tensor, with the qparams carried across.
    host_scales, host_zero_points = _make_qparams(QP_LEN, on_cpu=True)
    moved = flag_gems._empty_per_channel_affine_quantized(
        [4, 8],
        scales=host_scales,
        zero_points=host_zero_points,
        axis=1,
        dtype=torch.quint8,
        device=flag_gems.device,
    )
    assert moved.device.type == flag_gems.device
    assert moved.q_per_channel_scales().device.type == flag_gems.device
    assert torch.equal(moved.q_per_channel_scales().to("cpu"), host_scales)
    _assert_same_meta(moved, with_device)

    # No device argument: the factory falls back to the default device rather
    # than following the qparams, which is what the reference does too.
    default_dev = flag_gems._empty_per_channel_affine_quantized(
        [4, 8], scales=scales, zero_points=zero_points, axis=1, dtype=torch.quint8
    )
    ref_default_dev = torch.ops.aten._empty_per_channel_affine_quantized(
        [4, 8],
        scales=utils.to_reference(scales),
        zero_points=utils.to_reference(zero_points),
        axis=1,
        dtype=torch.quint8,
    )
    assert default_dev.device.type == ref_default_dev.device.type
    assert default_dev.device.type == "cpu"


@pytest.mark._empty_per_channel_affine_quantized
def test_accuracy__empty_per_channel_affine_quantized_unsupported_dtype():
    # A non-quantized dtype has no kernel for the CUDA backend on this build.
    # The registrar necessarily also installs the implementation on the plain
    # device key, and that path must reproduce the native rejection instead of
    # re-entering itself (which would surface as a RecursionError).
    scales, zero_points = _make_qparams(QP_LEN)
    for dtype in (torch.float32, torch.float16, torch.int32, torch.bool, None):
        with pytest.raises(NotImplementedError) as gems_exc:
            flag_gems._empty_per_channel_affine_quantized(
                [4, 8],
                scales=scales,
                zero_points=zero_points,
                axis=1,
                dtype=dtype,
                device=flag_gems.device,
            )
        assert "RecursionError" not in type(gems_exc.value).__name__

        ref_scales = utils.to_reference(scales)
        ref_zero_points = utils.to_reference(zero_points)
        expected_dev = "cpu" if cfg.TO_CPU else device
        with pytest.raises(NotImplementedError):
            torch.ops.aten._empty_per_channel_affine_quantized(
                [4, 8],
                scales=ref_scales,
                zero_points=ref_zero_points,
                axis=1,
                dtype=dtype,
                device=expected_dev,
            )


@pytest.mark._empty_per_channel_affine_quantized
def test_accuracy__empty_per_channel_affine_quantized_uninitialized_storage():
    # The native factory returns *uninitialized* storage. This implementation
    # must therefore not write the buffer either: a zero-filling kernel would
    # silently change what the tensor holds, since the reference never
    # promises zeroed data. Compare raw storage bytes against a plain
    # allocation taken from the same allocator state: equality means no extra
    # device write happened. (When the allocator hands out fresh pages both
    # sides read as zeros, so the assertion holds in either allocator state.)
    scales, zero_points = _make_qparams(QP_LEN)
    size = [64]
    nbytes = 64
    filler = 0xAB

    def _recycle():
        junk = torch.full([nbytes], filler, dtype=torch.uint8, device=flag_gems.device)
        assert int(junk[0].item()) == filler
        del junk

    def _raw(t):
        storage = t.untyped_storage()
        total = storage.nbytes()
        assert total > 0
        view = torch.empty(0, dtype=torch.uint8, device=t.device).set_(storage)
        return torch.as_strided(view, (total,), (1,), 0).clone()

    _recycle()
    res = _call(
        size, scales=scales, zero_points=zero_points, axis=0, dtype=torch.quint8
    )
    res_bytes = _raw(res)
    del res

    _recycle()
    control = torch.empty([nbytes], dtype=torch.uint8, device=flag_gems.device)
    control_bytes = _raw(control)
    del control

    _recycle()
    ref = _reference(
        size, scales=scales, zero_points=zero_points, axis=0, dtype=torch.quint8
    )
    ref_bytes = _raw(ref)
    del ref

    assert torch.equal(res_bytes, control_bytes), (
        f"implementation wrote into the storage it returned: "
        f"{int((res_bytes != control_bytes).sum())} differing bytes"
    )
    assert torch.equal(
        ref_bytes, control_bytes
    ), "reference wrote into the storage it returned"


@pytest.mark._empty_per_channel_affine_quantized
def test_accuracy__empty_per_channel_affine_quantized_dispatched_path():
    # The operator is a factory, so ATen's dispatch table for it has no plain
    # device key at all: the deleted-entry probe showed a sentinel installed on
    # the device key is never selected, while the Autograd key is. The
    # registration must therefore carry the Autograd key, and a dispatched
    # call (torch.ops.aten.<op> / torch._empty_per_channel_affine_quantized)
    # must actually execute the submitted implementation.
    from torch.library import Library

    config_entries = [
        entry
        for entry in flag_gems._FULL_CONFIG
        if entry and entry[0] == ("_empty_per_channel_affine_quantized")
    ]
    assert config_entries, "no _FULL_CONFIG entry for the operator"
    entry = config_entries[0]
    extra_keys = tuple(entry[3]) if len(entry) > 3 else ()
    autograd_key = torch._C.DispatchKey.Autograd.name
    assert (
        autograd_key in extra_keys
    ), f"the dispatched path needs the {autograd_key} key, got {extra_keys!r}"

    lib = Library("aten", "IMPL")
    hits = []

    def sentinel(
        size,
        *,
        scales,
        zero_points,
        axis,
        dtype=None,
        layout=None,
        device=None,
        pin_memory=None,
        memory_format=None,
    ):
        hits.append(axis)
        return flag_gems._empty_per_channel_affine_quantized(
            size,
            scales=scales,
            zero_points=zero_points,
            axis=axis,
            dtype=dtype,
            layout=layout,
            device=device,
            pin_memory=pin_memory,
            memory_format=memory_format,
        )

    scales, zero_points = _make_qparams(QP_LEN)
    lib.impl("_empty_per_channel_affine_quantized", sentinel, autograd_key)
    try:
        dispatched = torch.ops.aten._empty_per_channel_affine_quantized(
            [4, 8],
            scales=scales,
            zero_points=zero_points,
            axis=1,
            dtype=torch.quint8,
            device=flag_gems.device,
        )
        assert hits == [1], f"dispatched call did not reach the impl: {hits}"
        assert dispatched.shape == torch.Size([4, 8])
        assert dispatched.q_per_channel_axis() == 1
        assert dispatched.qscheme() == torch.per_channel_affine

        # The python-level factory binding is the same entry point.
        via_torch = torch._empty_per_channel_affine_quantized(
            [4, 8],
            scales=scales,
            zero_points=zero_points,
            axis=1,
            dtype=torch.quint8,
            device=flag_gems.device,
        )
        assert hits == [1, 1], f"torch binding did not reach the impl: {hits}"
        assert via_torch.shape == torch.Size([4, 8])
    finally:
        lib._destroy()

    # After removing the sentinel the dispatched path is native again and
    # still consistent with the submitted implementation.
    after = torch.ops.aten._empty_per_channel_affine_quantized(
        [4, 8],
        scales=scales,
        zero_points=zero_points,
        axis=1,
        dtype=torch.quint8,
        device=flag_gems.device,
    )
    assert after.q_per_channel_axis() == 1
    assert after.qscheme() == torch.per_channel_affine


@pytest.mark._empty_per_channel_affine_quantized
def test_accuracy__empty_per_channel_affine_quantized_out_overload():
    # ``.out`` is a CompositeExplicitAutograd kernel whose shape/buffer checks
    # live in the composite body; the implementation does not override it, so
    # it must keep working while the base overload is registered. Verified
    # against the native behaviour: the passed buffer is resized/rewritten and
    # returned by identity.
    scales, zero_points = _make_qparams(QP_LEN)
    out_buffer = _call(
        [4, 8], scales=scales, zero_points=zero_points, axis=1, dtype=torch.quint8
    )
    returned = torch.ops.aten._empty_per_channel_affine_quantized.out(
        [4, 8], scales=scales, zero_points=zero_points, axis=1, out=out_buffer
    )
    assert returned is out_buffer
    assert returned.shape == torch.Size([4, 8])
    assert returned.q_per_channel_axis() == 1
    assert returned.qscheme() == torch.per_channel_affine
    assert returned.q_per_channel_scales().dtype == torch.float64


@pytest.mark._empty_per_channel_affine_quantized
def test_accuracy__empty_per_channel_affine_quantized_dispatch_stability():
    # Repeated calls (plus an unrelated aten dispatch in between) must not
    # recurse, drift or leak state: the re-entrancy marker is per-thread and
    # must be released by the finally block on every path.
    scales, zero_points = _make_qparams(QP_LEN)
    for _ in range(3):
        res = _call(
            [4, 8], scales=scales, zero_points=zero_points, axis=1, dtype=torch.quint8
        )
        assert res.q_per_channel_axis() == 1
        assert torch.ops.aten.dim(torch.randn(2, device=flag_gems.device)) == 1
    # Interleaving a failing unsupported-dtype call must not leave the marker
    # set: a following valid call still has to work.
    for _ in range(2):
        with pytest.raises(NotImplementedError):
            flag_gems._empty_per_channel_affine_quantized(
                [4, 8],
                scales=scales,
                zero_points=zero_points,
                axis=1,
                dtype=torch.float32,
                device=flag_gems.device,
            )
        ok = _call(
            [4, 8], scales=scales, zero_points=zero_points, axis=1, dtype=torch.quint8
        )
        assert ok.q_per_channel_axis() == 1
        assert ok.qscheme() == torch.per_channel_affine
