# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch
from _pytest.mark.structures import Mark, MarkDecorator

import flag_gems

from . import accuracy_utils as utils
from .conftest import QUICK_MODE

# ``_dimI`` starts with an underscore, and ``pytest.mark`` refuses to generate
# a marker via attribute access for such names. Register it directly on the
# MarkGenerator so ``@pytest.mark._dimI`` and ``-m _dimI`` both work.
setattr(
    pytest.mark,
    "_dimI",
    MarkDecorator(Mark("_dimI", (), {}, _ispytest=True), _ispytest=True),
)

# ATen registers ``aten::_dimI`` only for the Meta, SparseCPU and SparseCUDA
# backends; dense tensors and the compressed sparse layouts hit no kernel and
# raise NotImplementedError natively. The dense CUDA and sparse COO keys are
# registered by FlagGems, so both the positive (COO) and the negative
# (strided/CSR) contracts are pinned here against native reference behaviour.
COO_SHAPES = [(2, 3), (4, 5, 6)]
if QUICK_MODE:
    COO_SHAPES = [(2, 3)]


def _make_coo(nnd, nnz, size, seed=0):
    gen = torch.Generator().manual_seed(seed)
    numel = 1
    for s in size[:nnd]:
        numel *= s
    flat = torch.randperm(numel, generator=gen)[:nnz]
    indices = torch.empty((nnd, nnz), dtype=torch.int64)
    for d in reversed(range(nnd)):
        indices[d] = flat % size[d]
        flat = flat // size[d]
    # Deliberately unsorted: uncoalesced COO must return the same metadata.
    values = torch.randn(nnz, generator=gen)
    return torch.sparse_coo_tensor(indices, values, size)


def _make_coo_hybrid(nnd, nnz, size, seed=0):
    # COO requires sparse_dim + dense_dim == dim(), so a rank-3 tensor with two
    # sparse dimensions carries one trailing dense value dimension.
    gen = torch.Generator().manual_seed(seed)
    numel = 1
    for s in size[:nnd]:
        numel *= s
    flat = torch.randperm(numel, generator=gen)[:nnz]
    indices = torch.empty((nnd, nnz), dtype=torch.int64)
    for d in reversed(range(nnd)):
        indices[d] = flat % size[d]
        flat = flat // size[d]
    values = torch.randn((nnz,) + tuple(size[nnd:]), generator=gen)
    return torch.sparse_coo_tensor(indices, values, size)


def _to_device(t, device):
    return t.to(device)


@pytest.mark._dimI
@pytest.mark.parametrize("shape", COO_SHAPES)
def test_accuracy__dimI_sparse_coo(shape):
    # Plain 2-D COO: sparse_dim equals the leading index-matrix dimension.
    # The rank-3 case is a hybrid (2 sparse dims + 1 dense value dim).
    nnd = 2
    if len(shape) > 2:
        sparse = _make_coo_hybrid(nnd, 3, shape, seed=2)
    else:
        sparse = _make_coo(nnd, 3, shape, seed=1)
    sparse = _to_device(sparse, flag_gems.device)
    ref_sparse = utils.to_reference(sparse)

    ref_out = torch.ops.aten._dimI(ref_sparse)
    res_out = flag_gems._dimI(sparse)

    assert isinstance(res_out, int)
    assert res_out == ref_out
    assert res_out == 2


@pytest.mark._dimI
def test_accuracy__dimI_sparse_coo_hybrid():
    # Hybrid COO (one sparse dim + dense trailing value dims) returns 1.
    sparse = torch.sparse_coo_tensor(torch.tensor([[0, 1]]), torch.randn(2, 3), (2, 3))
    sparse = _to_device(sparse, flag_gems.device)
    ref_sparse = utils.to_reference(sparse)

    ref_out = torch.ops.aten._dimI(ref_sparse)
    res_out = flag_gems._dimI(sparse)

    assert res_out == ref_out
    assert res_out == 1


@pytest.mark._dimI
def test_accuracy__dimI_sparse_coo_1d():
    # 1-sparse-dim COO: a single index row, so the count is 1.
    sparse = torch.sparse_coo_tensor(torch.tensor([[0, 1]]), torch.randn(2), (2,))
    sparse = _to_device(sparse, flag_gems.device)
    ref_sparse = utils.to_reference(sparse)

    ref_out = torch.ops.aten._dimI(ref_sparse)
    res_out = flag_gems._dimI(sparse)

    assert res_out == ref_out
    assert res_out == 1


@pytest.mark._dimI
def test_accuracy__dimI_sparse_coo_uncoalesced():
    # Duplicate coordinates leave the tensor uncoalesced; the sparse dimension
    # count is layout metadata and must not change.
    indices = torch.tensor([[0, 0, 1, 1], [0, 0, 0, 1]], dtype=torch.int64)
    sparse = torch.sparse_coo_tensor(indices, torch.randn(4), (2, 3))
    sparse = _to_device(sparse, flag_gems.device)
    assert not sparse.is_coalesced()

    ref_sparse = utils.to_reference(sparse)
    ref_out = torch.ops.aten._dimI(ref_sparse)
    res_out = flag_gems._dimI(sparse)

    assert res_out == ref_out
    assert res_out == 2


@pytest.mark._dimI
def test_accuracy__dimI_sparse_coo_zero_nnz():
    # An empty index matrix with the right number of rows still reports 2.
    sparse = torch.sparse_coo_tensor(
        torch.zeros(2, 0, dtype=torch.int64),
        torch.zeros(0),
        (2, 3),
    )
    sparse = _to_device(sparse, flag_gems.device)
    ref_sparse = utils.to_reference(sparse)

    ref_out = torch.ops.aten._dimI(ref_sparse)
    res_out = flag_gems._dimI(sparse)

    assert res_out == ref_out
    assert res_out == 2


@pytest.mark._dimI
def test_accuracy__dimI_reference_table():
    # Reference values captured in a process that never imported flag_gems
    # (un-substituted environment), pinned here as literals.
    table = {
        "coo-plain-2d": 2,
        "coo-plain-3d": 2,
        "coo-1d": 1,
        "coo-hybrid": 1,
        "coo-uncoalesced": 2,
        "coo-0nnz": 2,
    }
    plain = _to_device(_make_coo(2, 3, (2, 3), seed=1), flag_gems.device)
    assert flag_gems._dimI(plain) == table["coo-plain-2d"]
    plain3 = _to_device(_make_coo_hybrid(2, 4, (4, 5, 6), seed=9), flag_gems.device)
    assert flag_gems._dimI(plain3) == table["coo-plain-3d"]
    one_d = _to_device(
        torch.sparse_coo_tensor(torch.tensor([[0, 1]]), torch.randn(2), (2,)),
        flag_gems.device,
    )
    assert flag_gems._dimI(one_d) == table["coo-1d"]
    hybrid = _to_device(
        torch.sparse_coo_tensor(torch.tensor([[0, 1]]), torch.randn(2, 3), (2, 3)),
        flag_gems.device,
    )
    assert flag_gems._dimI(hybrid) == table["coo-hybrid"]
    unco = _to_device(
        torch.sparse_coo_tensor(
            torch.tensor([[0, 0, 1, 1], [0, 0, 0, 1]], dtype=torch.int64),
            torch.randn(4),
            (2, 3),
        ),
        flag_gems.device,
    )
    assert flag_gems._dimI(unco) == table["coo-uncoalesced"]
    empty = _to_device(
        torch.sparse_coo_tensor(
            torch.zeros(2, 0, dtype=torch.int64), torch.zeros(0), (2, 3)
        ),
        flag_gems.device,
    )
    assert flag_gems._dimI(empty) == table["coo-0nnz"]


@pytest.mark._dimI
def test_accuracy__dimI_strided_raises():
    # aten::_dimI has no dense kernel; both the native path and the registered
    # FlagGems path must raise NotImplementedError.
    dense = torch.randn(2, 3, device=flag_gems.device)
    ref_dense = utils.to_reference(dense)

    with pytest.raises(NotImplementedError):
        torch.ops.aten._dimI(ref_dense)
    with pytest.raises(NotImplementedError):
        flag_gems._dimI(dense)


@pytest.mark._dimI
def test_accuracy__dimI_sparse_compressed_raises():
    # aten::_dimI is not registered for the SparseCsr dispatch keys; CSR and
    # CSC must raise NotImplementedError natively, and no interception is
    # registered by FlagGems, so the error must survive unchanged.
    crow = torch.tensor([0, 2, 4], dtype=torch.int64)
    col = torch.tensor([0, 1, 0, 1], dtype=torch.int64)
    val = torch.randn(4)
    csr = _to_device(torch.sparse_csr_tensor(crow, col, val, (2, 3)), flag_gems.device)
    csc = _to_device(torch.sparse_csc_tensor(col, crow, val, (2, 3)), flag_gems.device)

    for name, t in [("csr", csr), ("csc", csc)]:
        with pytest.raises(NotImplementedError):
            torch.ops.aten._dimI(utils.to_reference(t))
        with pytest.raises(NotImplementedError):
            flag_gems._dimI(t)


@pytest.mark._dimI
def test__dimI_dispatch_stability():
    # Exercise the registered dispatcher path repeatedly: a recursion bug or
    # stale state in the implementation would surface here. Dispatching a
    # related metadata op (`_nnz`) in between must not re-route ``_dimI``.
    #
    # Registration mirrors the real one (dense CUDA key + sparse COO key) but
    # only for this operator, so the test can observe which kernel the
    # dispatcher picked. ``use_gems()`` is avoided on purpose.
    sparse = _to_device(_make_coo(2, 5, (2, 3), seed=7), flag_gems.device)
    hybrid = _to_device(
        torch.sparse_coo_tensor(torch.tensor([[0, 1]]), torch.randn(2, 3), (2, 3)),
        flag_gems.device,
    )
    dense = torch.randn(2, 3, device=flag_gems.device)

    calls = []

    def spy(self):
        calls.append(str(self.layout))
        return flag_gems._dimI(self)

    lib = torch.library.Library("aten", "IMPL")
    try:
        lib.impl("_dimI", spy, "CUDA")
        lib.impl("_dimI", spy, "SparseCUDA")

        # >= 3 dispatcher-routed calls on COO inputs, with a neighbouring
        # metadata op (``_nnz``) dispatched in between.
        assert torch.ops.aten._dimI(sparse) == 2
        assert torch.ops.aten._nnz(sparse) == 5
        assert torch.ops.aten._dimI(sparse) == 2
        assert torch.ops.aten._dimI(hybrid) == 1
        assert torch.ops.aten._dimI(sparse) == 2

        # A dense tensor carries the CUDA key and reaches the same impl, which
        # mirrors the native NotImplementedError contract.
        with pytest.raises(NotImplementedError):
            torch.ops.aten._dimI(dense)

        # Every COO call above had to route into the spy (i.e. into the
        # FlagGems implementation), not into the native kernel.
        assert calls.count("torch.sparse_coo") == 4
        assert calls.count("torch.strided") == 1
    finally:
        lib._destroy()

    # The temporary registration is gone: native behaviour is restored.
    with pytest.raises(NotImplementedError):
        torch.ops.aten._dimI(dense)
    assert flag_gems._dimI(sparse) == 2
