# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch
from _pytest.mark.structures import Mark, MarkDecorator

import flag_gems

from . import accuracy_utils as utils
from .conftest import QUICK_MODE

# ``_values_copy`` starts with an underscore, and ``pytest.mark`` refuses to
# generate a marker via attribute access for such names. Register the markers
# directly on the MarkGenerator so ``@pytest.mark._values_copy`` and
# ``-m _values_copy`` both work.
setattr(
    pytest.mark,
    "_values_copy",
    MarkDecorator(Mark("_values_copy", (), {}, _ispytest=True), _ispytest=True),
)
setattr(
    pytest.mark,
    "_values_copy_out",
    MarkDecorator(Mark("_values_copy_out", (), {}, _ispytest=True), _ispytest=True),
)


def _reference(x):
    """Native reference values for ``aten::_values_copy``.

    The op is a torchgen-generated ``view_copy`` whose kernel body is
    ``_values(self).clone(memory_format=Contiguous)``
    (torchgen/gen_functionalization_type.py, GenCompositeViewCopyKernel), so
    the reference is composed from the native values accessor plus ``clone``.
    The literal ``torch.ops.aten._values_copy`` is not callable for any of the
    inputs under test on this build: it has no Sparse dispatch-key kernel at
    all, and its composed body calls ``aten::_values``, which has no CUDA/CPU
    strided kernel (a COO input raises from the Sparse key, a dense input from
    the CUDA/CPU key).

    For a sparse tensor the values are the stored values; for a strided tensor
    they are the tensor itself, so the reference is a plain contiguous clone.
    """
    if x.is_sparse:
        return torch.ops.aten._values(x).clone(memory_format=torch.contiguous_format)
    return x.clone(memory_format=torch.contiguous_format)


def _same_values(a, b):
    """Compare two tensors device-agnostically.

    ``utils.gems_assert_equal`` asserts the reference is on CPU whenever the
    ``--ref=cpu`` phase is active, so it cannot compare two GPU tensors there.
    Checks whose two sides are both produced by the code under test (aliasing,
    mutation isolation, agreement with the input's stored values) therefore
    move both sides to the CPU explicitly, which is valid in both phases.
    """
    return torch.equal(a.detach().cpu(), b.detach().cpu())


def _values_input(shape, dtype, device, strided=False):
    """Values tensor of ``shape``/``dtype``, optionally non-contiguous.

    Integer and bool element types cannot be sampled with ``randn`` (there is
    no normal kernel for them), so they are built on the CPU and moved; the
    ``strided`` views are transposes (dense non-overlapping), which is the
    layout the ND kernel is written for. The dtype dispatch is on
    ``dtype.is_floating_point``/``dtype == torch.bool`` rather than on the
    ``utils`` dtype lists, which narrow under ``QUICK_MODE`` and would silently
    classify e.g. float32 as bool in the quick-cpu phase.
    """
    if dtype.is_floating_point or dtype.is_complex:
        values = torch.randn(shape, dtype=dtype, device=device)
    elif dtype == torch.bool:
        values = torch.randint(0, 2, size=shape, dtype=torch.bool, device="cpu").to(
            device
        )
    else:
        values = torch.randint(
            torch.iinfo(dtype).min,
            torch.iinfo(dtype).max,
            shape,
            dtype=dtype,
            device="cpu",
        ).to(device)
    if strided:
        # ``transpose`` covers 3-D+ where ``t()`` (<= 2-D) does not; both
        # produce the same dense non-overlapping non-contiguous layout.
        values = values.transpose(0, -1)
        assert not values.is_contiguous()
    return values


def _make_coo_plain(device, dtype=torch.float32):
    indices = torch.tensor([[0, 1, 1], [1, 0, 1]], dtype=torch.int64, device=device)
    values = _values_input((3,), dtype, device)
    return torch.sparse_coo_tensor(indices, values, (2, 3))


def _make_coo_hybrid(device, dtype=torch.float32):
    # One sparse dim plus two dense trailing dims: the values tensor carries
    # the dense dims, shape (nnz, 2, 3), contiguous -> flat-kernel path.
    indices = torch.tensor([[0, 1]], dtype=torch.int64, device=device)
    values = _values_input((2, 2, 3), dtype, device)
    return torch.sparse_coo_tensor(indices, values, (2, 2, 3))


def _make_coo_hybrid_strided(device, dtype=torch.float32):
    # Values handed to the sparse constructor as a transposed (dense
    # non-overlapping, non-contiguous) buffer. The constructor keeps that
    # layout, so the stored values are strided and take the ND-kernel path.
    indices = torch.tensor([[0, 1, 2]], dtype=torch.int64, device=device)
    values = _values_input((4, 3), dtype, device, strided=True)
    return torch.sparse_coo_tensor(indices, values, (4, 4))


def _make_coo_uncoalesced(device, dtype=torch.float32):
    # Duplicate coordinates: deliberately not coalesced. The stored values are
    # returned raw regardless of coalescing state.
    indices = torch.tensor([[0, 0, 1], [0, 0, 2]], dtype=torch.int64, device=device)
    values = _values_input((3,), dtype, device)
    return torch.sparse_coo_tensor(indices, values, (2, 3))


def _make_coo_zero_nnz(device, dtype=torch.float32):
    indices = torch.zeros(2, 0, dtype=torch.int64, device=device)
    values = torch.zeros(0, dtype=dtype, device=device)
    return torch.sparse_coo_tensor(indices, values, (2, 3))


COO_CASES = [
    ("coo-plain", _make_coo_plain),
    ("coo-hybrid", _make_coo_hybrid),
    ("coo-hybrid-strided", _make_coo_hybrid_strided),
    ("coo-uncoalesced", _make_coo_uncoalesced),
    ("coo-zero-nnz", _make_coo_zero_nnz),
]
if QUICK_MODE:
    COO_CASES = [
        ("coo-plain", _make_coo_plain),
        ("coo-hybrid-strided", _make_coo_hybrid_strided),
    ]

# Shapes for the dense (is_sparse=False) branch: a 1-D case, a small 2-D case
# and a large 4-D case; the square and cubic entries keep the strided variants
# genuinely non-contiguous.
DENSE_SHAPES = [(16,), (8, 8), (16, 128, 64, 60)]
if QUICK_MODE:
    DENSE_SHAPES = [(8, 8)]


def _dense_input(shape, dtype, strided=False):
    return _values_input(shape, dtype, flag_gems.device, strided=strided)


@pytest.mark._values_copy
@pytest.mark.parametrize(
    "name, make",
    COO_CASES,
    ids=[name for name, _ in COO_CASES],
)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_accuracy_values_copy_coo(name, make, dtype):
    # Sparse COO is the operator's reason to exist: those inputs carry the
    # SparseCUDA dispatch key, where native has no kernel on this build, so
    # these cases define the implemented contract.
    inp = make(flag_gems.device, dtype=dtype)
    ref_inp = utils.to_reference(inp)
    vals = inp._values()

    ref_out = _reference(ref_inp)
    res_out = flag_gems._values_copy(inp)

    assert res_out.shape == ref_out.shape == vals.shape
    assert res_out.dtype == ref_out.dtype == inp.dtype
    assert res_out.layout == torch.strided
    assert res_out.is_sparse is False
    utils.gems_assert_equal(res_out, ref_out)
    # Values are exactly the ones stored in the input.
    assert _same_values(res_out, vals)
    # Fresh allocation: the result is a copy, never the values storage.
    if vals.numel() > 0:
        assert res_out.data_ptr() != vals.data_ptr()
        assert res_out._base is None


@pytest.mark._values_copy
@pytest.mark.parametrize(
    "name, make",
    [
        ("plain", _make_coo_plain),
        ("hybrid", _make_coo_hybrid),
        ("hybrid-strided", _make_coo_hybrid_strided),
    ],
    ids=["plain", "hybrid", "hybrid-strided"],
)
def test_accuracy_values_copy_coo_dtype_sweep(name, make):
    # int/bool values exercise both kernels on non-float element types (they
    # are dtype-agnostic byte movers).
    for dtype in utils.INT_DTYPES + utils.BOOL_TYPES:
        inp = make(flag_gems.device, dtype=dtype)
        ref_out = _reference(utils.to_reference(inp))
        res_out = flag_gems._values_copy(inp)
        assert res_out.dtype == ref_out.dtype == dtype
        utils.gems_assert_equal(res_out, ref_out)
        assert res_out.data_ptr() != inp._values().data_ptr()


@pytest.mark._values_copy
@pytest.mark.parametrize("shape", DENSE_SHAPES)
@pytest.mark.parametrize("dtype", utils.FLOAT_DTYPES)
def test_accuracy_values_copy_dense(shape, dtype):
    # is_sparse is False: the values are the tensor itself, so the op is a
    # plain copy. Native's composed body also calls _values(self) here, which
    # has no dense CUDA kernel, so the override is the only working path.
    inp = _dense_input(shape, dtype)
    ref_out = _reference(utils.to_reference(inp))
    res_out = flag_gems._values_copy(inp)

    assert res_out.shape == ref_out.shape == inp.shape
    assert res_out.dtype == dtype
    utils.gems_assert_equal(res_out, ref_out)
    assert _same_values(res_out, inp)
    assert res_out.data_ptr() != inp.data_ptr()
    assert res_out._base is None


@pytest.mark._values_copy
@pytest.mark.parametrize("shape", DENSE_SHAPES)
def test_accuracy_values_copy_dense_dtype_sweep(shape):
    for dtype in utils.INT_DTYPES + utils.BOOL_TYPES:
        inp = _dense_input(shape, dtype)
        ref_out = _reference(utils.to_reference(inp))
        res_out = flag_gems._values_copy(inp)
        assert res_out.dtype == dtype
        utils.gems_assert_equal(res_out, ref_out)


@pytest.mark._values_copy
@pytest.mark.parametrize(
    "name, make",
    [
        ("plain", _make_coo_plain),
        ("hybrid", _make_coo_hybrid),
        ("hybrid-strided", _make_coo_hybrid_strided),
        ("uncoalesced", _make_coo_uncoalesced),
    ],
    ids=["plain", "hybrid", "hybrid-strided", "uncoalesced"],
)
def test_accuracy_values_copy_input_not_mutated(name, make):
    inp = make(flag_gems.device)
    before = inp._values().clone()

    res_out = flag_gems._values_copy(inp)
    assert res_out.data_ptr() != inp._values().data_ptr()
    # Writing to the copy must not reach the input values, and the copy must
    # carry the input's values before the write (a fill on an aliasing result
    # would also change ``inp._values()``).
    assert _same_values(res_out, before)
    res_out.fill_(123.0)
    assert _same_values(inp._values(), before)


@pytest.mark._values_copy
def test_accuracy_values_copy_strided_values():
    # The stored values of a COO tensor may be an arbitrary strided view (the
    # sparse constructor keeps the buffer it is handed), so the ND kernel
    # reconstructs physical offsets from the shape/stride table and returns the
    # elements in logical order.
    inp = _make_coo_hybrid_strided(flag_gems.device)
    vals = inp._values()
    assert not vals.is_contiguous()

    ref_out = _reference(utils.to_reference(inp))
    res_out = flag_gems._values_copy(inp)

    utils.gems_assert_equal(res_out, ref_out)
    assert _same_values(res_out, vals)
    assert res_out.shape == vals.shape
    assert res_out.data_ptr() != vals.data_ptr()


@pytest.mark._values_copy
@pytest.mark.parametrize("shape", [(8, 8), (4, 5, 6)])
def test_accuracy_values_copy_dense_non_contiguous(shape):
    # Dense non-contiguous input through the is_sparse=False branch. A
    # transpose is dense non-overlapping, so ``empty_like`` keeps the strides
    # and the ND kernel's offset map stays inside both buffers.
    inp = _dense_input(shape, torch.float32, strided=True)
    assert not inp.is_contiguous()
    ref_out = _reference(utils.to_reference(inp))
    res_out = flag_gems._values_copy(inp)

    utils.gems_assert_equal(res_out, ref_out)
    assert _same_values(res_out, inp)
    assert res_out.shape == inp.shape
    assert res_out.data_ptr() != inp.data_ptr()


@pytest.mark._values_copy
def test_accuracy_values_copy_gapped_values():
    # Values sliced with a step are strided but not dense: their maximal
    # physical offset exceeds numel - 1, so the ND kernel's offset map cannot
    # address a numel-element output buffer. The implementation materializes
    # such values and still returns the exact logical elements.
    base = torch.randn(3, 8, device=flag_gems.device)
    values = base[:, ::2]
    assert not values.is_contiguous()
    inp = torch.sparse_coo_tensor(
        torch.tensor([[0, 1, 2]], dtype=torch.int64, device=flag_gems.device),
        values,
        (4, 4),
    )
    assert inp._values().stride() == values.stride()

    ref_out = _reference(utils.to_reference(inp))
    res_out = flag_gems._values_copy(inp)

    utils.gems_assert_equal(res_out, ref_out)
    assert _same_values(res_out, inp._values())
    assert res_out.shape == inp._values().shape


@pytest.mark._values_copy
def test_accuracy_values_copy_expanded_values():
    # An expanded (stride-0) values buffer is the extreme non-dense strided
    # case: it overlaps itself and its stride table does not cover a dense
    # range, so it must take the materialized path.
    values = torch.randn(1, 3, device=flag_gems.device).expand(4, 3)
    assert values.stride() == (0, 1)
    inp = torch.sparse_coo_tensor(
        torch.tensor([[0, 1, 2, 3]], dtype=torch.int64, device=flag_gems.device),
        values,
        (5, 3),
    )

    ref_out = _reference(utils.to_reference(inp))
    res_out = flag_gems._values_copy(inp)

    utils.gems_assert_equal(res_out, ref_out)
    assert _same_values(res_out, inp._values())


@pytest.mark._values_copy
def test_accuracy_values_copy_empty_and_scalar():
    # Empty COO (nnz 0) and empty dense inputs short-circuit before the launch.
    # An empty CUDA tensor has no backing page (data_ptr 0 on both sides), so
    # no fresh-storage comparison is meaningful for them.
    coo_empty = _make_coo_zero_nnz(flag_gems.device)
    ref_coo = _reference(utils.to_reference(coo_empty))
    res_coo = flag_gems._values_copy(coo_empty)
    assert res_coo.shape == ref_coo.shape == (0,)
    assert res_coo.numel() == 0
    utils.gems_assert_equal(res_coo, ref_coo)

    hybrid_empty = torch.sparse_coo_tensor(
        torch.zeros(1, 0, dtype=torch.int64, device=flag_gems.device),
        torch.zeros(0, 2, device=flag_gems.device),
        (3, 2),
    )
    res_hybrid = flag_gems._values_copy(hybrid_empty)
    assert res_hybrid.shape == (0, 2)
    assert res_hybrid.numel() == 0

    dense_empty = torch.empty(0, device=flag_gems.device)
    ref_dense = _reference(utils.to_reference(dense_empty))
    res_dense = flag_gems._values_copy(dense_empty)
    assert res_dense.shape == ref_dense.shape == (0,)
    utils.gems_assert_equal(res_dense, ref_dense)

    scalar = torch.randn((), device=flag_gems.device)
    ref_scalar = _reference(utils.to_reference(scalar))
    res_scalar = flag_gems._values_copy(scalar)
    assert res_scalar.shape == ()
    assert res_scalar.numel() == 1
    utils.gems_assert_equal(res_scalar, ref_scalar)
    assert res_scalar.data_ptr() != scalar.data_ptr()

    single = torch.randn(1, device=flag_gems.device)
    ref_single = _reference(utils.to_reference(single))
    res_single = flag_gems._values_copy(single)
    utils.gems_assert_equal(res_single, ref_single)
    assert res_single.data_ptr() != single.data_ptr()


@pytest.mark._values_copy
@pytest.mark.parametrize("n_elem", [4096, 4096 * 3 + 17])
def test_accuracy_values_copy_block_boundaries(n_elem):
    # Cross the flat kernel's block size (4096) both exactly and with a
    # partial tail, on a contiguous and on a trailing-dense-dim values tensor
    # (the latter uses the ND kernel's tail block).
    device = flag_gems.device
    indices = torch.randint(0, 64, (1, n_elem), dtype=torch.int64, device=device)
    inp = torch.sparse_coo_tensor(indices, torch.randn(n_elem, device=device), (64,))
    ref_out = _reference(utils.to_reference(inp))
    res_out = flag_gems._values_copy(inp)
    utils.gems_assert_equal(res_out, ref_out)

    inp2 = torch.sparse_coo_tensor(
        indices, torch.randn(n_elem, 2, device=device), (64, 2)
    )
    ref_out2 = _reference(utils.to_reference(inp2))
    res_out2 = flag_gems._values_copy(inp2)
    utils.gems_assert_equal(res_out2, ref_out2)


@pytest.mark._values_copy
def test_accuracy_values_copy_dispatch_stability():
    # Repeated dispatches with unrelated aten traffic in between must stay
    # stable: the implementation allocates fresh storage per call and keeps no
    # state across calls.
    inp = _make_coo_plain(flag_gems.device)
    ref_out = _reference(utils.to_reference(inp))
    for _ in range(3):
        res_out = flag_gems._values_copy(inp)
        utils.gems_assert_equal(res_out, ref_out)
        assert torch.ops.aten._nnz(inp) == 3
        assert res_out.data_ptr() != inp._values().data_ptr()


@pytest.mark._values_copy_out
@pytest.mark.parametrize(
    "name, make",
    [
        ("plain", _make_coo_plain),
        ("hybrid", _make_coo_hybrid),
        ("hybrid-strided", _make_coo_hybrid_strided),
    ],
    ids=["plain", "hybrid", "hybrid-strided"],
)
def test_accuracy_values_copy_out(name, make):
    # The .out overload writes the values into the buffer and returns that
    # buffer itself.
    inp = make(flag_gems.device)
    ref_out = _reference(utils.to_reference(inp))

    out_buf = torch.empty(0, dtype=inp.dtype, device=flag_gems.device)
    ret = flag_gems._values_copy_out(inp, out=out_buf)

    assert ret.data_ptr() == out_buf.data_ptr()
    assert out_buf.shape == tuple(inp._values().shape)
    utils.gems_assert_equal(out_buf, ref_out)
    assert _same_values(out_buf, inp._values())
    # The buffer is a copy target: writing it does not reach the input.
    before = inp._values().clone()
    out_buf.fill_(7.0)
    assert _same_values(inp._values(), before)


@pytest.mark._values_copy_out
def test_accuracy_values_copy_out_strided_buffer():
    inp = _make_coo_hybrid_strided(flag_gems.device)
    ref_out = _reference(utils.to_reference(inp))

    # A contiguous buffer holding the same number of elements (the values are
    # strided, so their element count differs from the buffer's shape).
    plain = torch.empty(inp._values().numel(), dtype=inp.dtype, device=flag_gems.device)
    ret = flag_gems._values_copy_out(inp, out=plain)
    assert ret.data_ptr() == plain.data_ptr()
    utils.gems_assert_equal(plain.reshape(ref_out.shape), ref_out)

    # A buffer carrying the values' own strides.
    strided_buf = torch.empty_like(inp._values())
    ret2 = flag_gems._values_copy_out(inp, out=strided_buf)
    assert ret2.data_ptr() == strided_buf.data_ptr()
    utils.gems_assert_equal(strided_buf, ref_out)


@pytest.mark._values_copy_out
def test_accuracy_values_copy_out_empty_and_dense():
    coo_empty = _make_coo_zero_nnz(flag_gems.device)
    buf = torch.empty(3, dtype=torch.float32, device=flag_gems.device)
    ret = flag_gems._values_copy_out(coo_empty, out=buf)
    assert ret.data_ptr() == buf.data_ptr()
    assert buf.shape == (0,)

    dense = torch.randn(4, 5, device=flag_gems.device)
    out_buf = torch.empty(4, 5, device=flag_gems.device)
    ret2 = flag_gems._values_copy_out(dense, out=out_buf)
    assert ret2.data_ptr() == out_buf.data_ptr()
    utils.gems_assert_equal(out_buf, _reference(utils.to_reference(dense)))


@pytest.mark._values_copy_out
def test_accuracy_values_copy_out_rejects_bad_buffer():
    inp = _make_coo_plain(flag_gems.device)
    # The out copy checks the buffer's dtype and device and raises.
    with pytest.raises(RuntimeError):
        flag_gems._values_copy_out(
            inp, out=torch.empty(3, dtype=torch.float64, device=flag_gems.device)
        )
    with pytest.raises(RuntimeError):
        flag_gems._values_copy_out(inp, out=torch.empty(3, dtype=torch.float32))
