# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import itertools
import math

import pytest
import torch
from _pytest.mark.structures import Mark, MarkDecorator

import flag_gems

from . import accuracy_utils as utils
from .conftest import QUICK_MODE

# pytest refuses attribute access for names it does not know, so register the
# marker explicitly (the repository pattern for operators with an underscore /
# unregistered name).
setattr(
    pytest.mark,
    "cartesian_prod",
    MarkDecorator(Mark("cartesian_prod", (), {}, _ispytest=True), _ispytest=True),
)

# Each case is a list of 1-D input lengths. The output has prod(lengths) rows,
# so the groups stay small. The groups target distinct implementation branches
# of the submitted operator:
#   K == 2                  general chunk kernel with KP == 2
#   K == 3                  general kernel, one padded column tile slot
#   K == 4, even s_last     the row-paired 8-wide store specialisation
#   K == 4, odd s_last      general kernel (the pair path needs even s_last)
#   K >= 5, K == 8          more mixed-radix digits; K == 8 has zero padding
#   large s_last            more than one program along the row grid axis
K2_CASES = [[4, 3], [1, 1], [2, 1]]
K3_CASES = [[3, 4, 2], [2, 2, 2]]
K4_PAIR_CASES = [[4, 4, 4, 4], [2, 2, 2, 8], [8, 4, 2, 16]]
K4_ODD_CASES = [[3, 3, 3, 3], [5, 2, 3, 7]]
KN_CASES = [[2, 3, 4, 5, 2], [2, 2, 2, 2, 2, 2], [2, 2, 2, 2, 2, 2, 2, 2]]
MULTI_PROGRAM_CASES = [[2048, 3], [3, 2048], [1024, 3, 3]]
if QUICK_MODE:
    K2_CASES = [[4, 3]]
    K3_CASES = [[3, 4, 2]]
    K4_PAIR_CASES = [[4, 4, 4, 4]]
    K4_ODD_CASES = [[3, 3, 3, 3]]
    KN_CASES = [[2, 3, 4, 5, 2]]
    MULTI_PROGRAM_CASES = [[2048, 3]]

# (lengths, per-input strides): strided slices exercise the kernel's in-stride
# branch. Strides must be >= 1 and the result must stay 1-D.
STRIDED_CASES = [([6, 5], [2, 1]), ([4, 4, 3], [1, 3, 1]), ([5, 5], [3, 3])]
if QUICK_MODE:
    STRIDED_CASES = [([6, 5], [2, 1])]

SWEEP_DTYPES = utils.FLOAT_DTYPES + utils.INT_DTYPES + utils.BOOL_TYPES

EMPTY_CASES = [[0, 3], [3, 0], [2, 0, 4], [0, 0], [0, 0, 0, 0]]
if QUICK_MODE:
    EMPTY_CASES = [[0, 3], [2, 0, 4]]

ORDER_CASE = [[3, 2, 4]]
if QUICK_MODE:
    ORDER_CASE = [[2, 3]]


def _make_1d(length, dtype, seed=0):
    """Build a 1-D tensor of ``length`` elements on the gems device.

    Generators are seeded so the same values are produced on the reference and
    device paths. cartesian_prod only permutes input elements, so the
    comparison against the reference is exact for every supported dtype.
    """
    gen = torch.Generator().manual_seed(seed * 1000 + length)
    if dtype in utils.BOOL_TYPES:
        return torch.randint(0, 2, (length,), generator=gen).to(
            dtype=torch.bool, device=flag_gems.device
        )
    if dtype in utils.INT_DTYPES:
        return torch.randint(-1000, 1000, (length,), generator=gen).to(
            dtype=dtype, device=flag_gems.device
        )
    return torch.randn(length, generator=gen).to(dtype=dtype, device=flag_gems.device)


def _make_case(lengths, dtype, strides=None):
    """Return (device_inputs, reference_inputs) for one test case.

    Reference tensors are derived from the *converted* base tensor, never
    converted separately: ``Tensor.to("cpu")`` materializes a contiguous copy,
    so converting a strided view would lose the stride and the reference would
    stop matching (the ``--ref=cpu`` trap). Slicing the converted base keeps
    the reference on the same storage with the same stride.
    """
    device_tensors, ref_tensors = [], []
    for i, length in enumerate(lengths):
        step = 1 if strides is None else strides[i]
        backing_len = length * step if step > 1 else length
        backing = _make_1d(backing_len, dtype, seed=i)
        ref_backing = utils.to_reference(backing)
        if step > 1 and length > 0:
            device_tensors.append(backing[::step][:length])
            ref_tensors.append(ref_backing[::step][:length])
        else:
            device_tensors.append(backing)
            ref_tensors.append(ref_backing)
    return device_tensors, ref_tensors


def _shape_fragment(t):
    """Render a shape in a build-agnostic way (A1).

    This build's native message renders IntArrayRef as ``[3, 3]``; other
    builds may print the tuple form ``(3, 3)``. Accept either rendering so a
    different runner torch cannot fail the assertion on wording alone.
    """
    dims = ", ".join(str(int(s)) for s in t.shape)
    return ("[" + dims + "]", "(" + dims + ")")


@pytest.mark.cartesian_prod
@pytest.mark.parametrize(
    "lengths",
    K2_CASES + K3_CASES + K4_PAIR_CASES + K4_ODD_CASES + KN_CASES,
)
@pytest.mark.parametrize("dtype", SWEEP_DTYPES)
def test_accuracy_cartesian_prod(lengths, dtype):
    k = len(lengths)
    inp, ref_inp = _make_case(lengths, dtype)
    ref_out = torch.ops.aten.cartesian_prod(ref_inp)

    res_out = flag_gems.cartesian_prod(inp)

    assert tuple(res_out.shape) == (math.prod(lengths), k) == tuple(ref_out.shape)
    assert res_out.dtype == ref_out.dtype == dtype
    assert res_out.device == inp[0].device
    # Freshly allocated output: it never aliases any input.
    for t in inp:
        assert res_out.data_ptr() != t.data_ptr()
    assert res_out._base is None
    assert res_out.is_contiguous() == ref_out.is_contiguous()
    # Row order must match native lexicographic order (last input fastest).
    assert res_out.tolist() == ref_out.tolist()
    utils.gems_assert_equal(res_out, ref_out)


@pytest.mark.cartesian_prod
@pytest.mark.parametrize("lengths,strides", STRIDED_CASES)
@pytest.mark.parametrize("dtype", [torch.float32, torch.int32, torch.bool])
def test_accuracy_cartesian_prod_strided_inputs(lengths, strides, dtype):
    # Non-contiguous 1-D inputs: the kernel reads through each input's logical
    # stride (data_ptr + stride), so no materializing copy is required. The
    # output is always contiguous, matching native.
    inp, ref_inp = _make_case(lengths, dtype, strides=strides)
    for t, step in zip(inp, strides):
        assert t.dim() == 1
        if step > 1 and t.numel() > 0:
            assert not t.is_contiguous()
    ref_out = torch.ops.aten.cartesian_prod(ref_inp)

    res_out = flag_gems.cartesian_prod(inp)

    assert tuple(res_out.shape) == tuple(ref_out.shape)
    assert res_out.is_contiguous()
    assert res_out.stride() == (len(lengths), 1)
    assert res_out.tolist() == ref_out.tolist()
    utils.gems_assert_equal(res_out, ref_out)


@pytest.mark.cartesian_prod
@pytest.mark.parametrize("lengths", MULTI_PROGRAM_CASES)
@pytest.mark.parametrize("dtype", [torch.float32, torch.int32])
def test_accuracy_cartesian_prod_multi_program(lengths, dtype):
    # s_last > 1024 forces more than one program along the row grid axis;
    # enough chunks force more than one along the chunk axis as well.
    inp, ref_inp = _make_case(lengths, dtype)
    ref_out = torch.ops.aten.cartesian_prod(ref_inp)

    res_out = flag_gems.cartesian_prod(inp)

    assert tuple(res_out.shape) == tuple(ref_out.shape)
    assert res_out[:16].tolist() == ref_out[:16].tolist()
    assert res_out[-16:].tolist() == ref_out[-16:].tolist()
    assert res_out.is_contiguous()
    utils.gems_assert_equal(res_out, ref_out)


@pytest.mark.cartesian_prod
@pytest.mark.parametrize("lengths", EMPTY_CASES)
def test_accuracy_cartesian_prod_empty(lengths):
    # Any zero-length input makes the product zero; native still returns a
    # (0, K) tensor with a zero leading dimension and the shared dtype.
    inp, ref_inp = _make_case(lengths, torch.float32)
    ref_out = torch.ops.aten.cartesian_prod(ref_inp)

    res_out = flag_gems.cartesian_prod(inp)

    assert tuple(res_out.shape) == (0, len(lengths)) == tuple(ref_out.shape)
    assert res_out.numel() == 0
    assert res_out.dtype == torch.float32
    utils.gems_assert_equal(res_out, ref_out)


@pytest.mark.cartesian_prod
@pytest.mark.parametrize("dtype", SWEEP_DTYPES)
def test_accuracy_cartesian_prod_single_tensor_identity(dtype):
    # K == 1: native returns the input tensor object itself -- identity, not a
    # view wrapper and not a copy. Every dtype takes this branch.
    inp = _make_1d(7, dtype)
    ref_inp = utils.to_reference(inp)

    res_out = flag_gems.cartesian_prod([inp])
    ref_out = torch.ops.aten.cartesian_prod([ref_inp])

    assert res_out is inp
    assert res_out.data_ptr() == inp.data_ptr()
    assert res_out._base is None
    assert tuple(res_out.shape) == tuple(ref_out.shape)
    assert res_out.dtype == ref_out.dtype
    utils.gems_assert_equal(res_out, ref_out)


@pytest.mark.cartesian_prod
def test_accuracy_cartesian_prod_single_tensor_strided_identity():
    # K == 1 with a non-contiguous input: native is still the identity. It
    # returns the strided tensor unchanged rather than calling reshape/contiguous.
    backing = _make_1d(20, torch.float32)
    inp = backing[::3]
    assert not inp.is_contiguous()
    ref_backing = utils.to_reference(backing)
    ref_inp = ref_backing[::3]

    res_out = flag_gems.cartesian_prod([inp])
    ref_out = torch.ops.aten.cartesian_prod([ref_inp])

    assert res_out is inp
    assert res_out.data_ptr() == inp.data_ptr()
    # Compare strides against a reference view sliced from the converted base
    # (converting the view itself would materialize a contiguous copy).
    assert res_out.stride() == ref_inp.stride()
    assert res_out.is_contiguous() == ref_inp.is_contiguous()
    assert tuple(res_out.shape) == tuple(ref_out.shape)
    utils.gems_assert_equal(res_out, ref_out)


@pytest.mark.cartesian_prod
def test_accuracy_cartesian_prod_single_tensor_empty():
    inp = _make_1d(0, torch.float32)
    ref_inp = utils.to_reference(inp)

    res_out = flag_gems.cartesian_prod([inp])
    ref_out = torch.ops.aten.cartesian_prod([ref_inp])

    assert res_out is inp
    assert tuple(res_out.shape) == (0,) == tuple(ref_out.shape)
    assert res_out.dtype == torch.float32


@pytest.mark.cartesian_prod
@pytest.mark.parametrize("dtype", [torch.float32, torch.int32, torch.bool])
def test_accuracy_cartesian_prod_single_element_inputs(dtype):
    # K == 2 with singleton sizes hits the cb/bs lower-bound clamps and the
    # n == k == 1 corner of the general kernel.
    inp, ref_inp = _make_case([1, 1], dtype)
    ref_out = torch.ops.aten.cartesian_prod(ref_inp)

    res_out = flag_gems.cartesian_prod(inp)

    assert tuple(res_out.shape) == (1, 2)
    assert res_out.tolist() == ref_out.tolist()
    utils.gems_assert_equal(res_out, ref_out)


@pytest.mark.cartesian_prod
@pytest.mark.parametrize("dtype", [torch.float16, torch.float32, torch.bfloat16])
def test_accuracy_cartesian_prod_k4_pair_path(dtype):
    # K == 4, even s_last and a power-of-two half take the dedicated
    # row-paired kernel (8-wide innermost dim -> 16-byte stores).
    lengths = [4, 4, 4, 16]
    inp, ref_inp = _make_case(lengths, dtype)
    ref_out = torch.ops.aten.cartesian_prod(ref_inp)

    res_out = flag_gems.cartesian_prod(inp)

    assert tuple(res_out.shape) == (1024, 4)
    assert res_out.tolist() == ref_out.tolist()
    utils.gems_assert_equal(res_out, ref_out)


@pytest.mark.cartesian_prod
@pytest.mark.parametrize("lengths", ORDER_CASE)
def test_accuracy_cartesian_prod_order_is_lexicographic(lengths):
    # Independent ordering check (itertools.product is the documented
    # semantics): the last input varies fastest and rows are lexicographic.
    inp, _ = _make_case(lengths, torch.int32)
    values = [t.tolist() for t in inp]
    want_rows = [
        [values[j][idx[j]] for j in range(len(lengths))]
        for idx in itertools.product(*(range(n) for n in lengths))
    ]

    res_out = flag_gems.cartesian_prod(inp)

    assert res_out.tolist() == want_rows
    # Cross-check against the ATen reference row by row.
    ref_out = torch.ops.aten.cartesian_prod([t.cpu() for t in inp])
    assert res_out.tolist() == ref_out.tolist()


@pytest.mark.cartesian_prod
def test_accuracy_cartesian_prod_aten_tensorlist_form():
    # The only overload on this build takes a TensorList: the implementation is
    # called with the list form, and the same values must come out of a call
    # with the same tensors re-collected into a fresh list.
    assert torch.ops.aten.cartesian_prod.overloads() == ["default"]
    assert "Tensor[]" in str(torch.ops.aten.cartesian_prod.default._schema)
    lengths = [3, 4, 2]
    inp, ref_inp = _make_case(lengths, torch.float32)
    ref_out = torch.ops.aten.cartesian_prod(ref_inp)

    res_direct = flag_gems.cartesian_prod(inp)
    res_list = flag_gems.cartesian_prod(list(inp))

    assert res_direct.tolist() == ref_out.tolist()
    assert res_list.tolist() == ref_out.tolist()
    utils.gems_assert_equal(res_direct, ref_out)
    utils.gems_assert_equal(res_list, ref_out)


@pytest.mark.cartesian_prod
def test_accuracy_cartesian_prod_repeated_calls_are_stable():
    # Five repeated calls must return consistent values, and the outputs of
    # separate calls are independent allocations.
    lengths = [4, 3]
    inp, ref_inp = _make_case(lengths, torch.float32)
    ref_out = torch.ops.aten.cartesian_prod(ref_inp)

    outs = [flag_gems.cartesian_prod(inp) for _ in range(5)]

    for out in outs:
        utils.gems_assert_equal(out, ref_out)
    # Each call allocates its own output storage.
    for i in range(len(outs)):
        for j in range(i + 1, len(outs)):
            assert outs[i].data_ptr() != outs[j].data_ptr()


@pytest.mark.cartesian_prod
@pytest.mark.parametrize("lengths", K2_CASES + K4_ODD_CASES)
def test_accuracy_cartesian_prod_non_1d_raises(lengths):
    # Native rejects any input whose dim != 1 (0-dim and 2-D included) with
    # RuntimeError before any dtype or device check. Assert the exception
    # class plus semantic fragments (the offending shape) rather than one
    # build's full sentence: CI's runner torch is a different build (A1).
    inp, _ = _make_case(lengths, torch.float32)
    good = inp[0]
    bad_2d = _make_1d(lengths[0] * lengths[1], torch.float32).reshape(*lengths[:2])
    bad_0d = _make_1d(1, torch.float32)[0]

    for bad in (bad_2d, bad_0d):
        with pytest.raises(RuntimeError) as excinfo:
            flag_gems.cartesian_prod([good, bad])
        message = str(excinfo.value)
        assert "1D" in message
        assert any(fragment in message for fragment in _shape_fragment(bad))


@pytest.mark.cartesian_prod
def test_accuracy_cartesian_prod_dtype_mismatch_raises():
    # Native meshgrid requires a uniform dtype across inputs.
    a = _make_1d(3, torch.float32)
    b = _make_1d(2, torch.int32)

    with pytest.raises(RuntimeError) as excinfo:
        flag_gems.cartesian_prod([a, b])
    assert "dtype" in str(excinfo.value)


@pytest.mark.cartesian_prod
def test_accuracy_cartesian_prod_device_mismatch_raises():
    # Native meshgrid requires a uniform device across inputs. The reference
    # side cannot reproduce the mismatch in the --ref=cpu phase (both operands
    # are converted to CPU), so only the dispatched implementation is checked
    # here; the check itself mirrors the measured native contract.
    cuda_t = _make_1d(3, torch.float32)
    cpu_t = torch.arange(2, dtype=torch.float32)

    with pytest.raises(RuntimeError) as excinfo:
        flag_gems.cartesian_prod([cuda_t, cpu_t])
    assert "device" in str(excinfo.value)


@pytest.mark.cartesian_prod
def test_accuracy_cartesian_prod_zero_inputs_raises():
    # Native meshgrid rejects an empty TensorList.
    with pytest.raises(RuntimeError) as excinfo:
        flag_gems.cartesian_prod([])
    assert (
        "non-empty" in str(excinfo.value).lower()
        or "empty" in str(excinfo.value).lower()
    )
