# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch
from pytest import Mark, MarkDecorator

import flag_gems

from . import accuracy_utils as utils
from .conftest import QUICK_MODE

# ``sparse_bsr_tensor`` is a host-side constructor: its accuracy contract is
# which component tensors are accepted or rejected, whether the resulting
# tensor aliases them, and what the resulting metadata is. There is no
# elementwise arithmetic to compare, so the assertions below compare the
# metadata fingerprint and the stored components against the reference
# constructor rather than elementwise closeness.
#
# Native metadata and error contract captured in a process that never imported
# flag_gems (runs/sparse_bsr_tensor/native_probe_e.log / native_probe_h.log /
# native_probe_i.log):
#   - the member tensors ALIAS the inputs (data_ptr identity on all three);
#   - `size` is stored verbatim: it is not checked for block divisibility and
#     need not match the block shape carried by `values`;
#   - the packet overloads take their target device AND dtype from the keyword
#     arguments ONLY (TensorOptions falls back to the default device and
#     float32 when they are absent) and then assert every member matches, so
#     CUDA components built without `device=` raise "Values and compressed
#     tensor instance need to be on the same device." and non-float32 values
#     without `dtype=` raise "dtype of values (Half) must match dtype of
#     sparse tensor (Float)". The Python builtin has no such requirement
#     because its C++ argument parser derives both from `values`; the packet
#     forms must pass them explicitly, so every call below does;
#   - the size-inference form reads the block shape from values.shape[-2:] and
#     the block-row count from crow_indices.shape[-1] - 1;
#   - only integral col_indices dtypes are accepted by the size estimator.
setattr(
    pytest.mark,
    "sparse_bsr_tensor",
    MarkDecorator(Mark("sparse_bsr_tensor", (), {}, _ispytest=True), _ispytest=True),
)

# (n_block_rows, n_block_cols, block_rows, block_cols, seed)
BSR_CASES = [
    (1, 1, 2, 2, 0),
    (2, 2, 2, 2, 1),
    (3, 2, 2, 3, 2),
]
if not QUICK_MODE:
    BSR_CASES += [
        (8, 8, 4, 4, 3),
        (16, 12, 3, 5, 4),
        (4, 4, 1, 1, 5),
    ]

# Index dtype of the component tensors. Both are accepted; the builtin
# promotes to int64 before it hands the components over, the packet overloads
# keep whatever they are given.
INDEX_DTYPES = [torch.int64] if QUICK_MODE else [torch.int32, torch.int64]

# values dtypes the constructor stores verbatim (no dtype conversion on the
# native path: a dtype kwarg that disagrees with values is rejected instead).
VALUE_DTYPES = [torch.float32, torch.float64]
if not QUICK_MODE:
    VALUE_DTYPES += [torch.float16, torch.int32, torch.int64, torch.bool]


def _make_components(
    n_block_rows,
    n_block_cols,
    block_rows,
    block_cols,
    seed,
    device,
    index_dtype=torch.int64,
    value_dtype=torch.float32,
):
    """Build raw BSR components with a valid structure.

    Block columns are drawn strictly increasing per block row so the tensor
    also satisfies the (opt-in) compressed-index invariants; nnz is the number
    of stored blocks.
    """
    gen = torch.Generator(device="cpu").manual_seed(seed)
    nnz = 0
    crow = [0]
    col = []
    for _ in range(n_block_rows):
        # At least one block per block row, capped by the block-column count.
        if n_block_cols > 1:
            k = int(torch.randint(1, n_block_cols, (1,), generator=gen).item())
        else:
            k = 1
        picks = torch.randperm(n_block_cols, generator=gen)[:k].sort().values
        col.extend(int(v) for v in picks)
        nnz += k
        crow.append(nnz)
    crow_indices = torch.tensor(crow, dtype=index_dtype, device=device)
    col_indices = torch.tensor(col, dtype=index_dtype, device=device)
    # The generator is a CPU generator, so the random tensors are built on CPU
    # and moved; passing device=device alongside it would raise
    # "Expected a 'cuda' device type for generator but found 'cpu'".
    values = torch.randn((nnz, block_rows, block_cols), generator=gen).to(device)
    if value_dtype.is_floating_point:
        values = values.to(value_dtype)
    else:
        values = torch.randint(0, 8, (nnz, block_rows, block_cols), generator=gen).to(
            device=device, dtype=value_dtype
        )
    size = [n_block_rows * block_rows, n_block_cols * block_cols]
    return crow_indices, col_indices, values, size


def _options(kwargs, values):
    """Apply the components' device and dtype to a packet-overload call.

    Both sides get the same treatment so the comparison stays honest. The
    packet overloads take their target device and dtype from the keyword
    arguments ONLY (TensorOptions defaults to the default device and float32
    when they are absent) and then assert the components match; so on CUDA
    they must be passed explicitly for any values tensor that is not float32
    or not on the default device. Measured in native_probe_h.log /
    native_probe_i.log -- the Python builtin has no such requirement because
    its C++ argument parser derives both from `values`.
    """
    kwargs.setdefault("device", values.device)
    kwargs.setdefault("dtype", values.dtype)
    return kwargs


def gems_size(crow, col, values, size, **kwargs):
    return flag_gems.sparse_bsr_tensor_crow_col_value_size(
        crow, col, values, size, **_options(kwargs, values)
    )


def ref_size(crow, col, values, size, **kwargs):
    return torch.ops.aten.sparse_bsr_tensor.crow_col_value_size(
        crow, col, values, size, **_options(kwargs, values)
    )


def gems_infer(crow, col, values, **kwargs):
    return flag_gems.sparse_bsr_tensor_crow_col_value(
        crow, col, values, **_options(kwargs, values)
    )


def ref_infer(crow, col, values, **kwargs):
    return torch.ops.aten.sparse_bsr_tensor.crow_col_value(
        crow, col, values, **_options(kwargs, values)
    )


def _meta(t):
    """Metadata + stored-component fingerprint of a BSR tensor."""
    assert t.layout == torch.sparse_bsr, f"expected BSR layout, got {t.layout}"
    return (
        tuple(t.shape),
        t.dtype,
        t.layout,
        t._nnz(),
        t.sparse_dim(),
        t.dense_dim(),
        tuple(t.values().shape),
        t.values().dtype,
        t.crow_indices().dtype,
        t.col_indices().dtype,
    )


def _components_equal(res, ref):
    assert res.crow_indices().dtype == ref.crow_indices().dtype
    assert res.col_indices().dtype == ref.col_indices().dtype
    assert torch.equal(res.crow_indices().cpu(), ref.crow_indices().cpu())
    assert torch.equal(res.col_indices().cpu(), ref.col_indices().cpu())
    assert torch.equal(res.values().cpu(), ref.values().cpu())


@pytest.mark.sparse_bsr_tensor
@pytest.mark.parametrize("index_dtype", INDEX_DTYPES)
@pytest.mark.parametrize("nbr, nbc, br, bc, seed", BSR_CASES)
def test_sparse_bsr_tensor_crow_col_value_size(nbr, nbc, br, bc, seed, index_dtype):
    # aten::sparse_bsr_tensor.crow_col_value_size — the explicit-size form.
    crow, col, values, size = _make_components(
        nbr, nbc, br, bc, seed, flag_gems.device, index_dtype=index_dtype
    )
    ref = ref_size(
        utils.to_reference(crow),
        utils.to_reference(col),
        utils.to_reference(values),
        list(size),
    )
    res = gems_size(crow, col, values, list(size))
    assert _meta(res) == _meta(ref), f"metadata mismatch: {_meta(res)} != {_meta(ref)}"
    _components_equal(res, ref)
    assert tuple(res.shape) == (nbr * br, nbc * bc)
    assert tuple(res.values().shape[-2:]) == (br, bc)


@pytest.mark.sparse_bsr_tensor
@pytest.mark.parametrize("nbr, nbc, br, bc, seed", BSR_CASES)
def test_sparse_bsr_tensor_crow_col_value_infer(nbr, nbc, br, bc, seed):
    # aten::sparse_bsr_tensor.crow_col_value — size inferred from the
    # block-row count and the largest block column.
    crow, col, values, _ = _make_components(nbr, nbc, br, bc, seed, flag_gems.device)
    ref = ref_infer(
        utils.to_reference(crow), utils.to_reference(col), utils.to_reference(values)
    )
    res = gems_infer(crow, col, values)
    assert _meta(res) == _meta(ref), f"metadata mismatch: {_meta(res)} != {_meta(ref)}"
    _components_equal(res, ref)
    # The inferred size is exactly the BSR estimate: rows from the block-row
    # count, columns from the largest stored block column.
    assert tuple(res.shape) == (
        int(crow.numel() - 1) * br,
        (int(col.max().item()) + 1) * bc,
    )


@pytest.mark.sparse_bsr_tensor
@pytest.mark.parametrize("value_dtype", VALUE_DTYPES)
def test_sparse_bsr_tensor_values_dtypes(value_dtype):
    # The constructor stores values verbatim and reports their dtype; every
    # dtype class ATen accepts must round-trip through both overloads.
    dev = flag_gems.device
    crow, col, values, size = _make_components(
        2, 3, 2, 2, 11, dev, value_dtype=value_dtype
    )
    ref = ref_size(
        utils.to_reference(crow),
        utils.to_reference(col),
        utils.to_reference(values),
        list(size),
    )
    res = gems_size(crow, col, values, list(size))
    assert res.dtype == value_dtype
    assert res.values().dtype == value_dtype
    assert _meta(res) == _meta(ref)

    ref_n = ref_infer(
        utils.to_reference(crow), utils.to_reference(col), utils.to_reference(values)
    )
    res_n = gems_infer(crow, col, values)
    assert res_n.dtype == value_dtype
    assert _meta(res_n) == _meta(ref_n)


@pytest.mark.sparse_bsr_tensor
@pytest.mark.parametrize("index_dtype", INDEX_DTYPES)
def test_sparse_bsr_tensor_index_dtypes(index_dtype):
    # Both int32 and int64 component indices are accepted and stored as given;
    # the constructor performs no promotion (that is the Python builtin's job).
    dev = flag_gems.device
    crow, col, values, size = _make_components(
        2, 3, 2, 2, 12, dev, index_dtype=index_dtype
    )
    ref = ref_size(
        utils.to_reference(crow),
        utils.to_reference(col),
        utils.to_reference(values),
        list(size),
    )
    res = gems_size(crow, col, values, list(size))
    assert res.crow_indices().dtype == index_dtype
    assert res.col_indices().dtype == index_dtype
    assert _meta(res) == _meta(ref)

    ref_n = ref_infer(
        utils.to_reference(crow), utils.to_reference(col), utils.to_reference(values)
    )
    res_n = gems_infer(crow, col, values)
    assert res_n.crow_indices().dtype == index_dtype
    assert _meta(res_n) == _meta(ref_n)


@pytest.mark.sparse_bsr_tensor
def test_sparse_bsr_tensor_aliases_components():
    # The BSR constructor is a wiring op: the result's member tensors share
    # storage with the inputs, so writes through either side are visible on the
    # other.
    #
    # The reference aliasing check is driven from the ALREADY-CONVERTED base
    # tensors (not from a second utils.to_reference call), because with
    # --ref=cpu each conversion produces an independent CPU copy and comparing
    # a reference member against a separately converted input would compare
    # two unrelated allocations.
    dev = flag_gems.device
    crow, col, values, size = _make_components(2, 2, 2, 2, 13, dev)
    res = gems_size(crow, col, values, list(size))

    for name, got, want in (
        ("crow_indices", res.crow_indices(), crow),
        ("col_indices", res.col_indices(), col),
        ("values", res.values(), values),
    ):
        assert got.data_ptr() == want.data_ptr(), f"{name} must alias its input"
        assert got.untyped_storage().nbytes() == want.untyped_storage().nbytes()

    # Native is an alias too, so the contract being mirrored is real. The
    # reference is built from the converted base and compared against those
    # same converted tensors.
    ref_crow = utils.to_reference(crow)
    ref_col = utils.to_reference(col)
    ref_values = utils.to_reference(values)
    ref = ref_size(ref_crow, ref_col, ref_values, list(size))
    assert ref.crow_indices().data_ptr() == ref_crow.data_ptr()
    assert ref.col_indices().data_ptr() == ref_col.data_ptr()
    assert ref.values().data_ptr() == ref_values.data_ptr()

    # A write through the input component shows up in the constructed tensor
    # on both sides.
    values.fill_(7.0)
    assert bool((res.values() == 7.0).all().item())
    ref_values.fill_(7.0)
    assert bool((ref.values() == 7.0).all().item())


@pytest.mark.sparse_bsr_tensor
def test_sparse_bsr_tensor_does_not_copy_values():
    # A non-contiguous values tensor keeps its strides: the constructor stores
    # the tensor it was handed rather than materializing a contiguous copy.
    # The reference view is derived from the ALREADY-CONVERTED values base so
    # the two sides stay comparable under --ref=cpu.
    dev = flag_gems.device
    crow, col, values, size = _make_components(2, 2, 2, 2, 14, dev)
    strided = values.permute(0, 2, 1)
    ref_values = utils.to_reference(values).permute(0, 2, 1)
    ref = ref_size(
        utils.to_reference(crow),
        utils.to_reference(col),
        ref_values,
        list(size),
        layout=torch.sparse_bsr,
    )
    res = gems_size(crow, col, strided, list(size), layout=torch.sparse_bsr)
    assert res.values().stride() == strided.stride()
    assert ref.values().stride() == strided.stride()
    assert _meta(res) == _meta(ref)


@pytest.mark.sparse_bsr_tensor
def test_sparse_bsr_tensor_zero_blocks():
    # nnz == 0: the explicit form stores the requested size, the inference form
    # produces a zero plain extent (max over an empty column index is 0).
    dev = flag_gems.device
    crow = torch.tensor([0, 0, 0], dtype=torch.int64, device=dev)
    col = torch.tensor([], dtype=torch.int64, device=dev)
    values = torch.randn(0, 2, 2, device=dev)

    for size in ([4, 4], [0, 0]):
        ref = ref_size(
            utils.to_reference(crow),
            utils.to_reference(col),
            utils.to_reference(values),
            list(size),
        )
        res = gems_size(crow, col, values, list(size))
        assert _meta(res) == _meta(ref)
        assert res._nnz() == 0
        assert tuple(res.shape) == tuple(size)

    ref = ref_infer(
        utils.to_reference(crow), utils.to_reference(col), utils.to_reference(values)
    )
    res = gems_infer(crow, col, values)
    assert _meta(res) == _meta(ref)
    assert res._nnz() == 0
    assert tuple(res.shape) == (4, 0)


@pytest.mark.sparse_bsr_tensor
def test_sparse_bsr_tensor_single_block():
    # One stored block in a 1x1 block grid, the smallest non-empty tensor.
    dev = flag_gems.device
    crow = torch.tensor([0, 1], dtype=torch.int64, device=dev)
    col = torch.tensor([0], dtype=torch.int64, device=dev)
    values = torch.arange(6.0, device=dev).reshape(1, 2, 3)
    size = [2, 3]
    ref = ref_size(
        utils.to_reference(crow),
        utils.to_reference(col),
        utils.to_reference(values),
        size,
    )
    res = gems_size(crow, col, values, size)
    assert _meta(res) == _meta(ref)
    _components_equal(res, ref)
    assert tuple(res.shape) == (2, 3)
    assert res._nnz() == 1

    ref_n = ref_infer(
        utils.to_reference(crow), utils.to_reference(col), utils.to_reference(values)
    )
    res_n = gems_infer(crow, col, values)
    assert _meta(res_n) == _meta(ref_n)
    assert tuple(res_n.shape) == (2, 3)


@pytest.mark.sparse_bsr_tensor
def test_sparse_bsr_tensor_hybrid_dense_dim():
    # values with a trailing dense dimension make a hybrid BSR tensor: the
    # block shape is still values.shape[-2:] and dense_dim follows from the
    # remaining leading (non-batch) dimensions.
    dev = flag_gems.device
    crow = torch.tensor([0, 1, 2], dtype=torch.int64, device=dev)
    col = torch.tensor([0, 1], dtype=torch.int64, device=dev)
    values = torch.randn(2, 2, 2, 3, device=dev)
    size = [4, 4, 3]
    ref = ref_size(
        utils.to_reference(crow),
        utils.to_reference(col),
        utils.to_reference(values),
        size,
    )
    res = gems_size(crow, col, values, size)
    assert _meta(res) == _meta(ref)
    assert res.dense_dim() == 1
    assert tuple(res.values().shape) == (2, 2, 2, 3)

    ref_n = ref_infer(
        utils.to_reference(crow), utils.to_reference(col), utils.to_reference(values)
    )
    res_n = gems_infer(crow, col, values)
    assert _meta(res_n) == _meta(ref_n)
    assert res_n.dense_dim() == 1


@pytest.mark.sparse_bsr_tensor
def test_sparse_bsr_tensor_batched():
    # A 2-D crow_indices (and matching col_indices) makes a batched BSR tensor;
    # the block shape is read from the trailing dimensions of values.
    dev = flag_gems.device
    crow = torch.tensor([[0, 1], [0, 1]], dtype=torch.int64, device=dev)
    col = torch.tensor([[0], [1]], dtype=torch.int64, device=dev)
    values = torch.randn(2, 1, 2, 2, device=dev)
    size = [2, 4, 4]
    ref = ref_size(
        utils.to_reference(crow),
        utils.to_reference(col),
        utils.to_reference(values),
        size,
    )
    res = gems_size(crow, col, values, size)
    assert _meta(res) == _meta(ref)
    assert tuple(res.shape) == (2, 4, 4)

    ref_n = ref_infer(
        utils.to_reference(crow), utils.to_reference(col), utils.to_reference(values)
    )
    res_n = gems_infer(crow, col, values)
    assert _meta(res_n) == _meta(ref_n)
    assert tuple(res_n.shape) == (2, 2, 4)


@pytest.mark.sparse_bsr_tensor
def test_sparse_bsr_tensor_size_stored_verbatim():
    # The native constructor does NOT validate that `size` is divisible by the
    # block shape, nor that it agrees with the block shape carried by values.
    # Both mismatches are accepted and the size is stored as given; pin that
    # against native so a "helpful" extra validation cannot creep in.
    dev = flag_gems.device
    crow = torch.tensor([0, 1, 2], dtype=torch.int64, device=dev)
    col = torch.tensor([0, 1], dtype=torch.int64, device=dev)
    values = torch.randn(2, 2, 2, device=dev)
    for size in ([5, 4], [4, 4], [8, 8]):
        ref = ref_size(
            utils.to_reference(crow),
            utils.to_reference(col),
            utils.to_reference(values),
            list(size),
        )
        res = gems_size(crow, col, values, list(size))
        assert tuple(res.shape) == tuple(size)
        assert _meta(res) == _meta(ref)

    # A block shape in values that disagrees with `size` is equally accepted;
    # the reported block size follows values, the shape follows size.
    odd_values = torch.randn(2, 3, 3, device=dev)
    ref = ref_size(
        utils.to_reference(crow),
        utils.to_reference(col),
        utils.to_reference(odd_values),
        [4, 4],
    )
    res = gems_size(crow, col, odd_values, [4, 4])
    assert tuple(res.shape) == (4, 4)
    assert tuple(res.values().shape[-2:]) == (3, 3)
    assert _meta(res) == _meta(ref)


def _foreign_device(t):
    """A device guaranteed to differ from ``t``'s own device."""
    if t.device.type == "cpu":
        return torch.device(flag_gems.device)
    return torch.device("cpu")


@pytest.mark.sparse_bsr_tensor
def test_sparse_bsr_tensor_requires_explicit_device_for_cuda_components():
    # The packet overloads build the sparse tensor on the `device=` argument
    # (TensorOptions default when it is None) and then assert every member
    # shares it. With CUDA components and device=None that assertion fails on
    # BOTH sides; passing the components' own device succeeds on both. This is
    # the reason every other test passes `device` explicitly, and it is a
    # measured native difference from the Python builtin (whose C++ argument
    # parser derives the device from `values`).
    # Both sides deliberately use the SAME component tensors here (no
    # utils.to_reference): the contract under test is device/dtype-specific,
    # and mirroring it against a separately converted pair would change the
    # device in the --ref=cpu phase and silently stop exercising the branch.
    # Both sides deliberately use the SAME component tensors here (no
    # utils.to_reference): the contract under test is device/dtype-specific,
    # and mirroring it against a separately converted pair would change the
    # device in the --ref=cpu phase and silently stop exercising the branch.
    dev = flag_gems.device
    crow, col, values, size = _make_components(2, 2, 2, 2, 20, dev)
    with pytest.raises(RuntimeError) as ref_exc:
        torch.ops.aten.sparse_bsr_tensor.crow_col_value_size(
            crow, col, values, list(size), dtype=values.dtype
        )
    with pytest.raises(RuntimeError) as res_exc:
        flag_gems.sparse_bsr_tensor_crow_col_value_size(
            crow, col, values, list(size), dtype=values.dtype
        )
    assert str(res_exc.value) == str(ref_exc.value)
    assert "same device" in str(ref_exc.value)

    # With the device supplied, both sides agree. The reference components are
    # converted here, so this half of the test is device-agnostic.
    assert _meta(gems_size(crow, col, values, list(size))) == _meta(
        ref_size(
            utils.to_reference(crow),
            utils.to_reference(col),
            utils.to_reference(values),
            list(size),
        )
    )


@pytest.mark.sparse_bsr_tensor
def test_sparse_bsr_tensor_requires_explicit_dtype_for_non_float32_values():
    # Same shape of contract for the dtype: the packet overloads default the
    # target dtype to float32, so any values tensor of another dtype is
    # rejected unless `dtype=` is passed. The builtin derives it from values.
    # Both sides use the same components for the reason stated above.
    dev = flag_gems.device
    crow, col, values, size = _make_components(
        2, 2, 2, 2, 21, dev, value_dtype=torch.float64
    )
    with pytest.raises(RuntimeError) as ref_exc:
        torch.ops.aten.sparse_bsr_tensor.crow_col_value_size(
            crow, col, values, list(size), device=values.device
        )
    with pytest.raises(RuntimeError) as res_exc:
        flag_gems.sparse_bsr_tensor_crow_col_value_size(
            crow, col, values, list(size), device=values.device
        )
    assert str(res_exc.value) == str(ref_exc.value)
    assert "dtype of values" in str(ref_exc.value)
    assert "Double" in str(ref_exc.value)

    # Supplying the matching dtype makes both sides succeed.
    res = gems_size(crow, col, values, list(size))
    ref = ref_size(
        utils.to_reference(crow),
        utils.to_reference(col),
        utils.to_reference(values),
        list(size),
    )
    assert res.dtype == torch.float64
    assert _meta(res) == _meta(ref)


@pytest.mark.sparse_bsr_tensor
def test_sparse_bsr_tensor_explicit_size_dtype_and_device_kwargs():
    # `dtype` must agree with values; `device` must agree with the components
    # (the native wiring asserts all members live on the same device). The
    # device kwarg is derived from the ALREADY-CONVERTED component so the test
    # stays valid in the --ref=cpu phase, where the reference components are
    # CPU tensors.
    dev = flag_gems.device
    crow, col, values, size = _make_components(2, 2, 2, 2, 15, dev)
    ref_crow = utils.to_reference(crow)
    ref_col = utils.to_reference(col)
    ref_values = utils.to_reference(values)
    ref = ref_size(
        ref_crow,
        ref_col,
        ref_values,
        list(size),
        dtype=torch.float32,
        layout=torch.sparse_bsr,
        device=ref_values.device,
    )
    res = gems_size(
        crow,
        col,
        values,
        list(size),
        dtype=torch.float32,
        layout=torch.sparse_bsr,
        device=torch.device(dev),
    )
    assert _meta(res) == _meta(ref)
    assert res.device.type == torch.device(dev).type


@pytest.mark.sparse_bsr_tensor
def test_sparse_bsr_tensor_error_parity():
    # Every rejection class must raise the same exception class as native with
    # the semantic parameters of the failure present in the message. The full
    # sentence is compared when both sides raise from the same validator;
    # fragments are used otherwise (see the class comments).
    dev = flag_gems.device
    crow, col, values, size = _make_components(2, 2, 2, 2, 16, dev)

    # (label, gems_fn, ref_fn, fragments). The fragments name the parameters
    # of the failure rather than one build's sentence structure.
    cases = [
        (
            "wrong explicit layout",
            lambda: gems_size(crow, col, values, size, layout=torch.strided),
            lambda: ref_size(
                utils.to_reference(crow),
                utils.to_reference(col),
                utils.to_reference(values),
                list(size),
                layout=torch.strided,
            ),
            ["SparseBsr", "Strided"],
        ),
        (
            "wrong inference layout",
            lambda: gems_infer(crow, col, values, layout=torch.sparse_csr),
            lambda: ref_infer(
                utils.to_reference(crow),
                utils.to_reference(col),
                utils.to_reference(values),
                layout=torch.sparse_csr,
            ),
            ["SparseBsr", "SparseCsr"],
        ),
        (
            "dtype disagrees with values",
            lambda: gems_size(crow, col, values, size, dtype=torch.int64),
            lambda: ref_size(
                utils.to_reference(crow),
                utils.to_reference(col),
                utils.to_reference(values),
                list(size),
                dtype=torch.int64,
            ),
            ["dtype of values", "Long"],
        ),
        (
            "crow_indices 0-dim (inference)",
            lambda: gems_infer(
                torch.tensor(1, device=dev),
                torch.tensor(1, device=dev),
                torch.randn(1, 2, 2, device=dev),
            ),
            lambda: ref_infer(
                torch.tensor(1, device=dev),
                torch.tensor(1, device=dev),
                torch.randn(1, 2, 2, device=dev),
            ),
            ["crow_indices", "dimensionality", "0"],
        ),
        (
            "crow/col rank mismatch (inference)",
            lambda: gems_infer(
                torch.ones(2, 3, dtype=torch.int64, device=dev),
                col,
                torch.randn(2, 2, 2, device=dev),
            ),
            lambda: ref_infer(
                torch.ones(2, 3, dtype=torch.int64, device=dev),
                col,
                torch.randn(2, 2, 2, device=dev),
            ),
            ["crow_indices", "col_indices", "dimensionalities", "2", "1"],
        ),
        (
            "values rank too small (inference)",
            lambda: gems_infer(crow, col, torch.randn(2, 4, device=dev)),
            lambda: ref_infer(
                utils.to_reference(crow),
                utils.to_reference(col),
                torch.randn(2, 4, device=dev),
            ),
            ["values", "dimensionality", "2"],
        ),
        (
            "non-integral col_indices (inference)",
            lambda: gems_infer(crow, torch.ones(2, device=dev), values),
            lambda: ref_infer(
                utils.to_reference(crow),
                torch.ones(2, device=dev),
                utils.to_reference(values),
            ),
            ["estimate_sparse_compressed_tensor_size", "Float"],
        ),
        (
            "negative explicit size",
            lambda: gems_size(crow, col, values, [-4, 4]),
            lambda: ref_size(
                utils.to_reference(crow),
                utils.to_reference(col),
                utils.to_reference(values),
                [-4, 4],
            ),
            ["overflow"],
        ),
    ]
    for label, gems_fn, ref_fn, fragments in cases:
        with pytest.raises(RuntimeError) as ref_exc:
            ref_fn()
        with pytest.raises(RuntimeError) as res_exc:
            gems_fn()
        ref_msg = str(ref_exc.value)
        res_msg = str(res_exc.value)
        same = ref_msg == res_msg
        frags_ok = all(f in ref_msg for f in fragments) and all(
            f in res_msg for f in fragments
        )
        assert same or frags_ok, (
            f"{label}: gems={res_msg!r} ref={ref_msg!r} "
            f"(expected identical messages, or fragments {fragments} on both sides)"
        )


@pytest.mark.sparse_bsr_tensor
def test_sparse_bsr_tensor_error_message_equality():
    # Stronger than the matcher above: for the classes whose message comes from
    # the same validator on both paths, the full native message must match
    # character for character. The layout, dtype and device classes are raised
    # by the bsr-named native wiring and the impl's mirror of it, so they
    # belong here too; the size-estimator classes are compared in the parity
    # test because their wording depends on the dispatch-macro path.
    dev = flag_gems.device
    crow, col, values, size = _make_components(2, 2, 2, 2, 17, dev)

    # Each side's "foreign" device is derived from its OWN components, so the
    # device-mismatch case points away from the device the call actually runs
    # on in both phases (GPU in the full phase, CPU under --ref=cpu).
    ref_crow = utils.to_reference(crow)
    ref_col = utils.to_reference(col)
    ref_values = utils.to_reference(values)
    gems_foreign = _foreign_device(values)
    ref_foreign = _foreign_device(ref_values)

    for label, kw_gems, kw_ref in [
        (
            "layout=stride (explicit)",
            {"layout": torch.strided},
            {"layout": torch.strided},
        ),
        (
            "layout=sparse_bsc (explicit)",
            {"layout": torch.sparse_bsc},
            {"layout": torch.sparse_bsc},
        ),
        (
            "dtype disagrees with values (explicit)",
            {"dtype": torch.int64},
            {"dtype": torch.int64},
        ),
        (
            "home device mismatch (explicit)",
            {"device": gems_foreign},
            {"device": ref_foreign},
        ),
    ]:
        with pytest.raises(RuntimeError) as ref_exc:
            ref_size(ref_crow, ref_col, ref_values, list(size), **kw_ref)
        with pytest.raises(RuntimeError) as res_exc:
            flag_gems.sparse_bsr_tensor_crow_col_value_size(
                crow, col, values, list(size), **kw_gems
            )
        assert str(res_exc.value) == str(
            ref_exc.value
        ), f"{label}\n  gems: {res_exc.value}\n  ref : {ref_exc.value}"


@pytest.mark.sparse_bsr_tensor
def test_sparse_bsr_tensor_matches_reference_table():
    # Reference metadata captured in a process that never imported flag_gems
    # (native_probe_e.log), pinned as literals so a silent semantic drift shows
    # up even if the harness changes.
    dev = flag_gems.device
    crow = torch.tensor([0, 1, 2], dtype=torch.int64, device=dev)
    col = torch.tensor([0, 1], dtype=torch.int64, device=dev)
    values = torch.arange(8.0, device=dev).reshape(2, 2, 2)

    explicit = gems_size(crow, col, values, [4, 4])
    assert tuple(explicit.shape) == (4, 4)
    assert explicit.dtype == torch.float32
    assert explicit.layout == torch.sparse_bsr
    assert explicit._nnz() == 2
    assert explicit.sparse_dim() == 2
    assert explicit.dense_dim() == 0
    assert tuple(explicit.values().shape) == (2, 2, 2)
    assert tuple(explicit.values().shape[-2:]) == (2, 2)
    assert explicit.crow_indices().tolist() == [0, 1, 2]
    assert explicit.col_indices().tolist() == [0, 1]

    inferred = gems_infer(crow, col, values)
    assert tuple(inferred.shape) == (4, 4)
    assert inferred._nnz() == 2

    # values.shape[-2:] drives the inferred block shape: 3x3 blocks over a
    # 1-block-row grid give a (3, 6) tensor.
    crow3 = torch.tensor([0, 1], dtype=torch.int64, device=dev)
    values3 = torch.randn(1, 3, 3, device=dev)
    odd = gems_infer(crow3, col[:1], values3)
    assert tuple(odd.shape) == (3, 3)
    assert tuple(odd.values().shape[-2:]) == (3, 3)


@pytest.mark.sparse_bsr_tensor
def test_sparse_bsr_tensor_repeated_dispatch():
    # Repeated dispatcher-routed calls must be stable: no recursion (the
    # implementation delegates to aten::_sparse_bsr_tensor_unsafe, never to the
    # overload it implements) and no cross-call state.
    dev = flag_gems.device
    crow, col, values, size = _make_components(2, 2, 2, 2, 18, dev)
    for _ in range(5):
        r1 = gems_size(crow, col, values, list(size))
        assert r1._nnz() == int(crow[-1].item())
        r2 = gems_infer(crow, col, values)
        assert tuple(r2.shape) == (4, 4)
        # An unrelated dispatch in between must not re-route the constructors.
        assert torch.ops.aten._nnz(r1) == r1._nnz()
        assert gems_size(crow, col, values, list(size))._nnz() == r1._nnz()


@pytest.mark.sparse_bsr_tensor
def test_sparse_bsr_tensor_dispatch_sentinel():
    # Registration-path check: a sentinel on the key this operator registers on
    # must intercept the packet calls, proving the shipped implementation is
    # what executes rather than the native kernel.
    #
    # Measured reachability, one subset per fresh process (native_probe_c_matrix
    # .log, _d_matrix.log, _f.log, _k.log). Both overloads are composite
    # constructors with no backend kernel, and the dispatcher walks the
    # Autograd key before any composite key, so:
    #   - the Autograd key ALONE is never selected (the key is not in the
    #     arguments' keyset until a backend kernel is found);
    #   - the device key alone is selected only by the packet form that omits
    #     both layout and device;
    #   - the device key AND the Autograd key together catch every form --
    #     which is exactly the pair _FULL_CONFIG registers.
    # So the sentinel below mirrors the shipped arrangement (CUDA + Autograd)
    # rather than the Autograd key alone. The Python builtin
    # torch.sparse_bsr_tensor does NOT route through either overload (its C++
    # argument parser calls the shared
    # sparse_compressed_tensor.comp_plain_value[_size] op, owned by the
    # sparse_compressed_tensor integration), so the builtin is deliberately not
    # asserted on here.
    dev = flag_gems.device
    crow, col, values, size = _make_components(2, 2, 2, 2, 19, dev)
    lib = torch.library.Library("aten", "IMPL")
    hits = []

    def sentinel_size(crow_indices, col_indices, vals, sz, **kwargs):
        hits.append("size")
        return flag_gems.sparse_bsr_tensor_crow_col_value_size(
            crow_indices, col_indices, vals, sz, **kwargs
        )

    def sentinel_nosize(crow_indices, col_indices, vals, **kwargs):
        hits.append("nosize")
        return flag_gems.sparse_bsr_tensor_crow_col_value(
            crow_indices, col_indices, vals, **kwargs
        )

    try:
        for key in (flag_gems.backend_info.dispatch_key, "Autograd"):
            lib.impl("sparse_bsr_tensor.crow_col_value_size", sentinel_size, key)
            lib.impl("sparse_bsr_tensor.crow_col_value", sentinel_nosize, key)

        # (a) the packet form that omits layout and device is caught by the
        #     DEVICE key. It then fails the same-device check, exactly as the
        #     native path does -- reaching that check at all proves the
        #     sentinel ran, so the assertion is on the sentinel hit, not on a
        #     successful construction.
        with pytest.raises(RuntimeError, match="same device"):
            torch.ops.aten.sparse_bsr_tensor.crow_col_value(crow, col, values)
        assert hits.count("nosize") >= 1, hits

        # (b) the forms that supply layout/device are caught by Autograd.
        assert torch.ops.aten.sparse_bsr_tensor.crow_col_value_size(
            crow, col, values, list(size), device=torch.device(dev)
        )._nnz() == int(crow[-1].item())
        assert torch.ops.aten.sparse_bsr_tensor.crow_col_value(
            crow, col, values, device=torch.device(dev)
        )._nnz() == int(crow[-1].item())
        assert hits.count("size") >= 1, hits
        assert hits.count("nosize") >= 2, hits
    finally:
        lib._destroy()

    # After destroying the sentinel the routed path is native again and still
    # agrees with the submitted implementation.
    assert torch.ops.aten.sparse_bsr_tensor.crow_col_value_size(
        crow, col, values, list(size), device=torch.device(dev)
    )._nnz() == int(crow[-1].item())
    assert gems_size(crow, col, values, list(size))._nnz() == int(crow[-1].item())


@pytest.mark.sparse_bsr_tensor
def test_sparse_bsr_tensor_enabled_registration_reaches_the_impl():
    # End-to-end routing proof on the PRODUCTION registration arrangement:
    # flag_gems.enable() registers _FULL_CONFIG exactly as a user would trigger
    # it, then poisoning the delegate that the implementation calls proves the
    # shipped code -- not a native kernel -- is what executes for every packet
    # call form. Measured in native_probe_k.log ("ROUTED INTO OUR IMPL" on all
    # six forms).
    dev = flag_gems.device
    crow, col, values, size = _make_components(2, 2, 2, 2, 22, dev)
    flag_gems.enable()

    original = torch.ops.aten._sparse_bsr_tensor_unsafe

    def poison(*args, **kwargs):
        raise RuntimeError("POISON-UNSAFE")

    forms = [
        (
            "size, device only",
            lambda: torch.ops.aten.sparse_bsr_tensor.crow_col_value_size(
                crow, col, values, list(size), device=torch.device(dev)
            ),
        ),
        (
            "size, layout+device",
            lambda: torch.ops.aten.sparse_bsr_tensor.crow_col_value_size(
                crow,
                col,
                values,
                list(size),
                layout=torch.sparse_bsr,
                device=torch.device(dev),
            ),
        ),
        (
            "size, bare",
            lambda: torch.ops.aten.sparse_bsr_tensor.crow_col_value_size(
                crow, col, values, list(size)
            ),
        ),
        (
            "infer, device only",
            lambda: torch.ops.aten.sparse_bsr_tensor.crow_col_value(
                crow, col, values, device=torch.device(dev)
            ),
        ),
        (
            "infer, layout+device",
            lambda: torch.ops.aten.sparse_bsr_tensor.crow_col_value(
                crow,
                col,
                values,
                layout=torch.sparse_bsr,
                device=torch.device(dev),
            ),
        ),
        (
            "infer, bare",
            lambda: torch.ops.aten.sparse_bsr_tensor.crow_col_value(crow, col, values),
        ),
    ]
    try:
        torch.ops.aten._sparse_bsr_tensor_unsafe = poison
        for label, fn in forms:
            with pytest.raises(RuntimeError, match="POISON-UNSAFE"):
                fn()
    finally:
        torch.ops.aten._sparse_bsr_tensor_unsafe = original

    # Health after the poison is removed: the routed path is still correct.
    res = torch.ops.aten.sparse_bsr_tensor.crow_col_value_size(
        crow, col, values, list(size), device=torch.device(dev)
    )
    assert res._nnz() == int(crow[-1].item())
    assert _meta(res) == _meta(gems_size(crow, col, values, list(size)))
