# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import pytest
import torch
from _pytest.mark.structures import Mark, MarkDecorator

import flag_gems

from . import accuracy_utils as utils
from .conftest import QUICK_MODE

# ``_fw_primal_copy`` starts with an underscore, and ``pytest.mark`` refuses
# to generate a marker via attribute access for such names. Register the
# markers directly on the MarkGenerator so ``@pytest.mark._fw_primal_copy``
# and ``-m _fw_primal_copy`` both work.
setattr(
    pytest.mark,
    "_fw_primal_copy",
    MarkDecorator(Mark("_fw_primal_copy", (), {}, _ispytest=True), _ispytest=True),
)
setattr(
    pytest.mark,
    "_fw_primal_copy_out",
    MarkDecorator(Mark("_fw_primal_copy_out", (), {}, _ispytest=True), _ispytest=True),
)

# Shape sweep: 1-D sizes plus a 2-D square, covering the flat kernel and its
# element-size tuning table.
FW_PRIMAL_COPY_SHAPES = [(1024,), (65536,), (1024, 1024)]
if QUICK_MODE:
    FW_PRIMAL_COPY_SHAPES = [(1024,), (1024, 1024)]

# The dtype sweep drives the element-size branches of the flat kernel's
# tuning table (1/2/4/8 bytes) as well as the value-preservation contract.
# Native accepts every one of these on H20 (measured); complex64/128 are
# 8/16-byte and take the same final branch as fp64/int64.
FW_PRIMAL_COPY_DTYPES = [
    torch.float16,
    torch.float32,
    torch.bfloat16,
    torch.int16,
    torch.int32,
    torch.int64,
    torch.bool,
]
if QUICK_MODE:
    FW_PRIMAL_COPY_DTYPES = [torch.float32, torch.int16, torch.int32, torch.bool]


def _gen(shape, dtype, device):
    if dtype.is_floating_point:
        return torch.randn(shape, dtype=dtype, device=device)
    if dtype == torch.bool:
        return torch.randint(0, 2, size=shape, dtype=dtype, device=device)
    lo, hi = torch.iinfo(dtype).min, torch.iinfo(dtype).max
    return torch.randint(lo, hi, shape, dtype=dtype, device=device)


def _native_copy(inp, level):
    """Call the native operator on an equivalent inference tensor.

    Measured on H20: the native composite is generated for ``view_copy`` and
    its body asserts ``InferenceMode::is_enabled() && self.is_inference()``,
    so outside ``torch.inference_mode()`` it raises ``RuntimeError``. Every
    reference call therefore runs under ``inference_mode`` on an inference
    copy of the input; the copy is made from the already-converted reference
    tensor so a single conversion serves both the call and any metadata
    assertion (under ``--ref=cpu`` each ``to_reference`` allocates afresh).
    """
    with torch.inference_mode():
        return torch.ops.aten._fw_primal_copy(inp.clone(), level)


def _native_copy_out(ref_inp, level, shape):
    """Native ``_fw_primal_copy.out`` on an inference tensor of ``shape``.

    The native out composite asserts inference mode as well (measured: it
    raises for every inference-ness combination when called outside the
    context), so input and buffer are created and the call is made inside
    ``inference_mode``.
    """
    with torch.inference_mode():
        buffer = torch.empty(shape, dtype=ref_inp.dtype, device=ref_inp.device)
        return torch.ops.aten._fw_primal_copy.out(ref_inp.clone(), level, out=buffer)


def _assert_copy_contract(res, inp):
    """Assert the fresh-copy contract shared by every native path.

    Native ``_fw_primal_copy`` returns a newly allocated tensor: a different
    ``data_ptr``, no view base, and the input's shape and dtype.
    """
    assert res.shape == inp.shape
    assert res.dtype == inp.dtype
    assert res.data_ptr() != inp.data_ptr()
    assert res._base is None


@pytest.mark._fw_primal_copy
@pytest.mark.parametrize("dtype", FW_PRIMAL_COPY_DTYPES)
@pytest.mark.parametrize("shape", FW_PRIMAL_COPY_SHAPES)
def test_accuracy__fw_primal_copy_contiguous(shape, dtype):
    inp = _gen(shape, dtype, flag_gems.device)
    assert inp.is_contiguous()
    # One conversion, reused for the reference call and the comparisons.
    ref_inp = utils.to_reference(inp)

    ref_out = _native_copy(ref_inp, 0)
    res_out = flag_gems._fw_primal_copy(inp, 0)

    # Native first: the fresh-copy contract is verified, not assumed.
    _assert_copy_contract(ref_out, ref_inp)
    _assert_copy_contract(res_out, inp)
    assert res_out.is_contiguous() == ref_out.is_contiguous()
    assert res_out.stride() == ref_out.stride()
    utils.gems_assert_equal(res_out, ref_out)
    utils.gems_assert_equal(res_out, ref_inp)
    utils.gems_assert_equal(res_out, inp)


@pytest.mark._fw_primal_copy
@pytest.mark.parametrize(
    "slicer",
    [(slice(None), slice(None, None, 2)), (slice(None), slice(1, 7, 3))],
)
def test_accuracy__fw_primal_copy_non_contiguous(slicer):
    # ``x[:, ::2]``-style strided inputs exercise the strided kernel: it must
    # gather by the input's shape/stride table and materialize a contiguous
    # result, matching native.
    base = torch.randn(4, 8, device=flag_gems.device)
    inp = base[slicer]
    # The strided branch must actually be exercised.
    assert not inp.is_contiguous()

    # Convert the base once and re-derive the view from it: converting the
    # strided view itself would materialize a contiguous copy on CPU and lose
    # the strides this test exercises.
    ref_base = utils.to_reference(base)
    ref_inp = ref_base[slicer]

    ref_out = _native_copy(ref_inp, 0)
    res_out = flag_gems._fw_primal_copy(inp, 0)

    _assert_copy_contract(ref_out, ref_inp)
    _assert_copy_contract(res_out, inp)
    # Native materializes a CONTIGUOUS copy of a strided input.
    assert ref_out.is_contiguous()
    assert res_out.is_contiguous()
    assert res_out.stride() == ref_out.stride()
    utils.gems_assert_equal(res_out, ref_out)
    utils.gems_assert_equal(res_out, inp)


@pytest.mark._fw_primal_copy
@pytest.mark.parametrize(
    "make_input",
    [
        lambda: torch.randn(6, 4, device=flag_gems.device).t(),
        lambda: torch.randn(4, 6, 8, device=flag_gems.device).permute(2, 0, 1),
        lambda: torch.randn(1, 6, device=flag_gems.device).expand(4, 6),
        lambda: torch.randn(100, device=flag_gems.device).as_strided((4, 6), (12, 2)),
        lambda: torch.randn(4, 6, 8, device=flag_gems.device)[:, ::2, :],
    ],
)
def test_accuracy__fw_primal_copy_strided_layouts(make_input):
    # Transposes, permutations, zero-stride expansions and as_strided views
    # all take the strided branch and must produce the same contiguous values
    # as native.
    inp = make_input()
    assert not inp.is_contiguous()

    ref_inp = utils.to_reference(inp)
    ref_out = _native_copy(ref_inp, 0)
    res_out = flag_gems._fw_primal_copy(inp, 0)

    _assert_copy_contract(res_out, inp)
    assert res_out.is_contiguous()
    assert ref_out.is_contiguous()
    assert res_out.stride() == ref_out.stride()
    utils.gems_assert_equal(res_out, ref_out)
    utils.gems_assert_equal(res_out, inp)


@pytest.mark._fw_primal_copy
def test_accuracy__fw_primal_copy_zero_stride_expand():
    # A stride-0 dim means several output elements read the SAME source
    # element; the gather must reproduce that, not read neighbour values.
    inp = torch.randn(1, 5, device=flag_gems.device).expand(4, 5)
    assert inp.stride() == (0, 1)
    ref_inp = utils.to_reference(inp)

    ref_out = _native_copy(ref_inp, 0)
    res_out = flag_gems._fw_primal_copy(inp, 0)

    assert res_out.shape == (4, 5)
    utils.gems_assert_equal(res_out, ref_out)
    # Every expanded row equals the single source row.
    for row in res_out:
        assert torch.equal(row, res_out[0])


@pytest.mark._fw_primal_copy
def test_accuracy__fw_primal_copy_empty():
    # Empty 1-D tensor: the grid would be (0,), short-circuited before launch.
    inp = torch.empty(0, device=flag_gems.device)
    ref_inp = utils.to_reference(inp)
    ref_out = _native_copy(ref_inp, 0)
    res_out = flag_gems._fw_primal_copy(inp, 0)

    assert res_out.shape == (0,)
    assert res_out.numel() == 0
    assert ref_out.numel() == 0
    utils.gems_assert_equal(res_out, ref_out)


@pytest.mark._fw_primal_copy
@pytest.mark.parametrize("shape", [(0, 4), (4, 0), (0, 0)])
def test_accuracy__fw_primal_copy_empty_shapes(shape):
    # Multi-dim empty tensors: shape must survive even though no element is
    # copied, on both the flat and the strided path.
    inp = torch.empty(shape, device=flag_gems.device)
    ref_inp = utils.to_reference(inp)
    ref_out = _native_copy(ref_inp, 0)
    res_out = flag_gems._fw_primal_copy(inp, 0)

    assert res_out.shape == shape
    assert res_out.numel() == 0
    assert ref_out.shape == shape
    utils.gems_assert_equal(res_out, ref_out)


@pytest.mark._fw_primal_copy
def test_accuracy__fw_primal_copy_empty_non_contiguous():
    # A transposed empty tensor is "contiguous" only by ATen's degenerate
    # stride rules; exercise the empty guard on a genuinely strided-empty
    # input as well (numel == 0 on the strided path).
    base = torch.empty(4, 0, device=flag_gems.device)
    inp = base.transpose(0, 1)
    assert inp.numel() == 0
    ref_inp = utils.to_reference(inp)
    ref_out = _native_copy(ref_inp, 0)
    res_out = flag_gems._fw_primal_copy(inp, 0)

    assert res_out.shape == inp.shape
    assert res_out.numel() == 0
    utils.gems_assert_equal(res_out, ref_out)


@pytest.mark._fw_primal_copy
def test_accuracy__fw_primal_copy_zero_dim():
    inp = torch.randn((), device=flag_gems.device)
    ref_inp = utils.to_reference(inp)
    ref_out = _native_copy(ref_inp, 0)
    res_out = flag_gems._fw_primal_copy(inp, 0)

    assert res_out.shape == ()
    assert res_out.numel() == 1
    _assert_copy_contract(res_out, inp)
    utils.gems_assert_equal(res_out, ref_out)
    utils.gems_assert_equal(res_out, inp)


@pytest.mark._fw_primal_copy
def test_accuracy__fw_primal_copy_single_element():
    inp = torch.randn(1, device=flag_gems.device)
    ref_inp = utils.to_reference(inp)
    ref_out = _native_copy(ref_inp, 0)
    res_out = flag_gems._fw_primal_copy(inp, 0)

    _assert_copy_contract(res_out, inp)
    utils.gems_assert_equal(res_out, ref_out)


@pytest.mark._fw_primal_copy
def test_accuracy__fw_primal_copy_is_a_copy_not_a_view():
    # The contract that separates this op from its _fw_primal sibling:
    # writes through the result must NOT be visible in the input and vice
    # versa, because the values live in freshly allocated storage.
    inp = torch.randn(4, 8, device=flag_gems.device)
    res_out = flag_gems._fw_primal_copy(inp, 0)
    res_out.fill_(3.5)
    assert not torch.any(inp == 3.5).item()

    inp2 = torch.randn(4, 8, device=flag_gems.device)
    res2 = flag_gems._fw_primal_copy(inp2, 0)
    inp2.fill_(-1.0)
    assert not torch.any(res2 == -1.0).item()

    # And for the strided path.
    base = torch.randn(4, 8, device=flag_gems.device)
    strided = base[:, ::2]
    res3 = flag_gems._fw_primal_copy(strided, 0)
    assert res3.data_ptr() != strided.data_ptr()
    res3.fill_(7.0)
    assert not torch.any(strided == 7.0).item()


@pytest.mark._fw_primal_copy
@pytest.mark.parametrize("level", [0, 1, -1, 7, 100, 2**31 - 1])
def test_accuracy__fw_primal_copy_levels(level):
    # Native returns the same fresh copy for every level on a non-dual input;
    # mirror exactly what it does, including for out-of-range levels, which
    # are accepted verbatim.
    inp = torch.randn(3, 4, device=flag_gems.device)
    # One conversion, reused for the reference call and the comparisons.
    ref_inp = utils.to_reference(inp)
    ref_out = _native_copy(ref_inp, level)
    res_out = flag_gems._fw_primal_copy(inp, level)

    _assert_copy_contract(ref_out, ref_inp)
    _assert_copy_contract(res_out, inp)
    utils.gems_assert_equal(res_out, ref_out)

    # Same for a strided input: the level must not change the fallback path.
    base = torch.randn(4, 8, device=flag_gems.device)
    inp_nc = base[:, ::2]
    ref_base = utils.to_reference(base)
    ref_nc = ref_base[:, ::2]
    res_nc = flag_gems._fw_primal_copy(inp_nc, level)
    assert res_nc.is_contiguous()
    assert res_nc.data_ptr() != inp_nc.data_ptr()
    utils.gems_assert_equal(res_nc, _native_copy(ref_nc, level))


@pytest.mark._fw_primal_copy
def test_accuracy__fw_primal_copy_dispatch_stability():
    # Repeated calls plus unrelated aten ops in between must keep producing a
    # fresh, correct copy (no shared mutable state, no dispatch drift).
    inp = torch.randn(3, 4, device=flag_gems.device)
    ref_inp = utils.to_reference(inp)
    for _ in range(3):
        assert torch.ops.aten.dim(inp) == 2
        assert torch.ops.aten.numel(inp) == 12
        res_out = flag_gems._fw_primal_copy(inp, 0)
        assert res_out.data_ptr() != inp.data_ptr()
        assert res_out.shape == inp.shape
        utils.gems_assert_equal(res_out, _native_copy(ref_inp, 0))


@pytest.mark._fw_primal_copy
def test_accuracy__fw_primal_copy_repeated_calls_do_not_alias():
    # Two successive calls must not hand back the same buffer: each result is
    # a fresh allocation (a reused output buffer would still compare equal,
    # so the pointers are checked).
    inp = torch.randn(64, device=flag_gems.device)
    first = flag_gems._fw_primal_copy(inp, 0)
    second = flag_gems._fw_primal_copy(inp, 0)
    assert first.data_ptr() != inp.data_ptr()
    assert second.data_ptr() != inp.data_ptr()
    assert first.data_ptr() != second.data_ptr()


@pytest.mark._fw_primal_copy
@pytest.mark.parametrize("dtype", FW_PRIMAL_COPY_DTYPES)
def test_accuracy__fw_primal_copy_dtype_dispatch(dtype):
    # The op must not depend on element type: no promotion, no cast. This
    # also drives the flat kernel's element-size branch table.
    inp = _gen((1024,), dtype, flag_gems.device)
    ref_inp = utils.to_reference(inp)
    ref_out = _native_copy(ref_inp, 0)
    res_out = flag_gems._fw_primal_copy(inp, 0)

    assert res_out.dtype == ref_inp.dtype == ref_out.dtype
    _assert_copy_contract(res_out, inp)
    utils.gems_assert_equal(res_out, inp)


@pytest.mark._fw_primal_copy
def test_accuracy__fw_primal_copy_matches_primed_clone():
    # The native composite is ``_fw_primal(self, level).clone(Contiguous)``;
    # for a non-dual input the first hop is an aliasing view, so the whole op
    # is equivalent to a contiguous clone of the input. Verify the submitted
    # implementation against that independent formulation of the contract.
    inp = torch.randn(4, 7, device=flag_gems.device)
    assert flag_gems._fw_primal_copy(inp, 0).data_ptr() != inp.data_ptr()
    utils.gems_assert_equal(
        flag_gems._fw_primal_copy(inp, 0),
        inp.clone(memory_format=torch.contiguous_format),
    )

    strided = torch.randn(4, 8, device=flag_gems.device)[:, ::2]
    res_strided = flag_gems._fw_primal_copy(strided, 1)
    utils.gems_assert_equal(
        res_strided, strided.clone(memory_format=torch.contiguous_format)
    )


# ---------------------------------------------------------------------------
# The ``.out`` overload
# ---------------------------------------------------------------------------


@pytest.mark._fw_primal_copy_out
def test_accuracy__fw_primal_copy_out_writes_and_returns_out():
    inp = torch.randn(4, 6, device=flag_gems.device)
    out = torch.zeros(4, 6, device=flag_gems.device)
    ref_inp = utils.to_reference(inp)

    ref_out = _native_copy_out(ref_inp, 0, (4, 6))
    res = flag_gems._fw_primal_copy_out(inp, 0, out=out)

    # Identity: the caller's buffer itself is returned, not a fresh tensor.
    assert res is out
    # The buffer really was written (it started as zeros).
    assert torch.equal(out, inp)
    utils.gems_assert_equal(out, ref_out)
    # A distinct allocation from the input.
    assert out.data_ptr() != inp.data_ptr()
    assert ref_out.data_ptr() != ref_inp.data_ptr()


@pytest.mark._fw_primal_copy_out
def test_accuracy__fw_primal_copy_out_from_non_contiguous_input():
    base = torch.randn(4, 8, device=flag_gems.device)
    inp = base[:, ::2]
    assert not inp.is_contiguous()
    out = torch.zeros(4, 4, device=flag_gems.device)
    ref_inp = utils.to_reference(base)[:, ::2]

    ref_out = _native_copy_out(ref_inp, 0, (4, 4))
    res = flag_gems._fw_primal_copy_out(inp, 0, out=out)

    assert res is out
    assert out.is_contiguous()
    utils.gems_assert_equal(out, ref_out)
    utils.gems_assert_equal(out, inp)


@pytest.mark._fw_primal_copy_out
def test_accuracy__fw_primal_copy_out_non_contiguous_buffer():
    # An out buffer with its own strides must receive the values in ITS layout
    # (the strided staging path scatters back), and the same buffer is
    # returned.
    inp = torch.randn(4, 6, device=flag_gems.device)
    out = torch.zeros(6, 4, device=flag_gems.device).t()
    assert not out.is_contiguous()
    ref_inp = utils.to_reference(inp)

    ref_out = _native_copy_out(ref_inp, 0, (4, 6))
    res = flag_gems._fw_primal_copy_out(inp, 0, out=out)

    assert res is out
    assert out.stride() == (1, 6)
    utils.gems_assert_equal(out, ref_out)


@pytest.mark._fw_primal_copy_out
@pytest.mark.parametrize("bad_shape", [(3, 9), (0,), (24,)])
def test_accuracy__fw_primal_copy_out_resizes_mismatched_buffer(bad_shape):
    # Native resizes the buffer to the input shape (a deprecated-but-current
    # behaviour, warning included) and still returns the same object.
    inp = torch.randn(4, 6, device=flag_gems.device)
    out = torch.zeros(bad_shape, device=flag_gems.device)
    ref_inp = utils.to_reference(inp)

    ref_out = _native_copy_out(ref_inp, 0, bad_shape)
    assert ref_out.shape == (4, 6)

    res = flag_gems._fw_primal_copy_out(inp, 0, out=out)
    assert res is out
    assert out.shape == (4, 6)
    utils.gems_assert_equal(out, ref_out)


@pytest.mark._fw_primal_copy_out
def test_accuracy__fw_primal_copy_out_empty_input():
    inp = torch.empty(0, device=flag_gems.device)
    out = torch.zeros(0, device=flag_gems.device)
    ref_inp = utils.to_reference(inp)

    ref_out = _native_copy_out(ref_inp, 0, (0,))
    res = flag_gems._fw_primal_copy_out(inp, 0, out=out)

    assert res is out
    assert out.numel() == 0
    utils.gems_assert_equal(out, ref_out)


@pytest.mark._fw_primal_copy_out
@pytest.mark.parametrize("level", [0, 1, -1])
def test_accuracy__fw_primal_copy_out_levels(level):
    inp = torch.randn(4, 6, device=flag_gems.device)
    out = torch.zeros(4, 6, device=flag_gems.device)
    ref_inp = utils.to_reference(inp)

    ref_out = _native_copy_out(ref_inp, level, (4, 6))
    res = flag_gems._fw_primal_copy_out(inp, level, out=out)

    assert res is out
    utils.gems_assert_equal(out, ref_out)
