# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry, tl_extra_shim

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def trunc_kernel(
    x_ptr,
    y_ptr,
    n,
    BLOCK: tl.constexpr,
):
    """Element-wise trunc-toward-zero over a flat view, grid-stride loop.

    Each program walks a stride of tiles (``pid, pid+num_programs, ...``) so the
    grid width can be capped below the tile count: on this hardware a fixed
    ~max-occupancy grid saturates the memory subsystem, while a per-tile grid
    (one program per tile) regresses slightly because the extra launch slots buy
    no extra bandwidth and add dispatch cost. ``num_warps`` is selected from the
    tile size by the host heuristic.

    Truncation is the libdevice ``trunc`` on an fp32 promotion, matching the
    generic layer's numeric path exactly (and PyTorch's trunc semantics). The
    fp32 promotion is required: ``trunc`` is not native to the fp16/bf16 units,
    and casting straight through int32 would diverge on NaN/Inf and large
    magnitudes. ``x_ptr`` and ``y_ptr`` may alias (in-place ``trunc_``) since
    the load and store of a given element are within one iteration with no
    cross-element dependency.
    """
    pid = tl.program_id(0)
    num_programs = tl.num_programs(0)
    num_tiles = tl.cdiv(n, BLOCK)
    for tile in tl.range(pid, num_tiles, num_programs):
        off = tile * BLOCK + tl.arange(0, BLOCK)
        mask = off < n
        x = tl.load(x_ptr + off, mask=mask, other=0.0)
        y = tl_extra_shim.trunc(x.to(tl.float32)).to(x.dtype)
        tl.store(y_ptr + off, y, mask=mask)


def _heur(n):
    """Pick (BLOCK, num_warps, num_programs) for thead PPU.

    ``trunc`` is memory-bandwidth-bound (one load, one store, near-zero
    compute), so the tile is sized to saturate bandwidth rather than to hide
    arithmetic latency. A wide ``BLOCK=4096`` with a single warp tile keeps the
    grid narrow and the per-program register tile small; a larger tile does not
    raise throughput (already bandwidth-saturated) and only inflates launch.
    For tiny tensors the block shrinks to the next power of two of ``n`` so a
    single program covers the whole tensor with no masked tail.
    """
    if n <= 4096:
        BLOCK = triton.next_power_of_2(max(n, 64))
        num_warps = 4
        num_programs = 1
    else:
        # BLOCK=4096: tuned for thead PPU — large enough to saturate bandwidth on
        # big tensors, with the grid capped at 2048 programs to avoid dispatch
        # overhead past the device's saturation point.
        BLOCK = 4096
        num_warps = 4
        # Cap the grid near the device's saturation point: more programs than
        # this do not add bandwidth and only add dispatch overhead.
        num_programs = min(triton.cdiv(n, BLOCK), 2048)
    return BLOCK, num_warps, num_programs


def trunc(A):
    logger.debug("GEMS_THEAD TRUNC")
    n = A.numel()
    if n == 0:
        return torch.empty_like(A)
    # Operate on a flat contiguous view: torch.trunc preserves the input's
    # memory layout in the output, so a 1:1 flat copy into a same-strided
    # result keeps the layout and is correct for arbitrary (contiguous or
    # strided) inputs. ``reshape`` returns a view when possible (no copy) and
    # otherwise (non-contiguous) falls back to contiguous — matching the
    # behaviour callers get from the generic layer and from torch eager.
    x = A.reshape(-1)
    out = torch.empty_like(x)
    BLOCK, num_warps, num_programs = _heur(n)
    with torch_device_fn.device(A.device):
        trunc_kernel[(num_programs,)](x, out, n, BLOCK=BLOCK, num_warps=num_warps)
    return out.view_as(A)


def trunc_(A):
    logger.debug("GEMS_THEAD TRUNC_")
    n = A.numel()
    if n == 0:
        return A
    # In-place: write straight back into the input's storage. ``reshape`` on a
    # non-contiguous tensor materialises a contiguous copy, which would discard
    # the in-place write on exit — so require contiguity for the in-place path
    # (torch.trunc_ on a strided tensor also resolves to a contiguous op). For
    # the contiguous case the flat view aliases A's storage, so the store
    # updates A in place.
    if not A.is_contiguous():
        A = A.contiguous()
    x = A.reshape(-1)
    BLOCK, num_warps, num_programs = _heur(n)
    with torch_device_fn.device(A.device):
        trunc_kernel[(num_programs,)](x, x, n, BLOCK=BLOCK, num_warps=num_warps)
    return A
