# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

adaptive_max_pool3d_backward:
  - META:
      BLOCK_SIZE: 64
    num_warps: 4
    num_stages: 3
  - META:
      BLOCK_SIZE: 128
    num_warps: 4
    num_stages: 3
  - META:
      BLOCK_SIZE: 256
    num_warps: 8
    num_stages: 3
  - META:
      BLOCK_SIZE: 512
    num_warps: 8
    num_stages: 2
  - META:
      BLOCK_SIZE: 1024
    num_warps: 8
    num_stages: 2

attention:
- gen: true
  param_map:
    META:
      BLOCK_M: block_m
      BLOCK_N: block_n
      PRE_LOAD_V: pre_load_v
    num_warps: warps
    num_stages: stages
  block_m:
  - 64
  - 128
  block_n:
  - 32
  - 64
  - 128
  pre_load_v:
  - true
  - false
  warps:
  - 4
  - 8
  stages:
  - 1

bmm:
- META:
    TILE_M: 32
    TILE_N: 32
    TILE_K: 32
    GROUP_M: 1
  num_warps: 4
  num_stages: 2
baddbmm:
argmax:
argmin:
argmin_split_k:
    - gen: true
      param_map:
        META:
          BLOCK_M: block_m
          BLOCK_N: block_n
          BLOCK_K: block_k
        num_warps: warps
        num_stages: 4
      block_m:
        - 4
        - 8
      block_n:
        - 64
        - 512
      block_k:
        - 32
        - 64
      warps:
        - 4
        - 8
        - 16

lgamma:
  - META:
      BLOCK_SIZE: 256
    num_warps: 4
    num_stages: 2
  - META:
      BLOCK_SIZE: 512
    num_warps: 4
    num_stages: 2
  - META:
      BLOCK_SIZE: 1024
    num_warps: 4
    num_stages: 2

log_softmax:
mm:
mm_nn:
mm_nt:
mm_splitk:
mm_splitk_two_step:
gemv_k_parallel:
special_chebyshev_polynomial_u:
  - META:
      BLOCK_SIZE: 256
    num_warps: 8
    num_stages: 4
  - META:
      BLOCK_SIZE: 512
    num_warps: 8
    num_stages: 4
  - META:
      BLOCK_SIZE: 1024
    num_warps: 8
    num_stages: 4
  - META:
      BLOCK_SIZE: 2048
    num_warps: 8
    num_stages: 3

softmax_non_inner:
softmax_inner:
test_libentry:
min:
prod:
max:
addmm:
cross_entropy_loss:
masked_fill:
all:
amax:
any:
index_select:
layer_norm_persistent:
layer_norm_loop:
layer_norm_backward:
weight_bias_backward:
masked_select:
mean:
instancenorm:
instance_norm_loop:
instance_norm_backward:
instance_norm_weight_bias_backward:
count_nonzero:
cross_entropy_loss_sum_and_scale:
upsample_nearest2d:
upsample_linear1d:
upsample_bicubic2d_aa:
mv:
nonzero:
randperm:
select_scatter:
select_scatter_inner:
softmax:
vstack:
gather:
scatter:
sum:
triu:
triu_batch:
weight_norm_kernel_last:
weight_norm_kernel_first:
weight_norm_kernel:
vector_norm:
var_mean:
conv2d_forward:
conv2d_backward_weight:
batch_norm:
kron:
index_put:
polar:
diff_1d:
diff:
rms_norm_loop:
  - gen: true
    param_map:
      META:
        TILE_N: tile_n
      num_warps: warps
    warps:
      - 4
      - 8
    tile_n:
      - 512
      - 1024
add_rms_norm_loop:
  - gen: true
    param_map:
      META:
        TILE_N: tile_n
      num_warps: warps
    warps:
      - 4
      - 8
    tile_n:
      - 512
      - 1024
nansum_final_reduce:
nansum_dim:
nansum_dim_non_inner:
nansum_dim_inner:
alpha_dropout:
