# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import builtins
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as ext

logger = logging.getLogger(__name__)


def _get_num_sms():
    """Get the number of SMs on the current device."""
    return torch.cuda.get_device_properties(
        torch.cuda.current_device()
    ).multi_processor_count


@libentry()
@triton.jit(do_not_specialize=["n_elements", "bins", "min_val", "max_val"])
def histc_kernel(
    inp_ptr,
    local_hists_ptr,
    n_elements,
    bins,
    min_val,
    max_val,
    BLOCK_SIZE: tl.constexpr,
    BINS_STRIDE: tl.constexpr,
):
    """
    Persistent histogram kernel with per-program local histograms.

    Each program loops over multiple blocks and atomically accumulates into
    its private local histogram. This eliminates inter-program contention on
    the global output. Small BLOCK_SIZE combined with num_warps=1 minimizes
    intra-program contention (64 threads / bins threads per bin on Metax).
    """
    pid = ext.program_id(0)
    num_pids = ext.num_programs(0)
    offsets = tl.arange(0, BLOCK_SIZE)

    local_hist_ptr = local_hists_ptr + pid * BINS_STRIDE

    num_blocks = tl.cdiv(n_elements, BLOCK_SIZE)
    for block_id in tl.range(pid, num_blocks, num_pids):
        off = block_id * BLOCK_SIZE + offsets
        mask = off < n_elements

        inp_val = tl.load(inp_ptr + off, mask=mask, other=float("nan")).to(tl.float32)

        bin_idx = tl.floor((inp_val - min_val) * bins / (max_val - min_val)).to(
            tl.int32
        )

        bin_idx = tl.where(inp_val == max_val, bins - 1, bin_idx)
        in_range = (inp_val >= min_val) & (inp_val <= max_val)
        bin_idx = tl.where(bin_idx < 0, 0, bin_idx)
        bin_idx = tl.where(bin_idx >= bins, bins - 1, bin_idx)

        valid_mask = mask & in_range

        tl.atomic_add(local_hist_ptr + bin_idx, 1.0, mask=valid_mask, sem="relaxed")


def histc(inp, bins=100, min=0, max=0):
    """
    Compute the histogram of a tensor. Metax-optimized implementation.

    Uses per-program local histograms to eliminate inter-program atomic
    contention, combined with small blocks (64 elements) and num_warps=1
    (64 threads/program on Metax) to minimize intra-program contention.
    Final reduction via torch.sum.

    Args:
        inp: Input tensor
        bins: Number of histogram bins (default: 100)
        min: Lower end of the range (inclusive).
        max: Upper end of the range (inclusive).

    Returns:
        Tensor: Histogram of shape (bins,)
    """
    logger.debug("GEMS_METAX HISTC")

    inp = inp.contiguous()
    min_val = float(min)
    max_val = float(max)

    if min_val == 0 and max_val == 0:
        min_val = float(inp.min().item())
        max_val = float(inp.max().item())

    if min_val == max_val:
        out = torch.zeros(bins, dtype=inp.dtype, device=inp.device)
        # torch.histc places all elements in the middle bin when min==max
        out[bins // 2] = ((inp == min_val) & ~torch.isnan(inp)).sum().item()
        return out

    n_elements = inp.numel()
    if n_elements == 0:
        return torch.zeros(bins, dtype=inp.dtype, device=inp.device)

    NUM_SMS = _get_num_sms()

    # BLOCK_SIZE=64 with num_warps=1 gives minimal atomic contention:
    # 64 threads per program on Metax (warp_size=64)
    BLOCK_SIZE = 64
    num_blocks = triton.cdiv(n_elements, BLOCK_SIZE)

    # Scale grid to maintain good occupancy:
    # Cap at NUM_SMS * GRID_MULT with persistent loop for large inputs
    GRID_MULT = 10
    grid_size = builtins.min(num_blocks, NUM_SMS * GRID_MULT)

    # Per-program local histograms: shape (grid_size, bins)
    local_hists = torch.zeros((grid_size, bins), dtype=torch.float32, device=inp.device)

    with torch_device_fn.device(inp.device):
        histc_kernel[(grid_size,)](
            inp,
            local_hists,
            n_elements,
            bins,
            min_val,
            max_val,
            BLOCK_SIZE=BLOCK_SIZE,
            BINS_STRIDE=bins,
            num_warps=1,
        )

    # Reduce local histograms into final output
    out = local_hists.sum(dim=0).to(inp.dtype)
    return out
