# Kunlunxin (XPU) override of concatenate.
#
# `concatenate` is a pure alias of `cat` (aten::concatenate(Tensor[], int dim=0)).
# kunlunxin already ships a tuned `cat` override (`_kunlunxin/ops/cat.py`, a
# StridedBuffer + pointwise_dynamic `copy_func` path with bounded tiles +
# autoGrid + libentry cache), but `concatenate` was NOT overridden. The generic
# `ops/concatenate.py` binds `from flag_gems.ops.cat import cat` at import time,
# so it always calls the GENERIC cat whose hand-written raw @triton.jit
# `cat_copy_func_kernel_4` (fixed BLOCK, no @libentry caching) recompiles per
# shape/launch -> the IR dump (`harness/perf_ir_3/ir-concatenate-dev7.log`,
# 482K lines / 512KB) shows the module explosion -> discrete/slow on XPU.
#
# Fix: route `concatenate` through the exact same tuned kunlunxin `cat`. Zero
# algorithm change (byte-identical to the covered cat path) -> zero correctness
# risk. Same class as the cat_out uncovered-variant fix.
import logging
from typing import List, Tuple, Union

import torch

from .cat import cat

logger = logging.getLogger(__name__)


# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
from flag_gems.runtime import torch_device_fn

"""Triton implementation of torch.cat semantics.

concatenate(A, dim=0) concatenates a tuple/list of tensors along ``dim`` and returns
the resulting tensor (value-returning).

Semantics notes (matches torch.cat on this backend):
  * Zero-numel tensors are dropped when any non-empty tensor exists; output
    shape/contents come from the live tensors only (negative dims are then
    normalized against the live tensors' ndim).
  * If every input is empty, a plain (empty) concatenation is returned.

Performance architecture
-------------------------
Copies are the only work.  On this target per-CTA dispatch dominates small
blocks, so every copy uses very large Triton blocks (<= 32768 elements/CTA).
Contiguous whole-block transfers reinterpret both sides as int64 so each lane
moves 8 bytes (measured == torch memcpy bandwidth); byte-alignments that do
not permit the 8-byte view fall back to a native elementwise flat copy.
Concatenations along a non-outer dimension are handled by a masked affine
row-slab copy; non-contiguous sources by a fully strided gather kernel.
"""

import torch
import triton
import triton.language as tl


@triton.jit
def _kg_cat_copy_flat(src_ptr, dst_ptr, numel, BLOCK: tl.constexpr):
    """Contiguous flat copy (dtype-generic).  Grid = ceil(numel / BLOCK)."""
    pid = tl.program_id(0).to(tl.int64)
    offs = pid * BLOCK + tl.arange(0, BLOCK).to(tl.int64)
    m = offs < numel
    v = tl.load(src_ptr + offs, mask=m)
    tl.store(dst_ptr + offs, v, mask=m)


@triton.jit
def _kg_cat_copy_slab(src_ptr, dst_ptr, row_len, row_gap, add0, BLOCK: tl.constexpr):
    """Copy one contiguous input into a row-strided output region.

    Grid is (outer, ceil(row_len / BLOCK)); prefix row ``r`` of ``row_len``
    contiguous source elements maps to output offset
    ``r * (row_len + row_gap) + add0`` (both sides stay affine per block).
    """
    r = tl.program_id(0).to(tl.int64)
    c = tl.program_id(1).to(tl.int64)
    offs = c * BLOCK + tl.arange(0, BLOCK).to(tl.int64)
    m = offs < row_len
    v = tl.load(src_ptr + r * row_len + offs, mask=m)
    tl.store(dst_ptr + r * (row_len + row_gap) + add0 + offs, v, mask=m)


@triton.jit
def _kg_cat_copy_strided(
    src_ptr,
    dst_ptr,
    numel,
    sizes_ptr,
    sstr_ptr,
    dstr_ptr,
    NDIM: tl.constexpr,
    BLOCK: tl.constexpr,
):
    """Generic strided logical copy used only for non-contiguous sources."""
    pid = tl.program_id(0).to(tl.int64)
    f = pid * BLOCK + tl.arange(0, BLOCK).to(tl.int64)
    m = f < numel
    rem = f
    s_acc = tl.zeros([BLOCK], dtype=tl.int64)
    d_acc = tl.zeros([BLOCK], dtype=tl.int64)
    for dd in tl.static_range(NDIM - 1, -1, -1):
        sz = tl.load(sizes_ptr + dd).to(tl.int64)
        c = rem % sz
        rem = rem // sz
        s_acc += c * tl.load(sstr_ptr + dd).to(tl.int64)
        d_acc += c * tl.load(dstr_ptr + dd).to(tl.int64)
    v = tl.load(src_ptr + s_acc, mask=m)
    tl.store(dst_ptr + d_acc, v, mask=m)


def _kg_prod(xs):
    r = 1
    for x in xs:
        r *= x
    return r


def _kg_block(n, cap):
    """Power-of-two block <= cap with a 1024 floor; grid stays >= 1 CTA."""
    if n < 1:
        b = 1024
    else:
        b = 1 << ((n - 1).bit_length())
        if b > cap:
            b = cap
        if b < 1024:
            b = 1024
    return b


def _kg_warps(b):
    w = b // 2048
    if w < 4:
        w = 4
    if w > 16:
        w = 16
    return w


def concatenate(A, dim=0):
    with torch_device_fn.device(A[0].device):
        first = A[0]
        dtype = first.dtype
        device = first.device

        live = [t for t in A if t.numel() > 0]

        if live:
            tpl = live[0]
            ndim = tpl.dim()
            dd = dim if dim >= 0 else dim + ndim
            out_shape = list(tpl.shape)
            sizes_d = []
            total_d = 0
            for t in live:
                sd = t.shape[dd]
                sizes_d.append(sd)
                total_d += sd
            out_shape[dd] = total_d
            work = live
        else:
            ndim = first.dim()
            dd = dim if dim >= 0 else dim + ndim
            out_shape = list(first.shape)
            sizes_d = []
            total_d = 0
            for t in A:
                sd = t.shape[dd]
                sizes_d.append(sd)
                total_d += sd
            out_shape[dd] = total_d
            work = A

        out = torch.empty(out_shape, dtype=dtype, device=device)

        if not live:
            return out

        suffix = _kg_prod(out_shape[dd + 1 :])
        outer = _kg_prod(out_shape[:dd])

        out_flat = out.view(-1) if out.dim() > 1 else out
        esz = dtype.itemsize

        off = 0
        for t, sd in zip(work, sizes_d):
            numel = t.numel()
            if numel == 0:
                continue
            base = off * suffix  # flat element offset of this input's region

            if t.is_contiguous():
                if outer == 1:
                    # Destination region is one contiguous flat block.
                    if (numel * esz) % 8 == 0 and (base * esz) % 8 == 0:
                        a64 = t.reshape(-1).view(torch.int64)
                        d64 = out_flat[base : base + numel].view(torch.int64)
                        n64 = a64.numel()
                        blk = _kg_block(n64, 32768)
                        _kg_cat_copy_flat[((n64 + blk - 1) // blk,)](
                            a64, d64, n64, BLOCK=blk, num_warps=_kg_warps(blk)
                        )
                    else:
                        blk = _kg_block(numel, 32768)
                        _kg_cat_copy_flat[((numel + blk - 1) // blk,)](
                            t,
                            out_flat[base : base + numel],
                            numel,
                            BLOCK=blk,
                            num_warps=_kg_warps(blk),
                        )
                else:
                    # Row-strided slabs (concat along a middle/last dimension).
                    row_len = sd * suffix
                    blk = _kg_block(row_len, 8192)
                    row_stride_dst = out_shape[dd] * suffix
                    _kg_cat_copy_slab[(outer, (row_len + blk - 1) // blk)](
                        t,
                        out,
                        row_len,
                        row_stride_dst - row_len,
                        base,
                        BLOCK=blk,
                        num_warps=_kg_warps(blk),
                    )
            else:
                region = out.narrow(dd, off, sd)
                sizes_t = torch.tensor(list(t.shape), dtype=torch.int64, device=device)
                sstr_t = torch.tensor(
                    list(t.stride()), dtype=torch.int64, device=device
                )
                dstr_t = torch.tensor(
                    list(region.stride()), dtype=torch.int64, device=device
                )
                blk = _kg_block(numel, 8192)
                _kg_cat_copy_strided[((numel + blk - 1) // blk,)](
                    t,
                    region,
                    numel,
                    sizes_t,
                    sstr_t,
                    dstr_t,
                    NDIM=t.dim(),
                    BLOCK=blk,
                    num_warps=_kg_warps(blk),
                )
            off += sd
        return out
