# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import torch
import triton
import triton.language as tl

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
from flag_gems.runtime import torch_device_fn


@triton.jit
def _refl_pad1d_backward_kernel(
    grad_out_ptr,
    grad_in_ptr,
    W_in,
    W_out,
    pad_left,
    BLOCK_W: tl.constexpr,
):
    pid_b = tl.program_id(0)
    pid_w = tl.program_id(1)

    offs = pid_w * BLOCK_W + tl.arange(0, BLOCK_W)
    m = offs < W_in

    base_in = pid_b * W_in
    base_out = pid_b * W_out
    nm1 = W_in - 1

    # Clamp lane offsets into the valid row so every load below is in-bounds;
    # lanes with offs >= W_in are excluded by the store mask.
    k = tl.minimum(offs, nm1)

    # Clamp every address before loading; cropped contributions are zero.
    center = pad_left + k
    center_valid = (center >= 0) & (center < W_out)
    ci = tl.minimum(tl.maximum(center, 0), W_out - 1)
    cv = tl.load(grad_out_ptr + base_out + ci).to(tl.float32)
    acc = tl.where(center_valid, cv, 0.0)

    li = pad_left - k
    left_valid = (k >= 1) & (li >= 0) & (li < W_out)
    li = tl.minimum(tl.maximum(li, 0), W_out - 1)
    lv = tl.load(grad_out_ptr + base_out + li).to(tl.float32)
    acc += tl.where(left_valid, lv, 0.0)

    ri = pad_left + 2 * nm1 - k
    right_valid = (k < nm1) & (ri >= 0) & (ri < W_out)
    ri = tl.minimum(tl.maximum(ri, 0), W_out - 1)
    rv = tl.load(grad_out_ptr + base_out + ri).to(tl.float32)
    acc += tl.where(right_valid, rv, 0.0)

    tl.store(grad_in_ptr + base_in + offs, acc, mask=m)


def _cfg_for(W_in, B, dtype):
    total = B * W_in
    is_fp32 = dtype == torch.float32
    if total <= 8:
        return 64, 1  # tiny rows: single small warp
    if not is_fp32 and total >= 128:
        return 256, 4  # fp16/bf16 rows >= 128 elems: wider blocks win
    return 128, 4


def reflection_pad1d_backward(grad_output, input, padding):
    # ---- parse padding (int, sequence of 1/2, or tensor) ----
    with torch_device_fn.device(grad_output.device):
        if isinstance(padding, torch.Tensor):
            pad_list = [int(v) for v in padding.detach().reshape(-1).cpu().tolist()]
        elif isinstance(padding, (tuple, list)):
            pad_list = [int(v) for v in padding]
        else:
            pad_list = [int(padding), int(padding)]

        if len(pad_list) == 1:
            pad_left = pad_right = pad_list[0]
        elif len(pad_list) == 2:
            pad_left, pad_right = pad_list[0], pad_list[1]
        else:
            raise ValueError("reflection_pad1d padding must have length 1 or 2")

        W_in = input.shape[-1]
        W_out = grad_output.shape[-1]

        if W_in == 1 and pad_left == 0 and pad_right == 0:
            return grad_output.clone()
        if W_in < 2:
            raise ValueError("input width must be at least 2 for reflection padding")
        if pad_left >= W_in or pad_right >= W_in:
            raise ValueError(
                "padding values must be less than the input width for reflection padding"
            )

        if not grad_output.is_contiguous():
            grad_output = grad_output.contiguous()
        if not input.is_contiguous():
            input = input.contiguous()

        grad_input = torch.empty_like(input)

        B = input.numel() // W_in
        if B == 0 or W_in == 0:
            return grad_input

        block, warps = _cfg_for(W_in, B, input.dtype)
        grid = (B, triton.cdiv(W_in, block))
        _refl_pad1d_backward_kernel[grid](
            grad_output,
            grad_input,
            W_in,
            W_out,
            pad_left,
            BLOCK_W=block,
            num_warps=warps,
        )
        return grad_input
