# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import torch
import triton
import triton.language as tl

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
from flag_gems.runtime import torch_device_fn


@triton.jit
def _refl_pad3d_kernel(
    in_ptr,
    out_ptr,
    numel: tl.constexpr,
    L1: tl.constexpr,
    S0: tl.constexpr,
    S1: tl.constexpr,
    S2: tl.constexpr,
    p0l: tl.constexpr,
    p0r: tl.constexpr,
    p1l: tl.constexpr,
    p1r: tl.constexpr,
    p2l: tl.constexpr,
    p2r: tl.constexpr,
    A0: tl.constexpr,
    A1: tl.constexpr,
    G0: tl.constexpr,
    G1: tl.constexpr,
    G2: tl.constexpr,
    HAS0: tl.constexpr,
    HAS1: tl.constexpr,
    HAS2: tl.constexpr,
    K: tl.constexpr,
    BLOCK: tl.constexpr,
):
    O0 = S0 + p0l + p0r
    O1 = S1 + p1l + p1r
    O2 = S2 + p2l + p2r

    pid = tl.program_id(0)
    idx = pid * BLOCK + tl.arange(0, BLOCK)
    m = idx < numel

    # Peel the three padded dims (fastest = last input dim first).
    z = idx
    o2 = z % O2
    z = z // O2
    o1 = z % O1
    z = z // O1
    o0 = z % O0
    z = z // O0

    if K == 0:
        lead = 0
    elif K == 1:
        lead = z * A0
    else:
        lead = (z % L1) * A1 + (z // L1) * A0

    # Reflect dim 0 (input dim K).
    if HAS0:
        i0 = o0 - p0l
        i0 = tl.where(i0 < 0, -i0, i0)
        i0 = tl.where(i0 >= S0, 2 * (S0 - 1) - i0, i0)
    else:
        i0 = o0

    # Reflect dim 1.
    if HAS1:
        i1 = o1 - p1l
        i1 = tl.where(i1 < 0, -i1, i1)
        i1 = tl.where(i1 >= S1, 2 * (S1 - 1) - i1, i1)
    else:
        i1 = o1

    # Reflect dim 2 (fastest dim).
    if HAS2:
        i2 = o2 - p2l
        i2 = tl.where(i2 < 0, -i2, i2)
        i2 = tl.where(i2 >= S2, 2 * (S2 - 1) - i2, i2)
    else:
        i2 = o2

    in_off = lead + i0 * G0 + i1 * G1 + i2 * G2
    val = tl.load(in_ptr + in_off, mask=m, other=0.0)
    tl.store(out_ptr + idx, val, mask=m)


def _parse_padding(padding):
    if isinstance(padding, torch.Tensor):
        pad_list = [int(v) for v in padding.detach().reshape(-1).cpu().tolist()]
    elif isinstance(padding, (tuple, list)):
        pad_list = [int(v) for v in padding]
    else:
        raise TypeError("padding must be a sequence of integers")
    if len(pad_list) % 2 != 0 or len(pad_list) > 6:
        raise ValueError("unsupported reflection padding length")
    while len(pad_list) < 6:
        pad_list = [0, 0] + pad_list
    return pad_list


def reflection_pad3d(input, padding, *, out=None):
    with torch_device_fn.device(input.device):
        ndim = input.dim()
        if ndim < 3:
            raise ValueError("reflection pad requires an input with at least 3 dims")
        pad = _parse_padding(padding)
        K = ndim - 3  # number of leading (unpadded) dims, 0..2 for 3D..5D inputs

        in_shape = input.shape
        S0, S1, S2 = in_shape[K], in_shape[K + 1], in_shape[K + 2]
        p0l, p0r = pad[4], pad[5]
        p1l, p1r = pad[2], pad[3]
        p2l, p2r = pad[0], pad[1]
        O0 = S0 + p0l + p0r
        O1 = S1 + p1l + p1r
        O2 = S2 + p2l + p2r

        out_shape = tuple(in_shape[:K]) + (O0, O1, O2)
        if out is None:
            out = torch.empty(out_shape, dtype=input.dtype, device=input.device)
        else:
            if tuple(out.shape) != out_shape or out.dtype != input.dtype:
                out = torch.empty(out_shape, dtype=input.dtype, device=input.device)

        numel = 1
        for s in out_shape:
            numel *= s
        if numel == 0:
            return out

        strides = input.stride()
        G0, G1, G2 = strides[K], strides[K + 1], strides[K + 2]
        A0 = strides[0] if K >= 1 else 0
        A1 = strides[1] if K >= 2 else 0
        L1 = in_shape[1] if K >= 2 else 1

        BLOCK = 1024
        grid = ((numel + BLOCK - 1) // BLOCK,)
        _refl_pad3d_kernel[grid](
            input,
            out,
            numel=numel,
            L1=L1,
            S0=S0,
            S1=S1,
            S2=S2,
            p0l=p0l,
            p0r=p0r,
            p1l=p1l,
            p1r=p1r,
            p2l=p2l,
            p2r=p2r,
            A0=A0,
            A1=A1,
            G0=G0,
            G1=G1,
            G2=G2,
            HAS0=1 if (p0l != 0 or p0r != 0) else 0,
            HAS1=1 if (p1l != 0 or p1r != 0) else 0,
            HAS2=1 if (p2l != 0 or p2r != 0) else 0,
            K=K,
            BLOCK=BLOCK,
            num_warps=4,
        )
        return out
