# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import numbers

import torch
import triton
import triton.language as tl

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
from flag_gems.runtime import torch_device_fn

_BLOCK = 1024
_NUM_WARPS = 4


# ---------------------------------------------------------------------------
# Kernel 1: uniform integer degree in [0,5], x read linearly (contiguous).
# Degree is a compile-time constant so the exact closed-form U_n(x) is emitted
# with no dynamic loop, which allows very large BLOCK sizes on the XPU backend.
# ---------------------------------------------------------------------------
@triton.jit
def _cheb_u_uni_lin(x_ptr, out_ptr, total, DEG: tl.constexpr, BLOCK: tl.constexpr):
    pid = tl.program_id(0).to(tl.int64)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < total
    xv = tl.load(x_ptr + offs, mask=mask).to(tl.float32)
    if DEG == 0:
        r = xv * 0.0 + 1.0
    elif DEG == 1:
        r = xv + xv
    else:
        x2 = xv * xv
        if DEG == 2:
            r = 4.0 * x2 - 1.0
        else:
            x3 = x2 * xv
            if DEG == 3:
                r = 8.0 * x3 - 4.0 * xv
            else:
                x4 = x3 * xv
                if DEG == 4:
                    r = 16.0 * x4 - 12.0 * x2 + 1.0
                else:
                    x5 = x4 * xv
                    r = 32.0 * x5 - 32.0 * x3 + 6.0 * xv
    tl.store(out_ptr + offs, r, mask=mask)


# ---------------------------------------------------------------------------
# Kernel 2: uniform integer degree, x gathered through a broadcast decode
# ---------------------------------------------------------------------------
@triton.jit
def _cheb_u_uni_gen(
    x_ptr,
    out_ptr,
    meta_ptr,
    R,
    total,
    degree,
    BLOCK: tl.constexpr,
    CT_F64: tl.constexpr,
):
    pid = tl.program_id(0).to(tl.int64)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < total
    xo = tl.zeros([BLOCK], dtype=tl.int64)
    for d in range(0, R):
        ostr = tl.load(meta_ptr + (R + d))
        sz = tl.load(meta_ptr + d)
        c = (offs // ostr) % sz
        xo += c * tl.load(meta_ptr + (2 * R + d))
    if CT_F64:
        xv = tl.load(x_ptr + xo, mask=mask).to(tl.float64)
    else:
        xv = tl.load(x_ptr + xo, mask=mask).to(tl.float32)
    two_x = xv + xv
    a = xv * 0.0 + 1.0
    b = two_x
    for k in range(2, degree + 1):
        c = two_x * b - a
        a = b
        b = c
    res = tl.where(degree == 0, 1.0, b)
    res = tl.where(degree < 0, 0.0, res)
    tl.store(out_ptr + offs, res, mask=mask)


# ---------------------------------------------------------------------------
# Kernel 3: uniform degree supplied as a scalar tensor element (x linear)
# ---------------------------------------------------------------------------
@triton.jit
def _cheb_u_uni_tensor(
    x_ptr, n_ptr, out_ptr, total, BLOCK: tl.constexpr, CT_F64: tl.constexpr
):
    pid = tl.program_id(0).to(tl.int64)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < total
    n0 = tl.load(n_ptr).to(tl.int64)
    if CT_F64:
        xv = tl.load(x_ptr + offs, mask=mask).to(tl.float64)
    else:
        xv = tl.load(x_ptr + offs, mask=mask).to(tl.float32)
    two_x = xv + xv
    a = xv * 0.0 + 1.0
    b = two_x
    for k in range(2, n0 + 1):
        c = two_x * b - a
        a = b
        b = c
    res = tl.where(n0 == 0, 1.0, b)
    res = tl.where(n0 < 0, 0.0, res)
    tl.store(out_ptr + offs, res, mask=mask)


# ---------------------------------------------------------------------------
# Kernel 4: per-lane degrees, x and n linear (same-shape contiguous tensors)
# ---------------------------------------------------------------------------
@triton.jit
def _cheb_u_var_lin(
    x_ptr,
    n_ptr,
    out_ptr,
    total,
    BLOCK: tl.constexpr,
    CT_F64: tl.constexpr,
    N_IS_INT: tl.constexpr,
):
    pid = tl.program_id(0).to(tl.int64)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < total
    if N_IS_INT:
        nv = tl.load(n_ptr + offs, mask=mask, other=0)
    else:
        nv = tl.load(n_ptr + offs, mask=mask, other=0.0)
    nv = nv.to(tl.int64)
    if CT_F64:
        xv = tl.load(x_ptr + offs, mask=mask).to(tl.float64)
    else:
        xv = tl.load(x_ptr + offs, mask=mask).to(tl.float32)
    two_x = xv + xv
    a = xv * 0.0 + 1.0
    b = two_x
    bmax = tl.max(nv, axis=0)
    for k in range(2, bmax + 1):
        c = two_x * b - a
        adv = nv >= k
        a = tl.where(adv, b, a)
        b = tl.where(adv, c, b)
    res = tl.where(nv == 0, 1.0, b)
    res = tl.where(nv < 0, 0.0, res)
    tl.store(out_ptr + offs, res, mask=mask)


# ---------------------------------------------------------------------------
# Kernel 5: per-lane degrees with broadcast decode of both inputs
# ---------------------------------------------------------------------------
@triton.jit
def _cheb_u_var_gen(
    x_ptr,
    n_ptr,
    out_ptr,
    meta_ptr,
    R,
    total,
    BLOCK: tl.constexpr,
    CT_F64: tl.constexpr,
    N_IS_INT: tl.constexpr,
):
    pid = tl.program_id(0).to(tl.int64)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < total
    xo = tl.zeros([BLOCK], dtype=tl.int64)
    no = tl.zeros([BLOCK], dtype=tl.int64)
    for d in range(0, R):
        ostr = tl.load(meta_ptr + (R + d))
        sz = tl.load(meta_ptr + d)
        c = (offs // ostr) % sz
        xo += c * tl.load(meta_ptr + (2 * R + d))
        no += c * tl.load(meta_ptr + (3 * R + d))
    if N_IS_INT:
        nv = tl.load(n_ptr + no, mask=mask, other=0)
    else:
        nv = tl.load(n_ptr + no, mask=mask, other=0.0)
    nv = nv.to(tl.int64)
    if CT_F64:
        xv = tl.load(x_ptr + xo, mask=mask).to(tl.float64)
    else:
        xv = tl.load(x_ptr + xo, mask=mask).to(tl.float32)
    two_x = xv + xv
    a = xv * 0.0 + 1.0
    b = two_x
    bmax = tl.max(nv, axis=0)
    for k in range(2, bmax + 1):
        c = two_x * b - a
        adv = nv >= k
        a = tl.where(adv, b, a)
        b = tl.where(adv, c, b)
    res = tl.where(nv == 0, 1.0, b)
    res = tl.where(nv < 0, 0.0, res)
    tl.store(out_ptr + offs, res, mask=mask)


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------
def _eff_strides(shape, strides, out_shape):
    R = len(out_shape)
    pad = R - len(shape)
    res = []
    for j in range(R):
        if j < pad:
            res.append(0)
        else:
            dim = j - pad
            res.append(0 if shape[dim] == 1 else int(strides[dim]))
    return res


def _meta(out_shape, x_shape, x_strides, n_shape=None, n_strides=None, with_n=True):
    sz = [int(s) for s in out_shape]
    ostr = []
    p = 1
    for s in reversed(sz):
        ostr.append(p)
        p *= s
    ostr.reverse()
    xs = _eff_strides(x_shape, x_strides, out_shape)
    data = sz + ostr + xs
    if with_n:
        ns = _eff_strides(n_shape, n_strides, out_shape)
        data = data + ns
    return data


def _out_dtype(x_dtype, n_dtype):
    promoted = torch.promote_types(x_dtype, n_dtype)
    if promoted.is_floating_point:
        return promoted
    if promoted.is_complex:
        return promoted
    return torch.get_default_dtype()


@triton.jit
def _n_range_stage1(n_ptr, lo_ptr, hi_ptr, total, BLOCK: tl.constexpr):
    pid = tl.program_id(0).to(tl.int64)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < total
    nv = tl.load(n_ptr + offs, mask=mask, other=0).to(tl.int32)
    lo = tl.min(nv, axis=0)
    hi = tl.max(nv, axis=0)
    tl.store(lo_ptr + pid, lo)
    tl.store(hi_ptr + pid, hi)


@triton.jit
def _n_range_stage2(lo_ptr, hi_ptr, out_ptr, g, BLOCK: tl.constexpr):
    idx = tl.arange(0, BLOCK)
    mask = idx < g
    lov = tl.load(lo_ptr + idx, mask=mask, other=2147483647)
    hiv = tl.load(hi_ptr + idx, mask=mask, other=-2147483648)
    lo = tl.min(lov, axis=0)
    hi = tl.max(hiv, axis=0)
    tl.store(out_ptr, lo)
    tl.store(out_ptr + 1, hi)


def _tensor_n_range(n):
    dev = n.device
    total = n.numel()
    g = triton.cdiv(total, 4096)
    lo = torch.empty(g, dtype=torch.int32, device=dev)
    hi = torch.empty(g, dtype=torch.int32, device=dev)
    _n_range_stage1[(g,)](n, lo, hi, total, BLOCK=4096, num_warps=_NUM_WARPS)
    b2 = 1
    while b2 < g:
        b2 <<= 1
    out = torch.empty(2, dtype=torch.int32, device=dev)
    _n_range_stage2[(1,)](lo, hi, out, g, BLOCK=b2, num_warps=_NUM_WARPS)
    return int(out[0].item()), int(out[1].item())


def special_chebyshev_polynomial_u(x, n):
    # FlagGems contract: only degrees n in [0, 5] are supported (explicit
    # polynomial formulas). Out-of-range degrees must raise ValueError.
    with torch_device_fn.device((x if isinstance(x, torch.Tensor) else n).device):
        if isinstance(n, numbers.Number):
            n_min = n_max = int(n)
        elif n.numel() == 1:
            n_min = n_max = int(n.reshape(()).item())
        else:
            n_min, n_max = _tensor_n_range(n)
        if n_max > 5 or n_min < 0:
            raise ValueError(
                "Chebyshev polynomial order n must be in [0, 5], "
                "got values in [%d, %d]" % (n_min, n_max)
            )

        x_shape = tuple(x.shape)

        n_is_number = isinstance(n, numbers.Number)

        if n_is_number:
            out_shape = x_shape
        else:
            out_shape = torch.broadcast_shapes(x_shape, tuple(n.shape))

        out_numel = 1
        for s in out_shape:
            out_numel *= int(s)

        if n_is_number:
            od = _out_dtype(
                x.dtype,
                torch.int64 if isinstance(n, numbers.Integral) else torch.float64,
            )
        else:
            od = _out_dtype(x.dtype, n.dtype)

        out = torch.empty(out_shape, dtype=od, device=x.device)
        if out_numel == 0:
            return out

        ct_f64 = od == torch.float64
        grid = (triton.cdiv(out_numel, _BLOCK),)

        if n_is_number:
            degree = int(n)
            if x.is_contiguous():
                if out_numel <= (1 << 14):
                    BLOCK, NW = 1024, 4
                else:
                    BLOCK, NW = 8192, 16
                grid = (triton.cdiv(out_numel, BLOCK),)
                _cheb_u_uni_lin[grid](
                    x, out, out_numel, DEG=degree, BLOCK=BLOCK, num_warps=NW
                )
            else:
                meta = torch.tensor(
                    _meta(out_shape, x_shape, tuple(x.stride())),
                    dtype=torch.int64,
                    device=x.device,
                )
                _cheb_u_uni_gen[grid](
                    x,
                    out,
                    meta,
                    len(out_shape),
                    out_numel,
                    degree,
                    BLOCK=_BLOCK,
                    CT_F64=ct_f64,
                    num_warps=_NUM_WARPS,
                )
            return out

        # tensor n below
        n_is_int = not n.dtype.is_floating_point
        n_shape = tuple(n.shape)

        if x.is_contiguous() and n.is_contiguous() and x_shape == n_shape:
            _cheb_u_var_lin[grid](
                x,
                n,
                out,
                out_numel,
                BLOCK=_BLOCK,
                CT_F64=ct_f64,
                N_IS_INT=n_is_int,
                num_warps=_NUM_WARPS,
            )
        elif n.numel() == 1 and x.is_contiguous():
            _cheb_u_uni_tensor[grid](
                x,
                n.reshape(()),
                out,
                out_numel,
                BLOCK=_BLOCK,
                CT_F64=ct_f64,
                num_warps=_NUM_WARPS,
            )
        else:
            meta = torch.tensor(
                _meta(
                    out_shape, x_shape, tuple(x.stride()), n_shape, tuple(n.stride())
                ),
                dtype=torch.int64,
                device=x.device,
            )
            R = len(out_shape)
            _cheb_u_var_gen[grid](
                x,
                n,
                out,
                meta,
                R,
                out_numel,
                BLOCK=_BLOCK,
                CT_F64=ct_f64,
                N_IS_INT=n_is_int,
                num_warps=_NUM_WARPS,
            )
        return out
