# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing permissions
# and limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import contextlib
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)

_CHUNK = 1024  # lanes per sort tile / per program sub-tile
_WARPS_HIST = 8
_WARPS_SCATTER = 16
_WARPS_BOUNDARY = 8


@triton.jit
def _small_kernel(
    idx_ptr,
    v_ptr,
    sum_ptr,
    oidx_ptr,
    m_ptr,
    n,
    row1,
    row2,
    sh0,
    sh1,
    sh2,
    st0,
    st1,
    st2,
    CHUNK: tl.constexpr,
    SDIM: tl.constexpr,
    ACC: tl.constexpr,
):
    # Single-program path for nnz <= CHUNK: build linear indices, sort the
    # (lin, position) keys once, then compute boundaries, group ids and
    # per-group sums directly.
    ar = tl.arange(0, CHUNK)
    m = ar < n
    lin = tl.zeros((CHUNK,), dtype=tl.int32)
    ix = tl.load(idx_ptr + ar, mask=m, other=0).to(tl.int32)
    lin += ix * st0
    if SDIM >= 2:
        ix = tl.load(idx_ptr + row1 + ar, mask=m, other=0).to(tl.int32)
        lin += ix * st1
    if SDIM >= 3:
        ix = tl.load(idx_ptr + row2 + ar, mask=m, other=0).to(tl.int32)
        lin += ix * st2
    v = tl.load(v_ptr + ar, mask=m, other=0).to(ACC)
    key = (lin.to(tl.int64) << 32) | ar.to(tl.int64)
    key = tl.where(m, key, 0x7FFFFFFFFFFFFFFF)
    ks = tl.sort(key, 0)
    lin_s = (ks >> 32).to(tl.int32)
    pos_s = ks & 0xFFFFFFFF
    pos_c = tl.minimum(pos_s, CHUNK - 1)
    v_s = tl.gather(v, pos_c, 0)
    lin_prev = tl.gather(lin_s, tl.maximum(ar - 1, 0), 0)
    boundary = (ar == 0) | (lin_s != lin_prev)
    bm = tl.where(m & boundary, 1, 0)
    g = tl.cumsum(bm) - 1
    tl.atomic_add(sum_ptr + g, v_s, mask=m)
    lin64 = lin_s.to(tl.int64)
    if SDIM >= 1:
        d0 = (lin64 // st0) % sh0
        tl.store(oidx_ptr + g, d0, mask=m & boundary)
    if SDIM >= 2:
        d1 = (lin64 // st1) % sh1
        tl.store(oidx_ptr + n + g, d1, mask=m & boundary)
    if SDIM >= 3:
        d2 = (lin64 // st2) % sh2
        tl.store(oidx_ptr + 2 * n + g, d2, mask=m & boundary)
    tl.store(m_ptr, tl.sum(bm))


@triton.jit
def _hist0_kernel(
    idx_ptr,
    a_ptr,
    ghist_ptr,
    phist_ptr,
    n,
    row1,
    row2,
    st0,
    st1,
    st2,
    NCHUNK: tl.constexpr,
    CHUNK: tl.constexpr,
    SDIM: tl.constexpr,
    NBINS: tl.constexpr,
    DIGBITS: tl.constexpr,
):
    # Build the linear-index array a[i] and the digit-0 histogram in one pass
    # over the raw indices.
    pid = tl.program_id(0)
    rngN = tl.arange(0, NBINS)
    ar = tl.arange(0, CHUNK)
    r = tl.zeros((NBINS,), dtype=tl.int32)
    for c in tl.static_range(NCHUNK):
        i = pid * (NCHUNK * CHUNK) + c * CHUNK + ar
        m = i < n
        lin = tl.zeros((CHUNK,), dtype=tl.int32)
        ix = tl.load(idx_ptr + i, mask=m, other=0).to(tl.int32)
        lin += ix * st0
        if SDIM >= 2:
            ix = tl.load(idx_ptr + row1 + i, mask=m, other=0).to(tl.int32)
            lin += ix * st1
        if SDIM >= 3:
            ix = tl.load(idx_ptr + row2 + i, mask=m, other=0).to(tl.int32)
            lin += ix * st2
        tl.store(a_ptr + i, lin, mask=m)
        digit = lin & (NBINS - 1)
        digit_h = tl.where(m, digit, NBINS - 1)
        h = tl.histogram(digit_h, NBINS)
        cnt = tl.sum(m.to(tl.int32))
        h = tl.where(rngN == NBINS - 1, h - (CHUNK - cnt), h)
        r += h
    tl.atomic_add(ghist_ptr + rngN, r)
    tl.store(phist_ptr + pid * NBINS + rngN, r)


@triton.jit
def _hist_kernel(
    a_ptr,
    ghist_ptr,
    phist_ptr,
    n,
    NCHUNK: tl.constexpr,
    CHUNK: tl.constexpr,
    SHIFT: tl.constexpr,
    NBINS: tl.constexpr,
    DIGBITS: tl.constexpr,
):
    # Histogram of the digit (lin >> SHIFT) & (NBINS-1) over the index array.
    pid = tl.program_id(0)
    rngN = tl.arange(0, NBINS)
    ar = tl.arange(0, CHUNK)
    r = tl.zeros((NBINS,), dtype=tl.int32)
    for c in tl.static_range(NCHUNK):
        i = pid * (NCHUNK * CHUNK) + c * CHUNK + ar
        m = i < n
        a = tl.load(a_ptr + i, mask=m, other=0)
        digit = (a >> SHIFT) & (NBINS - 1)
        digit_h = tl.where(m, digit, NBINS - 1)
        h = tl.histogram(digit_h, NBINS)
        cnt = tl.sum(m.to(tl.int32))
        h = tl.where(rngN == NBINS - 1, h - (CHUNK - cnt), h)
        r += h
    tl.atomic_add(ghist_ptr + rngN, r)
    tl.store(phist_ptr + pid * NBINS + rngN, r)


@triton.jit
def _scan_kernel(
    ghist_ptr,
    phist_ptr,
    pbase_ptr,
    nprogs,
    BINSPP: tl.constexpr,
    QCHUNK: tl.constexpr,
    NBINS: tl.constexpr,
):
    # pbase[q, b] = exclusive prefix of the (bin, prog) count matrix in
    # (bin-major, prog) order.  Each program handles BINSPP bins.
    g = tl.program_id(0)
    rngN = tl.arange(0, NBINS)
    h = tl.load(ghist_ptr + rngN)
    for k in tl.static_range(BINSPP):
        b = g * BINSPP + k
        prefix_b = tl.sum(tl.where(rngN < b, h, 0))
        carry = 0
        for q0 in range(0, nprogs, QCHUNK):
            q = q0 + tl.arange(0, QCHUNK)
            mq = q < nprogs
            t = tl.load(phist_ptr + q * NBINS + b, mask=mq, other=0)
            e = tl.cumsum(t) - t + carry
            tl.store(pbase_ptr + q * NBINS + b, prefix_b + e, mask=mq)
            carry += tl.sum(t)


@triton.jit
def _scatter_kernel(
    a_ptr,
    a2_ptr,
    v_ptr,
    v2_ptr,
    pbase_ptr,
    ghist_ptr,
    phist_ptr,
    n,
    nprogs,
    NCHUNK: tl.constexpr,
    CHUNK: tl.constexpr,
    SHIFT: tl.constexpr,
    PSHIFT: tl.constexpr,
    FOLDSCAN: tl.constexpr,
    NBINS: tl.constexpr,
):
    # Stable scatter for one LSD radix digit: each sub-tile is sorted by
    # (digit, input position) with a 32-bit key; the (lin, value) payload is
    # gathered from the input arrays and written to its global destination
    # inside the digit's contiguous range.
    pid = tl.program_id(0)
    rngN = tl.arange(0, NBINS)
    ar = tl.arange(0, CHUNK)
    if FOLDSCAN:
        # Compute this program's pbase row directly from the histograms
        # (avoids a separate scan launch when the program count is small).
        h = tl.load(ghist_ptr + rngN)
        prefix = tl.cumsum(h) - h
        acc = tl.zeros((NBINS,), dtype=tl.int32)
        qo = tl.arange(0, 32)
        bo = tl.arange(0, NBINS)
        for q0 in range(0, nprogs, 32):
            qq = q0 + qo
            mq = (qq < pid) & (qq < nprogs)
            t = tl.load(
                phist_ptr + qq[:, None] * NBINS + bo[None, :],
                mask=mq[:, None],
                other=0,
            )
            acc += tl.sum(t, axis=0)
        pb = prefix + acc
    else:
        pb = tl.load(pbase_ptr + pid * NBINS + rngN)
    tbl = pb
    for c in tl.static_range(NCHUNK):
        i = pid * (NCHUNK * CHUNK) + c * CHUNK + ar
        m = i < n
        a = tl.load(a_ptr + i, mask=m, other=0)
        digit = (a >> SHIFT) & (NBINS - 1)
        digit_h = tl.where(m, digit, NBINS - 1)
        h = tl.histogram(digit_h, NBINS)
        cnt = tl.sum(m.to(tl.int32))
        h = tl.where(rngN == NBINS - 1, h - (CHUNK - cnt), h)
        base_c = tbl
        gstart_c = tl.cumsum(h) - h
        key = (digit << PSHIFT) | i
        key = tl.where(m, key, 0x7FFFFFFF)
        ks = tl.sort(key, 0)
        digit_s = (ks >> PSHIFT) & (NBINS - 1)
        pos_s = ks & ((1 << PSHIFT) - 1)
        m_s = pos_s < n
        a_s = tl.load(a_ptr + pos_s, mask=m_s, other=0)
        v_s = tl.load(v_ptr + pos_s, mask=m_s, other=0)
        gb = tl.gather(base_c, digit_s, 0)
        gs = tl.gather(gstart_c, digit_s, 0)
        dest = gb + (ar - gs)
        tl.store(a2_ptr + dest, a_s, mask=m_s)
        tl.store(v2_ptr + dest, v_s, mask=m_s)
        tbl += h


@triton.jit
def _bsum_kernel(a_ptr, bsum_ptr, n, CHUNK: tl.constexpr):
    pid = tl.program_id(0)
    ar = tl.arange(0, CHUNK)
    i = pid * CHUNK + ar
    m = i < n
    a = tl.load(a_ptr + i, mask=m, other=0)
    a_prev = tl.load(a_ptr + i - 1, mask=m & (i > 0), other=0)
    boundary = (i == 0) | (a != a_prev)
    s = tl.sum(tl.where(m & boundary, 1, 0))
    tl.store(bsum_ptr + pid, s)


@triton.jit
def _bscan_kernel(bsum_ptr, poff_ptr, m_ptr, nprogs, QCHUNK: tl.constexpr):
    carry = 0
    for q0 in range(0, nprogs, QCHUNK):
        q = q0 + tl.arange(0, QCHUNK)
        mq = q < nprogs
        t = tl.load(bsum_ptr + q, mask=mq, other=0)
        e = tl.cumsum(t) - t + carry
        tl.store(poff_ptr + q, e, mask=mq)
        carry += tl.sum(t)
    tl.store(m_ptr, carry)


@triton.jit
def _boundary_kernel(
    a_ptr,
    v_ptr,
    sum_ptr,
    oidx_ptr,
    poff_ptr,
    bsum_ptr,
    m_ptr,
    n,
    m,
    nnz,
    nprogs,
    sh0,
    sh1,
    sh2,
    st0,
    st1,
    st2,
    CHUNK: tl.constexpr,
    SDIM: tl.constexpr,
    ACC: tl.constexpr,
    FOLD: tl.constexpr,
    QCHUNK: tl.constexpr,
):
    pid = tl.program_id(0)
    if FOLD:
        # Compute the per-program boundary offset and the total group count
        # by scanning bsum (avoids a separate scan launch).
        poff = 0
        total = 0
        for q0 in range(0, nprogs, QCHUNK):
            q = q0 + tl.arange(0, QCHUNK)
            mq = q < nprogs
            t = tl.load(bsum_ptr + q, mask=mq, other=0)
            poff += tl.sum(tl.where(q < pid, t, 0))
            total += tl.sum(t)
        tl.store(m_ptr, total)
    else:
        poff = tl.load(poff_ptr + pid)
    ar = tl.arange(0, CHUNK)
    i = pid * CHUNK + ar
    mm = i < n
    a = tl.load(a_ptr + i, mask=mm, other=0)
    lin = a.to(tl.int64)
    a_prev = tl.load(a_ptr + i - 1, mask=mm & (i > 0), other=0)
    boundary = (i == 0) | (a != a_prev)
    bm = tl.where(mm & boundary, 1, 0)
    g = tl.cumsum(bm) - 1 + poff
    v = tl.load(v_ptr + i, mask=mm, other=0).to(ACC)
    tl.atomic_add(sum_ptr + g, v, mask=mm)
    if SDIM >= 1:
        d0 = (lin // st0) % sh0
        tl.store(oidx_ptr + g, d0, mask=mm & boundary)
    if SDIM >= 2:
        d1 = (lin // st1) % sh1
        tl.store(oidx_ptr + nnz + g, d1, mask=mm & boundary)
    if SDIM >= 3:
        d2 = (lin // st2) % sh2
        tl.store(oidx_ptr + 2 * nnz + g, d2, mask=mm & boundary)


@triton.jit
def _cast_fp_kernel(src_ptr, dst_ptr, m, BLOCK: tl.constexpr, DTYPE: tl.constexpr):
    ar = tl.arange(0, BLOCK)
    i = tl.program_id(0) * BLOCK + ar
    mm = i < m
    v = tl.load(src_ptr + i, mask=mm)
    tl.store(dst_ptr + i, v.to(DTYPE), mask=mm)


@triton.jit
def _cast_int_kernel(src_ptr, dst_ptr, m, BLOCK: tl.constexpr, DTYPE: tl.constexpr):
    ar = tl.arange(0, BLOCK)
    i = tl.program_id(0) * BLOCK + ar
    mm = i < m
    v = tl.load(src_ptr + i, mask=mm)
    tl.store(dst_ptr + i, v.to(DTYPE), mask=mm)


@triton.jit
def _cast_bool_kernel(src_ptr, dst_ptr, m, BLOCK: tl.constexpr):
    ar = tl.arange(0, BLOCK)
    i = tl.program_id(0) * BLOCK + ar
    mm = i < m
    v = tl.load(src_ptr + i, mask=mm)
    tl.store(dst_ptr + i, (v != 0).to(tl.int8), mask=mm)


def _ceil_div(a, b):
    return (a + b - 1) // b


def _emit_output(dtype, m, acc, sum_buf, oidx, shape, sparse_dim, dev):
    if dtype in (torch.float16, torch.bfloat16):
        oval = torch.empty(m, dtype=dtype, device=dev)
        dt = tl.float16 if dtype == torch.float16 else tl.bfloat16
        _cast_fp_kernel[(_ceil_div(m, 1024),)](
            sum_buf, oval, m, BLOCK=1024, DTYPE=dt, num_warps=4
        )
    elif dtype == torch.int16:
        oval = torch.empty(m, dtype=torch.int16, device=dev)
        _cast_int_kernel[(_ceil_div(m, 1024),)](
            sum_buf, oval, m, BLOCK=1024, DTYPE=tl.int16, num_warps=4
        )
    elif dtype == torch.int64:
        oval = torch.empty(m, dtype=torch.int64, device=dev)
        _cast_int_kernel[(_ceil_div(m, 1024),)](
            sum_buf, oval, m, BLOCK=1024, DTYPE=tl.int64, num_warps=4
        )
    elif dtype == torch.bool:
        oval_i8 = torch.empty(m, dtype=torch.int8, device=dev)
        _cast_bool_kernel[(_ceil_div(m, 1024),)](
            sum_buf, oval_i8, m, BLOCK=1024, num_warps=4
        )
        oval = oval_i8.view(torch.bool)
    else:  # float32, float64, int32
        oval = sum_buf
    out = torch.sparse_coo_tensor(oidx, oval, shape, device=dev)
    out._coalesced_(True)
    return out


def _coalesce(self: torch.Tensor) -> torch.Tensor:
    """Merge duplicate entries of an uncoalesced sparse COO tensor.

    Mirrors ``aten::_coalesce(Tensor self) -> Tensor``: sorts the index
    columns in lexicographic (row-major) order, adds together the values of
    duplicate columns and returns a fresh sparse COO tensor reporting
    ``is_coalesced() == True``. The input tensor is never modified and stays
    uncoalesced.

    The native op is a *strict* helper: its CPU/CUDA kernels start with the
    internal assertion ``!self.is_coalesced()`` (measured in
    runs/_coalesce/probe_native_cpu.log section 2 and
    probe_native_gpu.log section 2), so an already-coalesced input - including
    a zero-nnz tensor, which native reports as coalesced - raises RuntimeError
    here exactly as native does. ``aten::coalesce`` is the public entry point
    that implements the identity shortcut for already-coalesced inputs and
    then calls this op.

    Rejections (each disclosed in the report): non-COO layouts (native has no
    kernel and the dispatcher rejects them), hybrid COO with dense dims
    (native sums whole value rows; the supplied kernels accumulate 1-D values
    only), int8/uint8 and complex dtypes (native wraps via axpy; outside the
    submitted dtype ladder), and sparse_dim > 3 (the index linearization
    unrolls S=1..3).

    Multi-pass LSD radix sort over row-major linearized indices, followed
    by boundary detection, group-sum accumulation, index de-linearization
    and output construction.  Two side arrays are permuted through the sort
    passes: A (int32, linearized index) and V (dtype, value).  Each pass
    sorts sub-tiles by (digit, input-position) 32-bit keys; payloads are
    gathered from A and V and scattered into their digit-contiguous
    destinations.  Stability is what makes the LSD passes compose into a
    fully sorted array.  Digit width is workload-adaptive: 10-bit digits
    (2 passes) for small program counts with <=20-bit linear indices, 8-bit
    digits (3 passes) otherwise.
    """
    logger.debug("GEMS _COALESCE")
    # Native has kernels ONLY for the sparse-COO layout on this build (CPU +
    # CUDA); a dense or compressed-layout input reaches no kernel at all and
    # the dispatcher rejects it.  This guard mirrors that contract with the
    # class the repo convention uses for unsupported inputs.  It must run
    # BEFORE any metadata access: a strided tensor rejects here rather than
    # with whatever ``_nnz``/``_indices`` would raise.
    if self.layout != torch.sparse_coo:
        raise NotImplementedError(
            f"_coalesce is only implemented for sparse COO tensors, "
            f"but got layout {self.layout}"
        )
    if self.dense_dim() > 0:
        # Hybrid COO (values with trailing dense dims): native adds whole
        # value rows (``values.stride(0)`` blocks, SparseTensor.cpp axpy) but
        # the supplied kernels address ``val_ptr + entry`` with a scalar
        # offset and build a 1-D output value tensor, which
        # ``torch.sparse_coo_tensor`` rejects for a shape with dense dims.
        raise NotImplementedError(
            "_coalesce does not support hybrid COO tensors with dense "
            f"dimensions (sparse_dim={self.sparse_dim()}, "
            f"dense_dim={self.dense_dim()}); the submitted kernel accumulation "
            "is defined for 1-D values only"
        )
    dtype = self.dtype
    if dtype not in (
        torch.float16,
        torch.float32,
        torch.bfloat16,
        torch.float64,
        torch.int16,
        torch.int32,
        torch.int64,
        torch.bool,
    ):
        # int8/uint8 (wrap-around axpy in native) and the complex dtypes are
        # native-supported but outside the submitted kernels' dtype ladder;
        # rejected instead of silently producing a widened/wrapped result.
        raise NotImplementedError(
            f"_coalesce does not support dtype {dtype}; the submitted kernels "
            "cover float16/32/64, bfloat16, int16/32/64 and bool"
        )
    if self.sparse_dim() > 3:
        # The linear-index unrolling covers sparse_dim 1..3; a 4th-or-later
        # index row would silently drop out of the linear key, so the input
        # is rejected instead of merging columns that differ only in a later
        # dimension.
        raise NotImplementedError(
            f"_coalesce supports at most 3 sparse dimensions, but got "
            f"sparse_dim={self.sparse_dim()}"
        )
    if self.is_coalesced():
        # Native's strict-input contract, measured on both builds (CPU:
        # SparseTensor.cpp:628, CUDA: SparseCUDATensor.cu:45 - the internal
        # assertion ``!self.is_coalesced()``).  The public ``aten::coalesce``
        # is what implements the identity shortcut; this worker raises for an
        # already-coalesced input exactly as native does.
        raise RuntimeError(
            "!self.is_coalesced() INTERNAL ASSERT FAILED at "
            "flag_gems/ops/_coalesce.py: _coalesce expects an uncoalesced "
            "sparse COO tensor"
        )
    dev = self.device
    indices = self._indices()
    values = self._values()
    shape = tuple(self.shape)
    sparse_dim = self.sparse_dim()
    nnz = self._nnz()
    return _coalesce_kernels(dtype, dev, indices, values, shape, sparse_dim, nnz)


def _coalesce_kernels(dtype, dev, indices, values, shape, sparse_dim, nnz):
    """Run the radix/merge kernels for one uncoalesced COO input.

    Split out of the op body so every Triton launch sits inside a single
    ``torch_device_fn.device`` context (the device guard is a no-op context on
    a CPU-only host, where these kernels cannot run anyway).
    """
    if dev.type == "cpu":
        ctx = contextlib.nullcontext()
    else:
        ctx = torch_device_fn.device(dev)
    with ctx:
        return _coalesce_launch(dtype, dev, indices, values, shape, sparse_dim, nnz)


def _coalesce_launch(dtype, dev, indices, values, shape, sparse_dim, nnz):
    if nnz == 0:
        oi = torch.empty((sparse_dim, 0), dtype=torch.int64, device=dev)
        ov = torch.empty((0,), dtype=dtype, device=dev)
        out = torch.sparse_coo_tensor(oi, ov, shape, device=dev)
        out._coalesced_(True)
        return out

    if not indices.is_contiguous():
        indices = indices.contiguous()
    if not values.is_contiguous():
        values = values.contiguous()

    # Accumulation dtype per input dtype.
    if dtype == torch.float64:
        acc = torch.float64
        acc_tl = tl.float64
    elif dtype == torch.float32:
        acc = torch.float32
        acc_tl = tl.float32
    elif dtype in (torch.float16, torch.bfloat16):
        acc = torch.float32
        acc_tl = tl.float32
    else:  # int16, int32, int64 -> exact int32 accumulation (bool via cast)
        acc = torch.int32
        acc_tl = tl.int32

    # Row-major strides for the linear index.
    strides = [1] * sparse_dim
    for d in range(sparse_dim - 2, -1, -1):
        strides[d] = strides[d + 1] * shape[d + 1]

    CHUNK = _CHUNK

    # Single-program fast path for small nnz.
    if nnz <= CHUNK:
        row1 = nnz
        row2 = 2 * nnz
        sh0 = shape[0] if sparse_dim >= 1 else 1
        sh1 = shape[1] if sparse_dim >= 2 else 1
        sh2 = shape[2] if sparse_dim >= 3 else 1
        st0 = strides[0] if sparse_dim >= 1 else 1
        st1 = strides[1] if sparse_dim >= 2 else 1
        st2 = strides[2] if sparse_dim >= 3 else 1
        sum_buf = torch.zeros(nnz, dtype=acc, device=dev)
        oidx = torch.empty((sparse_dim, nnz), dtype=torch.int64, device=dev)
        m_buf = torch.empty(1, dtype=torch.int32, device=dev)
        _small_kernel[(1,)](
            indices,
            values,
            sum_buf,
            oidx,
            m_buf,
            nnz,
            row1,
            row2,
            sh0,
            sh1,
            sh2,
            st0,
            st1,
            st2,
            CHUNK=CHUNK,
            SDIM=sparse_dim,
            ACC=acc_tl,
            num_warps=8,
        )
        m = int(m_buf.item())
        return _emit_output(
            dtype, m, acc, sum_buf[:m], oidx[:, :m].contiguous(), shape, sparse_dim, dev
        )

    nchunk = max(1, min(8, _ceil_div(nnz, CHUNK * 1024)))
    nprogs = _ceil_div(nnz, CHUNK * nchunk)
    nprogs_b = _ceil_div(nnz, CHUNK)

    row1 = nnz
    row2 = 2 * nnz
    sh0 = shape[0] if sparse_dim >= 1 else 1
    sh1 = shape[1] if sparse_dim >= 2 else 1
    sh2 = shape[2] if sparse_dim >= 3 else 1
    st0 = strides[0] if sparse_dim >= 1 else 1
    st1 = strides[1] if sparse_dim >= 2 else 1
    st2 = strides[2] if sparse_dim >= 3 else 1

    a = torch.empty(nnz, dtype=torch.int32, device=dev)
    a2 = torch.empty(nnz, dtype=torch.int32, device=dev)
    vbuf = [
        torch.empty(nnz, dtype=dtype, device=dev),
        torch.empty(nnz, dtype=dtype, device=dev),
    ]

    # Radix configuration: 10-bit/2-pass for small program counts with short
    # linear keys (the 1024-bin histogram is cheap at nprogs<=256, and the
    # parallel scan makes the 1024-bin prefix affordable); otherwise 8-bit.
    max_lin = strides[0] * shape[0] - 1
    nbits = max(1, max_lin.bit_length())
    digbits = 10 if (nbits <= 20 and nprogs <= 256) else 8
    nbins = 1 << digbits
    npasses = _ceil_div(nbits, digbits)
    pshift = max(1, nnz.bit_length())
    while digbits + pshift > 31:
        digbits -= 1
        nbins = 1 << digbits
        npasses = _ceil_div(nbits, digbits)

    src = a
    dst = a2
    v = values
    if digbits == 10:
        # The 1024-bin histogram path prefers smaller blocks (more blocks/SM).
        scat_warps = 8
    else:
        scat_warps = 8 if nnz > 1500000 else _WARPS_SCATTER
    # FOLDSCAN (in-kernel per-program prefix) is only profitable when the
    # redundant phist-row loads are small (nprogs <= 64); larger grids use the
    # dedicated scan kernel + pbase table instead.
    foldscan = nprogs <= 64
    pbase = torch.empty(nprogs * nbins, dtype=torch.int32, device=dev)
    gh_ph = torch.empty(nbins + nprogs * nbins, dtype=torch.int32, device=dev)
    for p in range(npasses):
        gh_ph.zero_()
        ghist = gh_ph[:nbins]
        phist = gh_ph[nbins:]
        shift = p * digbits
        if p == 0:
            _hist0_kernel[(nprogs,)](
                indices,
                src,
                ghist,
                phist,
                nnz,
                row1,
                row2,
                st0,
                st1,
                st2,
                NCHUNK=nchunk,
                CHUNK=CHUNK,
                SDIM=sparse_dim,
                NBINS=nbins,
                DIGBITS=digbits,
                num_warps=_WARPS_HIST,
            )
        else:
            _hist_kernel[(nprogs,)](
                src,
                ghist,
                phist,
                nnz,
                NCHUNK=nchunk,
                CHUNK=CHUNK,
                SHIFT=shift,
                NBINS=nbins,
                DIGBITS=digbits,
                num_warps=_WARPS_HIST,
            )
        if not foldscan:
            # One program per bin (BINSPP=1, grid=nbins) parallelizes the
            # prefix scan ~3x over the previous 8-bins-per-program layout.
            _scan_kernel[(nbins,)](
                ghist,
                phist,
                pbase,
                nprogs,
                BINSPP=1,
                QCHUNK=256,
                NBINS=nbins,
                num_warps=4,
            )
        _scatter_kernel[(nprogs,)](
            src,
            dst,
            v,
            vbuf[p & 1],
            pbase,
            ghist,
            phist,
            nnz,
            nprogs,
            NCHUNK=nchunk,
            CHUNK=CHUNK,
            SHIFT=shift,
            PSHIFT=pshift,
            FOLDSCAN=foldscan,
            NBINS=nbins,
            num_warps=scat_warps,
        )
        src, dst = dst, src
        v = vbuf[p & 1]

    bsum = torch.empty(nprogs_b, dtype=torch.int32, device=dev)
    _bsum_kernel[(nprogs_b,)](src, bsum, nnz, CHUNK=CHUNK, num_warps=_WARPS_BOUNDARY)

    foldb = nprogs_b <= 256
    if foldb:
        # Boundary kernel scans bsum itself; buffers are pre-sized to nnz and
        # sliced to m after the device sync.
        sum_buf = torch.zeros(nnz, dtype=acc, device=dev)
        oidx = torch.empty((sparse_dim, nnz), dtype=torch.int64, device=dev)
        m_buf = torch.empty(1, dtype=torch.int32, device=dev)
        _boundary_kernel[(nprogs_b,)](
            src,
            v,
            sum_buf,
            oidx,
            bsum,
            bsum,
            m_buf,
            nnz,
            0,
            nnz,
            nprogs_b,
            sh0,
            sh1,
            sh2,
            st0,
            st1,
            st2,
            CHUNK=CHUNK,
            SDIM=sparse_dim,
            ACC=acc_tl,
            FOLD=True,
            QCHUNK=128,
            num_warps=_WARPS_BOUNDARY,
        )
        m = int(m_buf.item())
        return _emit_output(
            dtype, m, acc, sum_buf[:m], oidx[:, :m].contiguous(), shape, sparse_dim, dev
        )
    else:
        poff = torch.empty(nprogs_b, dtype=torch.int32, device=dev)
        m_buf = torch.empty(1, dtype=torch.int32, device=dev)
        _bscan_kernel[(1,)](bsum, poff, m_buf, nprogs_b, QCHUNK=1024, num_warps=4)
        m = int(m_buf.item())
        sum_buf = torch.zeros(m, dtype=acc, device=dev)
        oidx = torch.empty((sparse_dim, m), dtype=torch.int64, device=dev)
        _boundary_kernel[(nprogs_b,)](
            src,
            v,
            sum_buf,
            oidx,
            poff,
            bsum,
            m_buf,
            nnz,
            m,
            m,
            nprogs_b,
            sh0,
            sh1,
            sh2,
            st0,
            st1,
            st2,
            CHUNK=CHUNK,
            SDIM=sparse_dim,
            ACC=acc_tl,
            FOLD=False,
            QCHUNK=128,
            num_warps=_WARPS_BOUNDARY,
        )
        return _emit_output(dtype, m, acc, sum_buf, oidx, shape, sparse_dim, dev)
