# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing permissions
# and limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def _copy_flat_kernel(src_ptr, dst_ptr, numel, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offsets = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offsets < numel
    vals = tl.load(src_ptr + offsets, mask=mask)
    tl.store(dst_ptr + offsets, vals, mask=mask)


@triton.jit
def _copy_strided_kernel(
    src_ptr,
    dst_ptr,
    sizes_ptr,
    strides_ptr,
    ndim,
    numel,
    BLOCK: tl.constexpr,
    MAXD: tl.constexpr,
):
    # Gather into a contiguous destination. The flat logical index is
    # row-major: dim 0 is the MOST significant digit, dim ndim-1 the least.
    # Decompose from the last dim down so dst position i receives the source
    # element at the row-major offset of i.
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    mask = offs < numel
    rem = offs.to(tl.int64)
    src_off = tl.zeros([BLOCK], dtype=tl.int64)
    for d in tl.static_range(MAXD):
        dd = ndim - 1 - d
        active = dd >= 0
        dd_safe = tl.maximum(dd, 0)
        size_d = tl.load(sizes_ptr + dd_safe)
        stride_d = tl.load(strides_ptr + dd_safe)
        size_safe = tl.where(active, size_d, 1)
        stride_safe = tl.where(active, stride_d, 0)
        idx_d = rem % size_safe
        rem = rem // size_safe
        src_off += idx_d.to(tl.int64) * stride_safe
    vals = tl.load(src_ptr + src_off, mask=mask)
    tl.store(dst_ptr + offs, vals, mask=mask)


# Tuned on H800 (see microbenchmarks): BLOCK=8192 with num_warps 8 for
# 2-byte dtypes and 4 for 4-byte dtypes reaches the highest streaming
# bandwidth; 1-byte and 8-byte dtypes use conservative configs.
_BLOCK_1B = 4096
_NW_1B = 4
_BLOCK_2B = 8192
_NW_2B = 8
_BLOCK_4B = 8192
_NW_4B = 4
_BLOCK_8B = 8192
_NW_8B = 8
_MAXD = 8


def _launch_flat(self: torch.Tensor, out: torch.Tensor) -> None:
    """Stream a contiguous ``self`` into ``out`` with the flat copy kernel.

    BLOCK/num_warps are the source's tuning table verbatim. The table selects
    on element size, so every branch is picked by real dtypes (1-byte:
    bool/int8/uint8; 2-byte: fp16/bf16/int16; 4-byte: fp32/int32; 8-byte:
    fp64/int64/complex).
    """
    numel = self.numel()
    es = self.element_size()
    if es <= 1:
        blk, nw = _BLOCK_1B, _NW_1B
    elif es == 2:
        blk, nw = _BLOCK_2B, _NW_2B
    elif es == 4:
        blk, nw = _BLOCK_4B, _NW_4B
    else:
        blk, nw = _BLOCK_8B, _NW_8B
    grid = (triton.cdiv(numel, blk),)
    _copy_flat_kernel[grid](self, out, numel, BLOCK=blk, num_warps=nw)


def _launch_strided(self: torch.Tensor, out: torch.Tensor) -> None:
    """Gather a non-contiguous ``self`` into the contiguous ``out``.

    ``sizes``/``strides`` are the source's device-side tables, and ``MAXD`` is
    the source's constant (8), verbatim. The kernel unrolls its decomposition
    over at most ``MAXD`` dims, so the supplied kernel covers inputs of rank
    <= 8; a higher-rank non-contiguous input is not addressed correctly (the
    outermost dims are skipped). This is inherited from the supplied
    implementation and is disclosed rather than silently patched; continuous
    ranks above 8 are unaffected because they take the flat path.
    """
    numel = self.numel()
    sizes = torch.tensor(list(self.shape), dtype=torch.int64, device=self.device)
    strides = torch.tensor(list(self.stride()), dtype=torch.int64, device=self.device)
    ndim = len(self.shape)
    grid = (triton.cdiv(numel, _BLOCK_4B),)
    _copy_strided_kernel[grid](
        self,
        out,
        sizes,
        strides,
        ndim,
        numel,
        BLOCK=_BLOCK_4B,
        MAXD=_MAXD,
    )


def _fw_primal_copy(self: torch.Tensor, level: int) -> torch.Tensor:
    """Copy the forward-AD primal of ``self`` at the given ``level``.

    Mirrors ``aten::_fw_primal_copy(Tensor self, int level) -> Tensor``: the
    view-copy partner of ``aten::_fw_primal``, and a ``view_copy``-tagged op.
    The generated ``CompositeExplicitAutogradNonFunctional`` body is
    ``_fw_primal(self, level).clone(memory_format=Contiguous)``, so the result
    is a **freshly allocated, contiguous** tensor holding ``self``'s values
    that never aliases the input -- unlike ``_fw_primal``, which returns a
    view.

    Semantics verified against native ATen on the target H20 build:

    - Element values are copied; ``data_ptr()`` differs from the input,
      ``_base is None``, and writes through the result leave the input
      untouched (and vice versa).
    - A non-contiguous input (slice/transpose/permute/expand with zero
      strides/``as_strided``) still yields a **contiguous** result, exactly
      like ``clone`` of a strided tensor.
    - ``level`` is accepted verbatim for a non-dual input: 0, 1, -1, 7, 100
      and ``2**31 - 1`` all return the same fresh copy. No level validation is
      duplicated here. Forward-AD rejection belongs to the autograd layer:
      a dual tensor raises ``NotImplementedError: Trying to use forward AD
      with aten::_fw_primal_copy that does not support it.`` there, above the
      backend key, so this implementation is never reached for such inputs
      (confirmed with a registration sentinel: a dual input raises without
      entering a CUDA-key kernel). Duplicating the check here would deviate
      from the native contract rather than reproduce it.
    - Empty, 0-dim and size-1 inputs are supported. The empty case allocates
      the fresh (contiguous) result and returns it without launching a kernel,
      since the grid would be empty.

    Dispatch: both overloads register on the plain backend (CUDA) key. The
    native composite additionally asserts
    ``InferenceMode::is_enabled() && self.is_inference()``, so on this build a
    plain normal-mode call raises ``RuntimeError`` on the native path; the
    CUDA registration serves every tensor/context combination instead, with
    the copy contract above. No extra dispatch key and no autograd delegation
    are needed: the op returns a fresh tensor, so it is not an
    ``_indices``-family aliasing view, and it has no tensor-free factory
    shape.
    """
    logger.debug("GEMS _FW_PRIMAL_COPY")
    numel = self.numel()
    if self.is_contiguous():
        out = torch.empty_like(self)
        if numel == 0:
            return out
        with torch_device_fn.device(self.device):
            _launch_flat(self, out)
        return out
    # Non-contiguous: materialize a fresh CONTIGUOUS copy, matching the
    # memory_format=Contiguous clone in the native composite.
    out = torch.empty_like(self, memory_format=torch.contiguous_format)
    if numel == 0:
        return out
    with torch_device_fn.device(self.device):
        _launch_strided(self, out)
    return out


def _fw_primal_copy_out(
    self: torch.Tensor, level: int, *, out: torch.Tensor
) -> torch.Tensor:
    """``aten::_fw_primal_copy.out``: write the primal copy into ``out``.

    Reproduces the generated out-variant, which is
    ``resize_out_helper(out, tmp); copy_arg(out, tmp)`` over the functional
    result ``tmp``: after the dtype and device checks the buffer is resized to
    the input shape, is written in place and is returned (identity, not a
    fresh allocation). A non-contiguous ``out`` is filled through a contiguous
    staging buffer and scattered back, the treatment the sibling out-variant
    copy operators in this repository use. The reference for the staging
    buffer is explicitly contiguous: ``empty_like(out)`` would inherit the
    caller's strides and the flat kernels would then write a contiguous
    stream into a strided layout.
    """
    logger.debug("GEMS _FW_PRIMAL_COPY_OUT")
    if out.dtype != self.dtype:
        raise RuntimeError(
            f"Expected out tensor to have dtype {self.dtype}, but got "
            f"{out.dtype} instead"
        )
    if out.device != self.device:
        # Native: "Expected out tensor to have device cuda:0, but got cpu
        # instead". The kernels can only write device memory, so this must be
        # rejected rather than silently staged through the host.
        raise RuntimeError(
            f"Expected out tensor to have device {self.device}, but got "
            f"{out.device} instead"
        )
    if tuple(out.shape) != tuple(self.shape):
        out.resize_(self.shape)
    numel = self.numel()
    if numel == 0:
        return out
    write = (
        out
        if out.is_contiguous()
        else torch.empty(self.shape, dtype=self.dtype, device=self.device)
    )
    with torch_device_fn.device(self.device):
        if self.is_contiguous():
            _launch_flat(self, write)
        else:
            _launch_strided(self, write)
    if write is not out:
        out.copy_(write)
    return out
