# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

logger = logging.getLogger(__name__)


def _indices(self: torch.Tensor) -> torch.Tensor:
    """Return the indices tensor of a sparse COO tensor as a zero-copy view.

    ``aten::_indices`` is a view op: the returned tensor aliases the internal
    indices storage of the sparse tensor, so mutations through the view are
    reflected in the original sparse tensor and vice versa. No per-element
    computation is involved, therefore no Triton kernel is needed and
    ``pointwise_dynamic``/``triton.jit`` are intentionally omitted.

    The implementation delegates to the native backend kernel. Registering
    this override on the backend dispatch keys directly would make
    ``torch.ops.aten._indices`` re-enter the override (RecursionError);
    registering on the autograd key and delegating inside
    ``torch._C._AutoDispatchBelowAutograd`` reaches the native kernel
    instead, preserving the zero-copy alias contract.

    Dense (strided) tensors are rejected with ``NotImplementedError`` since
    ``aten::_indices`` has no kernel for the strided layout.
    """
    logger.debug("GEMS _INDICES")
    if self.layout == torch.strided:
        raise NotImplementedError("aten::_indices is only supported for sparse tensors")
    with torch._C._AutoDispatchBelowAutograd():
        return torch.ops.aten._indices.default(self)
