# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def _grad_input_kernel(
    go,
    x,
    w,
    gi,
    N,
    C_in,
    C_out,
    H_in,
    W_in,
    H_out,
    W_out,
    kH,
    kW,
    sh,
    sw,
    ph,
    pw,
    HW_in,
    HW_out,
    KHW,
    num_ci_blocks,
    num_w_blocks,
    BLOCK_CI: tl.constexpr,
    BLOCK_H: tl.constexpr,
    BLOCK_W: tl.constexpr,
    IS_FP64: tl.constexpr,
):
    DT = tl.float64 if IS_FP64 else tl.float32
    pid0 = tl.program_id(0)
    pid1 = tl.program_id(1)
    pid2 = tl.program_id(2)
    n = pid0 // num_ci_blocks
    cib = pid0 % num_ci_blocks

    ci = cib * BLOCK_CI + tl.arange(0, BLOCK_CI)
    ci_mask = ci < C_in

    hi = pid1 * BLOCK_H + tl.arange(0, BLOCK_H)
    hi_mask = hi < H_in

    wi = pid2 * BLOCK_W + tl.arange(0, BLOCK_W)
    wi_mask = wi < W_in

    acc = tl.zeros([BLOCK_CI, BLOCK_H, BLOCK_W], dtype=DT)

    go_base = go + n * (C_out * HW_out)
    gi_base = (
        gi
        + n * (C_in * HW_in)
        + ci[:, None, None] * HW_in
        + hi[None, :, None] * W_in
        + wi[None, None, :]
    )

    for kh in range(0, kH):
        hnum = hi + ph - kh
        ho = hnum // sh
        hok = (hnum % sh == 0) & (ho >= 0) & (ho < H_out) & hi_mask
        for kw in range(0, kW):
            wnum = wi + pw - kw
            wo = wnum // sw
            wok = (wnum % sw == 0) & (wo >= 0) & (wo < W_out) & wi_mask
            gmask = hok[:, None] & wok[None, :]
            for co in range(0, C_out):
                gv = tl.load(
                    go_base + co * HW_out + ho[:, None] * W_out + wo[None, :],
                    mask=gmask,
                    other=0.0,
                )
                wv = tl.load(
                    w + co * (C_in * KHW) + ci * KHW + kh * kW + kw,
                    mask=ci_mask,
                    other=0.0,
                )
                acc += gv[None, :, :] * wv[:, None, None]

    gi_mask = ci_mask[:, None, None] & hi_mask[None, :, None] & wi_mask[None, None, :]
    tl.store(gi_base, acc, mask=gi_mask)


@triton.jit
def _grad_weight_scalar_kernel(
    go,
    x,
    w,
    gw,
    N,
    C_in,
    C_out,
    H_in,
    W_in,
    H_out,
    W_out,
    kH,
    kW,
    sh,
    sw,
    ph,
    pw,
    HW_in,
    HW_out,
    KHW,
    BLOCK_CI: tl.constexpr,
    BLOCK_W: tl.constexpr,
    IS_FP64: tl.constexpr,
):
    DT = tl.float64 if IS_FP64 else tl.float32
    pid_co = tl.program_id(0)
    pid_tap = tl.program_id(1)
    pid_ci = tl.program_id(2)

    kh = pid_tap // kW
    kw = pid_tap % kW

    ci = pid_ci * BLOCK_CI + tl.arange(0, BLOCK_CI)
    ci_mask = ci < C_in

    offs = tl.arange(0, BLOCK_W)
    acc = tl.zeros([BLOCK_CI], dtype=DT)

    go_base = go + pid_co * HW_out
    x_base = x + pid_ci * BLOCK_CI * HW_in

    for n in range(0, N):
        for ho in range(0, H_out):
            hi = ho * sh - ph + kh
            if (hi >= 0) & (hi < H_in):
                for w0 in range(0, W_out, BLOCK_W):
                    wo = w0 + offs
                    wi = wo * sw - pw + kw
                    m = (wo < W_out) & (wi >= 0) & (wi < W_in)
                    gv = tl.load(
                        go_base + n * (C_out * HW_out) + ho * W_out + wo,
                        mask=m,
                        other=0.0,
                    )
                    xv = tl.load(
                        x_base
                        + n * (C_in * HW_in)
                        + ci[:, None] * HW_in
                        + hi * W_in
                        + wi[None, :],
                        mask=m[None, :],
                        other=0.0,
                    )
                    acc += tl.sum(xv * gv[None, :], axis=1)
    gw_ptrs = gw + pid_co * (C_in * KHW) + ci * KHW + kh * kW + kw
    tl.store(gw_ptrs, acc, mask=ci_mask)


@triton.jit
def _grad_weight_kernel(
    go,
    x,
    w,
    gw,
    N,
    C_in,
    C_out,
    H_in,
    W_in,
    H_out,
    W_out,
    kH,
    kW,
    sh,
    sw,
    ph,
    pw,
    HW_in,
    HW_out,
    KHW,
    num_co_blocks,
    num_h_blocks,
    BLOCK_CO: tl.constexpr,
    BLOCK_CI: tl.constexpr,
    BLOCK_H: tl.constexpr,
    BLOCK_W: tl.constexpr,
    IS_FP64: tl.constexpr,
):
    DT = tl.float64 if IS_FP64 else tl.float32
    pid0 = tl.program_id(0)
    pid_ci = tl.program_id(1)
    pid_h = tl.program_id(2)

    pid_tap = pid0 // num_co_blocks
    pid_co = pid0 % num_co_blocks
    kh = pid_tap // kW
    kw = pid_tap % kW

    ci = pid_ci * BLOCK_CI + tl.arange(0, BLOCK_CI)
    ci_mask = ci < C_in

    if IS_FP64:
        # single-co FMA path (fp64 dot is not profitable for these shapes)
        co0 = pid_co * BLOCK_CO
        acc = tl.zeros([BLOCK_CI], dtype=DT)
        for n in range(0, N):
            for hb in range(0, BLOCK_H):
                ho = pid_h * BLOCK_H + hb
                hi = ho * sh - ph + kh
                if (ho < H_out) & (hi >= 0) & (hi < H_in):
                    for w0 in range(0, W_out, BLOCK_W):
                        wo = w0 + tl.arange(0, BLOCK_W)
                        wi = wo * sw - pw + kw
                        m = (wo < W_out) & (wi >= 0) & (wi < W_in)
                        gv = tl.load(
                            go + n * (C_out * HW_out) + co0 * HW_out + ho * W_out + wo,
                            mask=m,
                            other=0.0,
                        )
                        xv = tl.load(
                            x
                            + n * (C_in * HW_in)
                            + ci[:, None] * HW_in
                            + hi * W_in
                            + wi[None, :],
                            mask=m[None, :],
                            other=0.0,
                        )
                        acc += tl.sum(xv * gv[None, :], axis=1)
        gw_ptrs = gw + co0 * (C_in * KHW) + ci * KHW + kh * kW + kw
        tl.atomic_add(gw_ptrs, acc, mask=ci_mask)
    else:
        # tensor-core path: acc[co, ci] += sum_k G[co, k] * X[k, ci] over the
        # spatial tile (BLOCK_H x BLOCK_W flattened), accumulated over n and w-tiles.
        co = pid_co * BLOCK_CO + tl.arange(0, BLOCK_CO)
        co_mask = co < C_out
        acc = tl.zeros([BLOCK_CO, BLOCK_CI], dtype=tl.float32)

        k = tl.arange(0, BLOCK_H * BLOCK_W)
        h_local = k // BLOCK_W
        w_local = k % BLOCK_W

        for n in range(0, N):
            ho = pid_h * BLOCK_H + h_local
            hi = ho * sh - ph + kh
            for w0 in range(0, W_out, BLOCK_W):
                wo = w0 + w_local
                wi = wo * sw - pw + kw
                m = (
                    (ho < H_out)
                    & (hi >= 0)
                    & (hi < H_in)
                    & (wo < W_out)
                    & (wi >= 0)
                    & (wi < W_in)
                )
                g_ptrs = (
                    go
                    + n * (C_out * HW_out)
                    + co[:, None] * HW_out
                    + ho[None, :] * W_out
                    + wo[None, :]
                )
                x_ptrs = (
                    x
                    + n * (C_in * HW_in)
                    + ci[None, :] * HW_in
                    + hi[:, None] * W_in
                    + wi[:, None]
                )
                gv = tl.load(g_ptrs, mask=co_mask[:, None] & m[None, :], other=0.0)
                xv = tl.load(x_ptrs, mask=m[:, None] & ci_mask[None, :], other=0.0)
                acc += tl.dot(gv, xv, input_precision="tf32")

        gw_ptrs = gw + co[:, None] * (C_in * KHW) + ci[None, :] * KHW + kh * kW + kw
        tl.atomic_add(gw_ptrs, acc, mask=co_mask[:, None] & ci_mask[None, :])


@triton.jit
def _grad_bias_kernel(
    go,
    gb,
    N,
    C_out,
    H_out,
    W_out,
    HW_out,
    num_n_blocks,
    BLOCK: tl.constexpr,
    IS_FP64: tl.constexpr,
):
    DT = tl.float64 if IS_FP64 else tl.float32
    pid = tl.program_id(0)
    co = pid % C_out
    nb = pid // C_out
    offs = tl.arange(0, BLOCK)
    acc = tl.zeros([BLOCK], dtype=DT)
    go_base = go + co * HW_out
    for n in range(nb, N, num_n_blocks):
        for ho in range(0, H_out):
            v = tl.load(
                go_base + n * (C_out * HW_out) + ho * W_out + offs,
                mask=offs < W_out,
                other=0.0,
            )
            acc += v
    tl.atomic_add(gb + co, tl.sum(acc))


@triton.jit
def _grad_bias_single_kernel(
    go,
    gb,
    N,
    C_out,
    H_out,
    W_out,
    HW_out,
    BLOCK: tl.constexpr,
    IS_FP64: tl.constexpr,
):
    DT = tl.float64 if IS_FP64 else tl.float32
    co = tl.program_id(0)
    offs = tl.arange(0, BLOCK)
    acc = tl.zeros([BLOCK], dtype=DT)
    go_base = go + co * HW_out
    for n in range(0, N):
        for ho in range(0, H_out):
            v = tl.load(
                go_base + n * (C_out * HW_out) + ho * W_out + offs,
                mask=offs < W_out,
                other=0.0,
            )
            acc += v
    tl.store(gb + co, tl.sum(acc))


@triton.jit
def _cast_bias_kernel(
    gb_acc,
    gb,
    C_out,
):
    co = tl.program_id(0)
    v = tl.load(gb_acc + co)
    tl.store(gb + co, v)


def _slow_conv2d_backward(
    grad_output,
    self,
    weight,
    kernel_size,
    stride,
    padding,
    output_mask=None,
) -> tuple:
    """Triple-output backward of the slow 2-D convolution, mirroring
    ``aten::_slow_conv2d_backward.output_mask(Tensor grad_output, Tensor self,
    Tensor weight, SymInt[2] kernel_size, SymInt[2] stride, SymInt[2] padding,
    bool[3] output_mask) -> (Tensor grad_input, Tensor grad_weight,
    Tensor grad_bias)``.

    ``grad_output`` is ``(N, C_out, H_out, W_out)``, ``self`` is
    ``(N, C_in, H, W)`` and ``weight`` is ``(C_out, C_in, KH, KW)``. Each of the
    three outputs is selectable through ``output_mask``; a deselected output is
    returned as ``None``. Six Triton kernels implement it: a direct
    grad-input sweep, two grad-weight kernels (a small-spatial per-tap FMA
    variant and an implicit-GEMM tensor-core variant whose fp64 branch uses a
    single-``co`` FMA loop), two grad-bias reductions (a split-N atomic variant
    and a single-program direct-store variant) and a tiny fp32->low-precision
    cast kernel used when a float16/bfloat16 grad_bias is accumulated in fp32.

    The grad-weight implicit-GEMM kernel accumulates into its output with
    ``tl.atomic_add``, so the grad_weight buffer is zero-initialized here; the
    grad-bias split kernel is likewise accumulated atomically.

    Native validates the operand shapes before it reads a single element and
    rejects every shape/dtype combination the kernels cannot index safely;
    those checks are mirrored here so the GPU path rejects the same inputs with
    the same exception class (see the accuracy tests). Without them the supplied
    source would either crash while unpacking a wrong-rank tensor, or silently
    read ``weight``/``grad_output`` out of bounds.

    One dispatch guard was added over the supplied source (the kernels
    themselves are unchanged): for ``C_in == 1`` the implicit-GEMM grad-weight
    kernel's ``tl.dot`` tile has an N extent of 1, which Triton mis-lowers --
    every grad_weight element came out exactly double the reference -- so that
    degenerate case is routed to the scalar FMA kernel, which the source itself
    uses for small spatial extents and which computes the same reduction
    correctly (probe job ``_slow_conv2d_backward-other-a1-2a842335``).
    """
    logger.debug("GEMS _SLOW_CONV2D_BACKWARD")

    # Rank first (native checks the input rank before it touches the weight).
    if grad_output.dim() != 4:
        raise RuntimeError(
            f"Expected 4D input tensor, but got {list(grad_output.shape)}"
        )
    if self.dim() != 4:
        raise RuntimeError(f"Expected 4D input tensor, but got {list(self.shape)}")

    go = grad_output
    x = self
    w = weight

    N, C_out, H_out, W_out = go.shape
    C_in = x.shape[1]
    H_in, W_in = x.shape[2], x.shape[3]

    kH, kW = (int(kernel_size[0]), int(kernel_size[1]))
    sh, sw = (int(stride[0]), int(stride[1]))
    ph, pw = (int(padding[0]), int(padding[1]))

    # Native derives the expected grad_output spatial extent from the input,
    # kernel, stride and padding, and rejects a mismatch before doing any work
    # ("Expected grad_output dim 2 to have size <E> but got <A>"). This also
    # covers a kernel larger than the padded input, where the extent is
    # non-positive.
    expected_h = (H_in + 2 * ph - kH) // sh + 1
    expected_w = (W_in + 2 * pw - kW) // sw + 1
    if H_out != expected_h:
        raise RuntimeError(
            f"Expected grad_output dim 2 to have size {expected_h} but got {H_out}"
        )
    if W_out != expected_w:
        raise RuntimeError(
            f"Expected grad_output dim 3 to have size {expected_w} but got {W_out}"
        )

    if w.dim() != 4:
        raise RuntimeError(f"Expected 4D weight tensor, but got {list(w.shape)}")
    if w.shape[0] != C_out:
        raise RuntimeError(
            f"Expected weight dim 0 to have size {C_out} but got {w.shape[0]}"
        )
    if w.shape[1] != C_in:
        raise RuntimeError(
            f"Expected input dim 1 to have size {w.shape[1]} but got {C_in}"
        )

    # Native rejects a dtype mismatch between the three operands ("expected
    # scalar type <A> but found <B>"); the kernels read all three through one
    # element type, so a mismatch would silently reinterpret the odd operand.
    if x.dtype != go.dtype:
        raise RuntimeError(f"expected scalar type {go.dtype} but found {x.dtype}")
    if w.dtype != go.dtype:
        raise RuntimeError(f"expected scalar type {go.dtype} but found {w.dtype}")

    if output_mask is not None:
        if len(output_mask) != 3:
            raise RuntimeError(
                "Expected output_mask to have 3 elements but got " f"{len(output_mask)}"
            )
        need_gi, need_gw, need_gb = (
            bool(output_mask[0]),
            bool(output_mask[1]),
            bool(output_mask[2]),
        )
    else:
        # A plain Python-level call without a mask computes all three outputs.
        # (The registered ``.output_mask`` dispatch overload always passes one.)
        need_gi, need_gw, need_gb = True, True, True

    device = go.device
    dtype = go.dtype
    is_fp64 = dtype == torch.float64

    if dtype not in (torch.float16, torch.bfloat16, torch.float32, torch.float64):
        raise RuntimeError(
            f'"_slow_conv2d_backward_cuda" not implemented for '
            f"'{str(dtype).replace('torch.', '').capitalize()}'"
        )

    # The kernels index every operand through the plain contiguous layout;
    # native's CUDA kernel accepts strided operands (and returns contiguous
    # outputs), so materialize contiguous copies instead of rejecting.
    go = go.contiguous()
    x = x.contiguous()
    w = w.contiguous()

    if need_gi:
        gi = torch.empty_like(x)
    else:
        gi = None
    if need_gw:
        # zero-initialized because the grad_weight kernel accumulates via atomic_add
        gw = torch.zeros_like(w)
    else:
        gw = None
    if need_gb:
        gb = torch.zeros(C_out, device=device, dtype=dtype)
    else:
        gb = None

    HW_in = H_in * W_in
    HW_out = H_out * W_out
    KHW = kH * kW

    if need_gi:
        BLOCK_CI = min(triton.next_power_of_2(C_in), 32)
        BLOCK_H = 4
        BLOCK_W = 32
        num_ci_blocks = triton.cdiv(C_in, BLOCK_CI)
        num_w_blocks = triton.cdiv(W_in, BLOCK_W)
        grid = (N * num_ci_blocks, triton.cdiv(H_in, BLOCK_H), num_w_blocks)
        with torch_device_fn.device(x.device):
            _grad_input_kernel[grid](
                go,
                x,
                w,
                gi,
                N,
                C_in,
                C_out,
                H_in,
                W_in,
                H_out,
                W_out,
                kH,
                kW,
                sh,
                sw,
                ph,
                pw,
                HW_in,
                HW_out,
                KHW,
                num_ci_blocks,
                num_w_blocks,
                BLOCK_CI=BLOCK_CI,
                BLOCK_H=BLOCK_H,
                BLOCK_W=BLOCK_W,
                IS_FP64=is_fp64,
                num_warps=8,
            )

    if need_gw:
        # ``tl.dot`` mis-lowers this kernel's tensor-core accumulation when its
        # N tile (BLOCK_CI) is 1: for C_in == 1 every grad_weight element comes
        # out exactly DOUBLE the reference (measured on H20, fp16/fp32/bf16,
        # rel err ~1.0 -- probe job _slow_conv2d_backward-other-a1-2a842335;
        # C_in >= 2 is unaffected and fp64 takes the FMA branch anyway). The
        # scalar FMA kernel below computes the same reduction correctly, so
        # route that degenerate case to it instead of the dot kernel.
        if H_out * W_out <= 16 or C_in == 1:
            # tiny spatial extent: the tensor-core K tile (8x64) would be almost
            # entirely masked; use the direct per-(co,tap,ci) FMA kernel instead
            BLOCK_CI = min(triton.next_power_of_2(C_in), 32)
            BLOCK_W = 128
            num_ci_blocks = triton.cdiv(C_in, BLOCK_CI)
            grid = (C_out, kH * kW, num_ci_blocks)
            with torch_device_fn.device(x.device):
                _grad_weight_scalar_kernel[grid](
                    go,
                    x,
                    w,
                    gw,
                    N,
                    C_in,
                    C_out,
                    H_in,
                    W_in,
                    H_out,
                    W_out,
                    kH,
                    kW,
                    sh,
                    sw,
                    ph,
                    pw,
                    HW_in,
                    HW_out,
                    KHW,
                    BLOCK_CI=BLOCK_CI,
                    BLOCK_W=BLOCK_W,
                    IS_FP64=is_fp64,
                    num_warps=4,
                )
        elif is_fp64:
            BLOCK_CO = 1
            BLOCK_CI = min(triton.next_power_of_2(C_in), 16)
            BLOCK_H = 8
            BLOCK_W = 64
            num_co_blocks = triton.cdiv(C_out, BLOCK_CO)
            num_ci_blocks = triton.cdiv(C_in, BLOCK_CI)
            num_h_blocks = triton.cdiv(H_out, BLOCK_H)
            grid = (kH * kW * num_co_blocks, num_ci_blocks, num_h_blocks)
            with torch_device_fn.device(x.device):
                _grad_weight_kernel[grid](
                    go,
                    x,
                    w,
                    gw,
                    N,
                    C_in,
                    C_out,
                    H_in,
                    W_in,
                    H_out,
                    W_out,
                    kH,
                    kW,
                    sh,
                    sw,
                    ph,
                    pw,
                    HW_in,
                    HW_out,
                    KHW,
                    num_co_blocks,
                    num_h_blocks,
                    BLOCK_CO=BLOCK_CO,
                    BLOCK_CI=BLOCK_CI,
                    BLOCK_H=BLOCK_H,
                    BLOCK_W=BLOCK_W,
                    IS_FP64=is_fp64,
                    num_warps=8,
                )
        else:
            BLOCK_CO = 16
            BLOCK_CI = min(triton.next_power_of_2(C_in), 16)
            BLOCK_H = 8
            BLOCK_W = 64
            num_co_blocks = triton.cdiv(C_out, BLOCK_CO)
            num_ci_blocks = triton.cdiv(C_in, BLOCK_CI)
            num_h_blocks = triton.cdiv(H_out, BLOCK_H)
            grid = (kH * kW * num_co_blocks, num_ci_blocks, num_h_blocks)
            with torch_device_fn.device(x.device):
                _grad_weight_kernel[grid](
                    go,
                    x,
                    w,
                    gw,
                    N,
                    C_in,
                    C_out,
                    H_in,
                    W_in,
                    H_out,
                    W_out,
                    kH,
                    kW,
                    sh,
                    sw,
                    ph,
                    pw,
                    HW_in,
                    HW_out,
                    KHW,
                    num_co_blocks,
                    num_h_blocks,
                    BLOCK_CO=BLOCK_CO,
                    BLOCK_CI=BLOCK_CI,
                    BLOCK_H=BLOCK_H,
                    BLOCK_W=BLOCK_W,
                    IS_FP64=is_fp64,
                    num_warps=8,
                )

    if need_gb:
        if N * H_out * W_out < 64:
            # tiny reduction: one program per co, direct store (single rounding)
            with torch_device_fn.device(x.device):
                _grad_bias_single_kernel[(C_out,)](
                    go,
                    gb,
                    N,
                    C_out,
                    H_out,
                    W_out,
                    HW_out,
                    BLOCK=256,
                    IS_FP64=is_fp64,
                    num_warps=2,
                )
        else:
            # split the N reduction across programs; partials accumulate in
            # fp32/fp64 so fp16/bf16 outputs only round once (a tiny cast kernel)
            if dtype == torch.float32 or is_fp64:
                gb_target = gb
                need_gb_cast = False
            else:
                gb_target = torch.zeros(C_out, device=device, dtype=torch.float32)
                need_gb_cast = True
            num_n_blocks = min(N, 8)
            grid = (C_out * num_n_blocks,)
            with torch_device_fn.device(x.device):
                _grad_bias_kernel[grid](
                    go,
                    gb_target,
                    N,
                    C_out,
                    H_out,
                    W_out,
                    HW_out,
                    num_n_blocks,
                    BLOCK=256,
                    IS_FP64=is_fp64,
                    num_warps=2,
                )
                if need_gb_cast:
                    _cast_bias_kernel[(C_out,)](
                        gb_target,
                        gb,
                        C_out,
                        num_warps=1,
                    )

    return gi, gw, gb
