# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch

logger = logging.getLogger(__name__)


def atleast_2d(self: torch.Tensor) -> torch.Tensor:
    """Return the input as a tensor with at least two dimensions.

    Mirrors ``aten::atleast_2d(Tensor self) -> Tensor``. The result never
    depends on stored element data and no data is ever copied or mutated,
    so this is a pure host-side view operation and no device kernel is
    launched. Semantics by rank (verified against native ATen on H20):

    - ``ndim >= 2``: native returns the input tensor *itself* -- the very
      same Python object, not a fresh view wrapper (``res is self``,
      ``res._is_view() == False``, ``res._base is None``). This
      implementation mirrors that exactly by returning ``self`` unchanged.
    - ``ndim == 1``: a zero-copy view with a leading singleton dimension
      (shape ``(1, N)``), sharing storage with ``self``.
    - ``ndim == 0``: a zero-copy view with two leading singleton dimensions
      (shape ``(1, 1)``), sharing storage with ``self``.

    Args:
        self (torch.Tensor): Input tensor of any rank.

    Returns:
        torch.Tensor: A 2-D (or higher) tensor viewing the same data.
    """
    logger.debug("GEMS ATLEAST_2D")
    if self.dim() >= 2:
        # Native atleast_2d is an identity for tensors that are already 2-D
        # or higher: it hands back the input object itself, so no view
        # wrapper is created here either.
        return self
    if self.dim() == 1:
        return self.unsqueeze(0)
    return self.unsqueeze(0).unsqueeze(0)
