# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

logger = logging.getLogger(__name__)

# C++ layout names as printed by native ATen in the rejection message of
# ``aten::ccol_indices`` (ATen/SparseCsrTensorUtils.h dispatch macro). Only the
# column-compressed layouts (CSC/BSC) carry a compressed-column-index buffer;
# the mapping below covers every remaining standard layout so the mirrored
# message is byte-identical to the native one on this build.
_NON_COL_COMPRESSED_LAYOUT_NAMES = {
    torch.strided: "Strided",
    torch.sparse_coo: "Sparse",
    torch.sparse_csr: "SparseCsr",
    torch.sparse_bsr: "SparseBsr",
}


def ccol_indices(self: torch.Tensor) -> torch.Tensor:
    """Return the compressed column indices of a CSC/BSC tensor as a zero-copy view.

    ``aten::ccol_indices(Tensor(a) self) -> Tensor(a)`` is a pure metadata
    accessor: the returned tensor, shaped ``batch_dims + (ncols + 1,)`` for CSC
    (``+ (n_col_blocks + 1,)`` for BSC), aliases the input tensor's internal
    compressed-column-index storage. Mutations written through the returned view
    are visible in the sparse tensor itself (and vice versa), and no per-element
    computation is involved, therefore no Triton kernel is needed and
    ``pointwise_dynamic``/``triton.jit`` are intentionally omitted.

    Layout coverage mirrors native ATen exactly (verified against native ATen on
    H20): only the column-compressed layouts CSC and BSC have a compressed-column
    buffer. CSR, BSR, COO and strided inputs are rejected with the native
    ``RuntimeError`` ("ccol_indices expected sparse column compressed tensor
    layout but got <Layout>"). The guard raises that identical message itself
    because delegation cannot reach the native check for those layouts: the
    general registrar also binds this implementation to the CUDA dispatch key,
    so re-dispatching a strided input would re-enter this override and recurse
    instead of surfacing the native error (measured: a same-key re-dispatch
    recurses; below-autograd delegation reaches the native kernel).

    For the supported layouts the implementation delegates to the native backend
    kernel. Registering this override on the backend dispatch keys directly would
    make ``torch.ops.aten.ccol_indices`` re-enter the override for CSC/BSC inputs
    (RecursionError); registering on the autograd key and delegating inside
    ``torch._C._AutoDispatchBelowAutograd`` reaches the native ``SparseCsrCUDA``
    kernel instead, preserving the zero-copy alias contract.
    """
    logger.debug("GEMS CCOL_INDICES")
    if self.layout not in (torch.sparse_csc, torch.sparse_bsc):
        layout_name = _NON_COL_COMPRESSED_LAYOUT_NAMES.get(self.layout)
        if layout_name is None:
            # Unknown layout: fall through to the native op, which reports it.
            with torch._C._AutoDispatchBelowAutograd():
                return torch.ops.aten.ccol_indices.default(self)
        raise RuntimeError(
            "ccol_indices expected sparse column compressed tensor layout "
            f"but got {layout_name}"
        )
    with torch._C._AutoDispatchBelowAutograd():
        return torch.ops.aten.ccol_indices.default(self)
