# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def _col_indices_copy_unmasked(src, dst, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    v = tl.load(src + offs, eviction_policy="evict_first")
    tl.store(dst + offs, v, eviction_policy="evict_first")


@triton.jit
def _col_indices_copy_masked(src, dst, n, BLOCK: tl.constexpr):
    pid = tl.program_id(0)
    offs = pid * BLOCK + tl.arange(0, BLOCK)
    m = offs < n
    v = tl.load(src + offs, mask=m, eviction_policy="evict_first")
    tl.store(dst + offs, v, mask=m, eviction_policy="evict_first")


# C++ layout names as printed by native ATen in the rejection message of
# ``aten::col_indices_copy`` (ATen/SparseCsrTensorUtils.h dispatch macro).
# Only row-compressed layouts (CSR/BSR) carry a column-indices buffer; the
# mapping below covers the remaining standard layouts whose native kernel
# rejects the input, so the mirrored message is byte-identical to it.
_NON_ROW_COMPRESSED_LAYOUT_NAMES = {
    torch.strided: "Strided",
    torch.sparse_csc: "SparseCsc",
    torch.sparse_bsc: "SparseBsc",
}

# C++ scalar-type names as printed by the dispatcher in the out-buffer dtype
# check ("Expected out tensor to have dtype <name>, but got <name> instead"),
# matching the native message for the realistic buffer dtypes. Unknown dtypes
# fall back to the Python dtype name.
_CPP_DTYPE_NAMES = {
    torch.bool: "bool",
    torch.uint8: "unsigned char",
    torch.int8: "signed char",
    torch.int16: "short int",
    torch.int32: "int",
    torch.int64: "long int",
    torch.float16: "c10::Half",
    torch.bfloat16: "c10::BFloat16",
    torch.float32: "float",
    torch.float64: "double",
    torch.complex64: "c10::complex<float>",
    torch.complex128: "c10::complex<double>",
}


def _cpp_dtype_name(dtype: torch.dtype) -> str:
    return _CPP_DTYPE_NAMES.get(dtype, str(dtype).replace("torch.", ""))


def _row_compressed_col_indices(self: torch.Tensor) -> torch.Tensor:
    """Return the column-index buffer of a row-compressed input, or reject it.

    ``aten::col_indices_copy`` only accepts the row-compressed layouts CSR and
    BSR. Every other layout is rejected by native ATen before any element is
    touched, and the rejection differs by layout class:

    - ``torch.strided`` / ``torch.sparse_csc`` / ``torch.sparse_bsc`` reach the
      native layout check and raise ``RuntimeError`` ("col_indices expected
      sparse row compressed tensor layout but got <Layout>"). The guard raises
      that identical message itself. Delegating instead would be unsafe: the
      general registrar also binds this implementation to the dense backend
      dispatch key, so re-dispatching a strided input would re-enter this
      override and recurse rather than surface the native error.
    - ``torch.sparse_coo`` has no dispatcher kernel at all for this operator
      (the native error lists SparseCsr backends only), so it raises
      ``NotImplementedError``. The same applies to layouts without a named
      kernel (e.g. jagged/nested or mkldnn inputs).

    The returned buffer is the live internal ``col_indices`` view. It can be a
    strided view when the sparse tensor was built from a non-contiguous index
    tensor; it is materialized here because the copy kernel addresses elements
    linearly and native returns a contiguous result.
    """
    if self.layout not in (torch.sparse_csr, torch.sparse_bsr):
        layout_name = _NON_ROW_COMPRESSED_LAYOUT_NAMES.get(self.layout)
        if layout_name is not None:
            raise RuntimeError(
                "col_indices expected sparse row compressed tensor layout "
                f"but got {layout_name}"
            )
        raise NotImplementedError(
            "aten::col_indices_copy is only supported for sparse row compressed "
            f"tensors, but got {self.layout}"
        )
    src = self.col_indices()
    if not src.is_contiguous():
        src = src.contiguous()
    return src


def _launch_copy(src: torch.Tensor, dst: torch.Tensor) -> None:
    """Copy ``src`` into ``dst`` with the source's kernel-selection policy.

    Small buffers (fewer than 2e6 elements) use BLOCK=1024 / num_warps=4 and
    larger ones BLOCK=2048 / num_warps=8; a buffer whose element count is an
    exact multiple of BLOCK takes the unmasked kernel, every other size the
    masked one. Callers must guarantee ``src.numel() > 0``.
    """
    n = src.numel()
    if n >= 2_000_000:
        BLOCK = 2048
        nw = 8
    else:
        BLOCK = 1024
        nw = 4
    with torch_device_fn.device(src.device):
        if n % BLOCK == 0:
            _col_indices_copy_unmasked[(n // BLOCK,)](
                src, dst, BLOCK=BLOCK, num_warps=nw
            )
        else:
            _col_indices_copy_masked[(n // BLOCK + 1,)](
                src, dst, n, BLOCK=BLOCK, num_warps=nw
            )


def col_indices_copy(self: torch.Tensor) -> torch.Tensor:
    """Return a fresh copy of the column indices of a sparse compressed tensor.

    Mirrors ``aten::col_indices_copy(Tensor self) -> Tensor``: the native
    operator reads the internal ``col_indices`` buffer of a row-compressed
    sparse tensor and materializes it into newly allocated memory (equivalent
    to ``self.col_indices().clone()``), so the result never aliases the input
    and writing to it leaves the sparse tensor untouched. The result is a
    contiguous 1-D tensor of ``nnz`` elements (one entry per stored block for
    BSR) that keeps the buffer's own integer dtype -- int64 for the default
    construction, int32 when the sparse tensor was built from int32 index
    tensors. The values are copied verbatim, so unsorted or duplicated column
    indices are preserved.

    Layout coverage mirrors native ATen exactly (verified against native ATen
    on H20): only CSR and BSR carry a column-indices buffer. CSC, BSC and
    strided inputs raise the native ``RuntimeError``; COO and other layouts
    without a dispatcher kernel raise ``NotImplementedError``. See
    ``_row_compressed_col_indices`` for the guard.
    """
    logger.debug("GEMS COL_INDICES_COPY")
    src = _row_compressed_col_indices(self)
    out = torch.empty_like(src)
    if src.numel() == 0:
        return out
    _launch_copy(src, out)
    return out


def col_indices_copy_out(self: torch.Tensor, *, out: torch.Tensor) -> torch.Tensor:
    """Write the column indices of a sparse compressed tensor into ``out``.

    Mirrors ``aten::col_indices_copy.out(Tensor self, *, Tensor(a!) out) ->
    Tensor(a!)``: the values are written into the caller-provided buffer and
    the same buffer is returned (identity, not a fresh allocation).

    The out buffer follows the native contract measured on H20. The buffer is
    reshaped to the source shape first (native emits a deprecation warning
    while resizing a non-empty buffer, this implementation resizes silently;
    resizing a non-contiguous buffer materializes it, exactly as native does).
    A buffer whose element type differs from the source buffer is rejected
    with the native message; a non-contiguous buffer that already has the
    right shape still receives the correct values written through its strides,
    which is handled by staging the copy in scratch space and scattering it
    with ``copy_``.

    The accepted layouts are the same as for the functional form: CSR and BSR.
    """
    logger.debug("GEMS COL_INDICES_COPY_OUT")
    src = _row_compressed_col_indices(self)
    if out.dtype != src.dtype:
        raise RuntimeError(
            "Expected out tensor to have dtype "
            f"{_cpp_dtype_name(src.dtype)}, but got "
            f"{_cpp_dtype_name(out.dtype)} instead"
        )
    if out.device != src.device:
        raise RuntimeError(
            "col_indices_copy.out: input and output must be on the same device."
        )
    # The shape is corrected before anything is written, as native does: this
    # also materializes a non-contiguous buffer, so the contiguity decision
    # below sees the same tensor native would copy into.
    if out.shape != src.shape:
        out.resize_(src.shape)
    if src.numel() == 0:
        return out
    if out.is_contiguous():
        _launch_copy(src, out)
    else:
        # Strided destination: native writes the logical elements through the
        # buffer's strides, so stage the copy and scatter it into place.
        staged = torch.empty_like(src)
        _launch_copy(src, staged)
        out.copy_(staged)
    return out
