# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on the basis of the "AS IS"
# BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch

logger = logging.getLogger(__name__)


def dense_dim(self: torch.Tensor) -> int:
    """Return the number of dense dimensions of ``self``.

    Mirrors ``aten::dense_dim(Tensor self) -> int``. This is a pure
    layout-metadata query: the result never depends on stored element data,
    so it is computed from TensorImpl properties without re-dispatching the
    ``dense_dim`` operator itself (re-entering the dispatcher from inside a
    registered CUDA kernel would recurse into this implementation).

    Semantics by layout (verified against native ATen on H20):
    - ``torch.strided``: every dimension is dense, ``dense_dim == dim()``.
    - ``torch.sparse_coo``: ``sparse_dim`` equals ``self._indices().shape[0]``
      (the leading index-matrix dimension), so ``dense_dim == dim() -
      indices.shape[0]``. Hybrid COO tensors (values with trailing dense
      dimensions) are covered by the same formula.
    - Sparse compressed layouts (CSR/CSC/BSR/BSC): ``sparse_dim == 2`` by
      ATen contract, so ``dense_dim == dim() - 2``.
    """
    logger.debug("GEMS DENSE_DIM")
    if self.layout == torch.strided:
        return self.dim()
    if self.layout == torch.sparse_coo:
        return self.dim() - self._indices().shape[0]
    return self.dim() - 2
