# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS"
# BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)

_CB = 1024
_MIN_MAX_NDIM = 8

_TL_DTYPES = {
    torch.float16: tl.float16,
    torch.bfloat16: tl.bfloat16,
    torch.float32: tl.float32,
    torch.float64: tl.float64,
    torch.int8: tl.int8,
    torch.int16: tl.int16,
    torch.int32: tl.int32,
    torch.int64: tl.int64,
    torch.uint8: tl.uint8,
    torch.uint16: tl.uint16,
    torch.uint32: tl.uint32,
    torch.uint64: tl.uint64,
    torch.bool: tl.int1,
}


@triton.jit
def _rowloop_contig(
    inp_ptr,
    out_ptr,
    M,
    n,
    offset,
    flat_shift,
    CB: tl.constexpr,
    OUT_DTYPE: tl.constexpr,
):
    # One program per output row. Each row is filled in CB-wide contiguous
    # chunks: zeros everywhere except the single diagonal element, which
    # carries the input value.
    r = tl.program_id(0).to(tl.int64)
    diag_col = r + offset
    flat = r + flat_shift
    diag_ok = (flat >= 0) & (flat < n)
    v = tl.load(inp_ptr + flat, mask=diag_ok, other=0)
    base = r * M
    z = tl.zeros([CB], dtype=OUT_DTYPE)
    for c0 in range(0, M, CB):
        cols = (c0 + tl.arange(0, CB)).to(tl.int64)
        mask = cols < M
        is_diag = (cols == diag_col) & diag_ok
        val = tl.where(is_diag, v, z)
        tl.store(out_ptr + base + cols, val, mask=mask)


@triton.jit
def _rowloop_gather(
    inp_ptr,
    out_ptr,
    div_ptr,
    stride_ptr,
    M,
    n,
    offset,
    flat_shift,
    NDIM: tl.constexpr,
    MAX_NDIM: tl.constexpr,
    CB: tl.constexpr,
    OUT_DTYPE: tl.constexpr,
):
    # Same structure as _rowloop_contig but the input flat index is mapped to
    # the physical offset via per-dimension divisor/stride decomposition for
    # non-contiguous inputs.
    r = tl.program_id(0).to(tl.int64)
    diag_col = r + offset
    flat = r + flat_shift
    diag_ok = (flat >= 0) & (flat < n)
    if NDIM > 0:
        rem = flat
        phys = flat * 0
        for d in tl.static_range(MAX_NDIM):
            if d < NDIM:
                div = tl.load(div_ptr + d).to(tl.int64)
                st = tl.load(stride_ptr + d).to(tl.int64)
                c = rem // div
                phys += c * st
                rem = rem % div
    else:
        phys = flat
    v = tl.load(inp_ptr + phys, mask=diag_ok, other=0)
    base = r * M
    z = tl.zeros([CB], dtype=OUT_DTYPE)
    for c0 in range(0, M, CB):
        cols = (c0 + tl.arange(0, CB)).to(tl.int64)
        mask = cols < M
        is_diag = (cols == diag_col) & diag_ok
        val = tl.where(is_diag, v, z)
        tl.store(out_ptr + base + cols, val, mask=mask)


def diagflat(self: torch.Tensor, offset=0) -> torch.Tensor:
    """Return a 2-D square tensor with the elements of ``self`` on the diagonal.

    Mirrors ``aten::diagflat(Tensor self, int offset=0) -> Tensor``: the input
    is flattened in logical order first (a multi-dim or non-contiguous input is
    gathered by per-dimension divisor/stride decomposition, not by physical
    memory order), then placed on the diagonal shifted by ``offset`` of a
    freshly allocated ``(n + abs(offset), n + abs(offset))`` output where
    ``n`` is the input's element count. The output never aliases the input.
    """
    logger.debug("GEMS DIAGFLAT")
    offset = int(offset)
    n = self.numel()
    m = n + abs(offset)
    out = torch.empty((m, m), dtype=self.dtype, device=self.device)
    if m == 0:
        return out
    if m <= 512:
        cb, nw = 512, 4
    elif m <= 2048:
        cb, nw = 1024, 4
    else:
        cb, nw = 1024, 8
    if self.is_contiguous():
        with torch_device_fn.device(self.device):
            _rowloop_contig[(m,)](
                self,
                out,
                m,
                n,
                offset,
                min(offset, 0),
                CB=cb,
                OUT_DTYPE=_TL_DTYPES[self.dtype],
                num_warps=nw,
            )
    else:
        ndim = self.dim()
        shape = self.shape
        strides = self.stride()
        divs = []
        prod = 1
        for s in reversed(shape):
            divs.append(prod)
            prod *= s
        divs = divs[::-1]
        with torch_device_fn.device(self.device):
            _rowloop_gather[(m,)](
                self,
                out,
                torch.tensor(divs, dtype=torch.int64, device=self.device),
                torch.tensor(strides, dtype=torch.int64, device=self.device),
                m,
                n,
                offset,
                min(offset, 0),
                NDIM=ndim,
                MAX_NDIM=max(_MIN_MAX_NDIM, ndim),
                CB=cb,
                OUT_DTYPE=_TL_DTYPES[self.dtype],
                num_warps=nw,
            )
    return out
