# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def hardshrink_kernel(x_ptr, out_ptr, n_elements, lambd, BLOCK_SIZE: tl.constexpr):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)
    threshold = lambd
    keep = (x > threshold) | (x < -threshold)
    y = tl.where(keep, x, 0.0)
    tl.store(out_ptr + offsets, y, mask=mask)


def hardshrink(x: torch.Tensor, lambd: float = 0.5) -> torch.Tensor:
    """Hardshrink activation: y = x if |x| > lambd else 0"""
    x_c = x.contiguous()
    out = torch.empty_like(x_c)
    n_elements = x_c.numel()
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(x.device):
        hardshrink_kernel[grid](x_c, out, n_elements, float(lambd), BLOCK_SIZE=1024)
    return out
