# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging
import math

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@triton.jit
def gcd_func(a, b):
    # Euclidean algorithm for GCD
    # GCD(a, b) = GCD(b, a % b) until b == 0
    while b != 0:
        a, b = b, a % b
    return a


@pointwise_dynamic(promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def lcm_func(x, y):
    # lcm(x, y) = |x * y| / gcd(x, y)
    # Special cases: lcm(0, 0) = 0, lcm(0, a) = 0
    a = tl.abs(x)
    b = tl.abs(y)
    g = gcd_func(a, b)
    # Handle zero cases: if a == 0 or b == 0, result is 0
    return tl.where((a == 0) | (b == 0), 0, (a * b) // g)


@pointwise_dynamic(is_tensor=[True, False], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def lcm_func_tensor_scalar(x, y):
    a = tl.abs(x)
    b = tl.abs(y)
    g = gcd_func(a, b)
    return tl.where((a == 0) | (b == 0), 0, (a * b) // g)


@pointwise_dynamic(is_tensor=[False, True], promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def lcm_func_scalar_tensor(x, y):
    a = tl.abs(x)
    b = tl.abs(y)
    g = gcd_func(a, b)
    return tl.where((a == 0) | (b == 0), 0, (a * b) // g)


def lcm(A, B):
    logger.debug("GEMS LCM")
    if isinstance(A, torch.Tensor) and isinstance(B, torch.Tensor):
        return lcm_func(A, B)
    elif isinstance(A, torch.Tensor):
        return lcm_func_tensor_scalar(A, B)
    elif isinstance(B, torch.Tensor):
        return lcm_func_scalar_tensor(A, B)
    else:
        # Both scalar
        a, b = abs(int(A)), abs(int(B))
        return torch.tensor(
            0 if a == 0 or b == 0 else a * b // math.gcd(a, b)
        )


def lcm_(A, B):
    logger.debug("GEMS LCM_")
    if isinstance(B, torch.Tensor):
        return lcm_func(A, B, out0=A)
    else:
        return lcm_func_tensor_scalar(A, B, out0=A)
