# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


# Sequential Cholesky decomposition - single program computes entire matrix
@libentry()
@triton.jit
def cholesky_kernel(
    L,
    N,
    stride_n,
):
    """
    Sequential Cholesky decomposition kernel.
    Uses one program to compute the entire matrix sequentially.
    """
    # Cholesky-Crout algorithm (column-oriented)
    # For j = 0 to n-1:
    #   for i = j to n-1:
    #     if i == j:
    #       L[i,j] = sqrt(L[i,j] - sum(L[i,k]^2 for k < j))
    #     else:
    #       L[i,j] = (L[i,j] - sum(L[i,k] * L[j,k] for k < j)) / L[j,j]

    # Process each column
    for j in range(N):
        # First compute diagonal element L[j,j]
        # L[j,j] = sqrt(L[j,j] - sum(L[j,k]^2 for k < j))
        diag_val = tl.load(L + j * stride_n + j).to(tl.float32)

        # Subtract sum of squares
        for k in range(j):
            l_jk = tl.load(L + j * stride_n + k)
            diag_val = diag_val - l_jk * l_jk

        # sqrt and store
        diag_val = tl.sqrt(diag_val)
        tl.store(L + j * stride_n + j, diag_val)

        # Now compute elements below diagonal in column j
        # L[i,j] = (L[i,j] - sum(L[i,k] * L[j,k] for k < j)) / L[j,j] for i > j
        for i in range(j + 1, N):
            val = tl.load(L + i * stride_n + j).to(tl.float32)

            # Subtract sum of products
            for k in range(j):
                l_i_k = tl.load(L + i * stride_n + k)
                l_j_k = tl.load(L + j * stride_n + k)
                val = val - l_i_k * l_j_k

            # Divide by diagonal
            val = val / diag_val
            tl.store(L + i * stride_n + j, val)


def linalg_cholesky_ex(A, upper=False, check_errors=False):
    """
    Computes the Cholesky decomposition of a Hermitian positive-definite matrix.

    Args:
        A: Input matrix of shape (..., n, n) where ... is batch dimensions
        upper: Whether to return upper triangular matrix
        check_errors: Whether to check for decomposition errors

    Returns:
        L: Lower triangular matrix
        info: Error code (0 = success)
    """
    logger.debug("GEMS linalg_cholesky_ex")
    # float16/bfloat16 not supported by cuSolver; only float32/float64 available
    assert A.dtype in (
        torch.float32,
        torch.float64,
    ), f"linalg_cholesky_ex only supports float32/float64, got {A.dtype}"

    # Handle 2D matrices (single matrix case)
    if A.dim() == 2:
        n = A.shape[0]

        # Create lower triangular copy of input matrix
        # This contains A[i,j] for i >= j (the values we need)
        L = torch.tril(A).clone()

        # Convert to float32 for computation
        L = L.to(torch.float32)

        # Launch kernel with 1 program (sequential computation)
        grid = (1,)
        cholesky_kernel[grid](
            L,
            n,
            L.stride(0),
        )

        # Zero out upper triangle to ensure lower triangular result
        result = torch.tril(L).to(A.dtype)

        info = torch.zeros((), dtype=torch.int32, device=A.device)

        if upper:
            result = result.transpose(-2, -1).conj()

        return result, info

    # Handle batch dimensions
    batch_shape = A.shape[:-2]
    n = A.shape[-1]

    if len(batch_shape) == 0:
        return linalg_cholesky_ex(A, upper=upper, check_errors=check_errors)

    # For batch matrices, process each one
    batch_size = 1
    for dim in batch_shape:
        batch_size *= dim

    result = torch.empty_like(A, dtype=torch.float32)
    info = torch.zeros(batch_shape, dtype=torch.int32, device=A.device)

    # Process each matrix in the batch
    A_flat = A.reshape(-1, n, n)
    result_flat = result.reshape(-1, n, n)

    for b in range(batch_size):
        # Create lower triangular copy
        L = torch.tril(A_flat[b]).to(torch.float32).to(A.device)

        # Launch kernel
        grid = (1,)
        cholesky_kernel[grid](
            L,
            n,
            L.stride(0),
        )

        result_flat[b] = torch.tril(L).to(A.dtype)

    result = result_flat.reshape(*A.shape)

    if upper:
        result = result.transpose(-2, -1).conj()

    if check_errors and info.any():
        raise RuntimeError("Cholesky decomposition failed")

    return result, info


def cholesky_ex(A, upper=False, check_errors=False):
    """Wrapper for aten.cholesky_ex"""
    return linalg_cholesky_ex(A, upper=upper, check_errors=check_errors)
