# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, 1, "ALWAYS_BOOL")])
@triton.jit
def ne_func(x, y):
    return x != y


def ne(A, B):
    logger.debug("GEMS NE")
    return ne_func(A, B)


@pointwise_dynamic(is_tensor=[True, False], promotion_methods=[(0, 1, "ALWAYS_BOOL")])
@triton.jit
def ne_func_scalar(x, y):
    return x != y


def ne_scalar(A, B):
    logger.debug("GEMS NE_SCALAR")
    return ne_func_scalar(A, B)
