# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
"""BSR (block compressed sparse row) tensor constructors.

``sparse_bsr_tensor`` is a host-side constructor: it validates the raw
components (int64-compatible ``crow_indices`` / ``col_indices``, a 3-D
``values`` tensor) and wires them into a BSR tensor whose member tensors
*alias* the inputs. There is no device-side arithmetic, so no Triton kernel is
provided.

Two ATen overloads, measured on this build (see the run report for the full
per-key probe tables):

============================  ==========================================
overload                      reached dispatch key
============================  ==========================================
``.crow_col_value_size``      Autograd (also reachable on the device key
                              and on CompositeImplicitAutograd)
``.crow_col_value``           Autograd (also reachable on the device key
                              and on CompositeImplicitAutograd)
============================  ==========================================

The Python builtin ``torch.sparse_bsr_tensor`` does **not** route through
either overload: its C++ argument parser calls the *shared*
``aten::sparse_compressed_tensor.comp_plain_value[_size]`` op (the same one
used by the CSR/CSC/BSC constructors) after promoting the components. That op
is owned by the ``sparse_compressed_tensor`` integration, so this module
deliberately does not register for it; the packet overloads registered here are
what the tests and the benchmark exercise.

Delegation, not re-dispatch: every implementation calls
``aten::_sparse_bsr_tensor_unsafe``, never the overload being implemented.
Registering an overload and then calling ``torch.ops.aten.sparse_bsr_tensor.*``
internally would recurse.

The supplied competition source launched a ceremonial Triton probe kernel at
import time (``_probe_scratch = torch.zeros(1, device="cuda")`` plus a
module-level launch). It was removed: the operator has no device-side
arithmetic, the probe's result was never read, and import-time GPU work breaks
CPU-only hosts and is prohibited by the batch rules (same removal rationale as
``sparse_dim`` / ``dense_dim`` / ``can_cast``).
"""

import logging

import torch

logger = logging.getLogger(__name__)

# Native layout spellings used in ATen error messages ("Sparse", "Strided",
# "SparseCsr", ...). Mirrored so a rejected ``layout=`` argument prints the
# same text as the native constructor.
_LAYOUT_NAMES = {
    torch.strided: "Strided",
    torch.sparse_coo: "Sparse",
    torch.sparse_csr: "SparseCsr",
    torch.sparse_csc: "SparseCsc",
    torch.sparse_bsr: "SparseBsr",
    torch.sparse_bsc: "SparseBsc",
}

# Index dtypes AT_DISPATCH_INTEGRAL_TYPES accepts in
# ``_estimate_sparse_compressed_tensor_size``; a column-index tensor outside
# this set is rejected with ATen's dispatch-macro message.
_INTEGRAL_DTYPES = (
    torch.int8,
    torch.uint8,
    torch.int16,
    torch.int32,
    torch.int64,
)

# ``toString(ScalarType)`` spellings from c10/core/ScalarType.h, used by ATen's
# AT_DISPATCH_SWITCH default branch:
#   "..." not implemented for '<name>'
# The C++ name is not the torch.dtype spelling ("float32" -> "Float"), so the
# rejection message is built from this table rather than by string-munging the
# dtype name.
_SCALAR_TYPE_NAMES = {
    torch.uint8: "Byte",
    torch.int8: "Char",
    torch.int16: "Short",
    torch.int32: "Int",
    torch.int64: "Long",
    torch.float16: "Half",
    torch.float32: "Float",
    torch.float64: "Double",
    torch.complex32: "ComplexHalf",
    torch.complex64: "ComplexFloat",
    torch.complex128: "ComplexDouble",
    torch.bool: "Bool",
    torch.bfloat16: "BFloat16",
}


def _scalar_type_name(dtype):
    return _SCALAR_TYPE_NAMES.get(dtype, str(dtype).removeprefix("torch."))


def _layout_name(layout):
    return _LAYOUT_NAMES.get(layout, str(layout))


def _check_bsr_layout(layout):
    """Mirror the ``SPARSE_COMPRESSED_TENSOR(bsr, kSparseBsr)`` layout guard.

    The native macro runs ``if (layout) { TORCH_CHECK(layout == kSparseBsr,
    "sparse bsr layout must be SparseBsr but got <layout>") }`` *before*
    forcing the layout to BSR, so a ``None`` (absent) layout is accepted and
    any other explicit layout is rejected with that exact sentence.
    """
    if layout is not None and layout != torch.sparse_bsr:
        raise RuntimeError(
            f"sparse bsr layout must be {_LAYOUT_NAMES[torch.sparse_bsr]} "
            f"but got {_layout_name(layout)}"
        )


def _estimate_sparse_compressed_tensor_size(crow_indices, col_indices, values):
    """Port of ATen ``_estimate_sparse_compressed_tensor_size`` for BSR.

    Called only by the size-inference overload (``crow_col_value``), exactly as
    the native ``sparse_compressed_tensor`` two-argument form does. BSR has
    ``block_ndim == 2`` and ``base_ndim == 2``, so the inferred size is
    ``[batch..., (n_block_rows) * block_rows, (max(col_indices) + 1) *
    block_cols, dense...]`` with ``n_block_rows`` read as
    ``crow_indices.shape[-1] - 1``.

    Every rejection below carries the native message fragments (parameter
    names and values) so the error contract, not just the exception class, is
    mirrored.
    """
    batch_ndim = crow_indices.dim() - 1
    block_ndim = 2
    base_ndim = 2
    if batch_ndim < 0:
        raise RuntimeError(
            f"crow_indices must have dimensionality >= 1 but got "
            f"{crow_indices.dim()}"
        )
    if crow_indices.dim() != col_indices.dim():
        raise RuntimeError(
            f"crow_indices and col_indices dimensionalities must be equal but "
            f"got {crow_indices.dim()} and {col_indices.dim()}, respectively"
        )
    dense_ndim = values.dim() - batch_ndim - block_ndim - 1
    if dense_ndim < 0:
        raise RuntimeError(
            f"values must have dimensionality > sum of batch and block "
            f"dimensionalities (={batch_ndim} + {block_ndim}) but got "
            f"{values.dim()}"
        )

    blocksize = [
        max(1, int(values.size(batch_ndim + 1))),
        max(1, int(values.size(batch_ndim + 2))),
    ]
    size = [int(s) for s in crow_indices.shape[:batch_ndim]]
    compressed_dim_size = (
        crow_indices.size(-1) - 1
        if (crow_indices.dim() > 0 and crow_indices.size(-1) > 0)
        else 0
    )
    if col_indices.dtype not in _INTEGRAL_DTYPES:
        # AT_DISPATCH_INTEGRAL_TYPES reports the requested operator and the
        # offending scalar type name, e.g.
        #   "estimate_sparse_compressed_tensor_size" not implemented for 'Float'
        raise RuntimeError(
            '"estimate_sparse_compressed_tensor_size" not implemented for '
            f"'{_scalar_type_name(col_indices.dtype)}'"
        )
    if col_indices.numel() > 0:
        plain_dim_size = int(col_indices.max().item()) + 1
    else:
        plain_dim_size = 0

    # BSR is a row-compressed blocked layout: rows scale by blocksize[0],
    # columns by blocksize[1].
    size.append(compressed_dim_size * blocksize[0])
    size.append(plain_dim_size * blocksize[1])
    for i in range(dense_ndim):
        j = batch_ndim + 1 + block_ndim + i
        size.append(int(values.size(j)) if j < values.dim() else 1)

    if len(size) != batch_ndim + base_ndim + dense_ndim:
        raise RuntimeError(
            f"tensor dimensionality must be sum of batch, base, and dense "
            f"dimensionalities (={batch_ndim} + {base_ndim} + {dense_ndim}) "
            f"but got {len(size)}"
        )
    return size


def sparse_bsr_tensor_crow_col_value_size(
    crow_indices: torch.Tensor,
    col_indices: torch.Tensor,
    values: torch.Tensor,
    size,
    *,
    dtype=None,
    layout=None,
    device=None,
    pin_memory=False,
) -> torch.Tensor:
    """Build a BSR tensor from components with an explicit ``size``.

    Mirrors ``aten::sparse_bsr_tensor.crow_col_value_size``. The native kernel
    rejects a non-BSR ``layout``, forces ``layout = kSparseBsr`` and forwards
    everything to the shared ``sparse_compressed_tensor`` path, which ends in
    ``_sparse_bsr_tensor_unsafe``; this implementation performs the identical
    delegation, so validation order, error text and the resulting tensor
    metadata are native behaviour.

    Measured native properties of the result (see the run report):

    - the member tensors *alias* the inputs (``data_ptr`` identity for
      ``crow_indices``, ``col_indices`` and ``values``; writes through the
      inputs are visible in the result and vice versa);
    - ``dtype`` selects the sparse tensor's dtype and must equal the dtype of
      ``values`` (a mismatch raises ``dtype of values (...) must match dtype
      of sparse tensor (...)``);
    - ``device=None`` leaves the result on the *default* device while
      ``set_member_tensors`` requires all members to share it, so CUDA
      components with ``device=None`` raise ``Values and compressed tensor
      instance need to be on the same device.``;
    - ``size`` is stored verbatim: it is not checked for block divisibility
      and does not have to match ``values``' block shape.
    """
    logger.debug("GEMS SPARSE_BSR_TENSOR")
    _check_bsr_layout(layout)
    return torch.ops.aten._sparse_bsr_tensor_unsafe(
        crow_indices,
        col_indices,
        values,
        list(size),
        dtype=dtype,
        layout=torch.sparse_bsr,
        device=device,
        pin_memory=pin_memory,
    )


def sparse_bsr_tensor_crow_col_value(
    crow_indices: torch.Tensor,
    col_indices: torch.Tensor,
    values: torch.Tensor,
    *,
    dtype=None,
    layout=None,
    device=None,
    pin_memory=False,
) -> torch.Tensor:
    """Build a BSR tensor from components with an inferred ``size``.

    Mirrors ``aten::sparse_bsr_tensor.crow_col_value``. The size is inferred
    by ``_estimate_sparse_compressed_tensor_size`` (ported above, identical
    arithmetic to ATen's), which reads the block shape from the two trailing
    dimensions of ``values`` and the block-row count from
    ``crow_indices.shape[-1] - 1``.

    Measured native properties of the inferred path (see the run report):

    - ``crow_indices`` must have dimensionality >= 1 and match
      ``col_indices``' rank; ``values`` must have rank > batch + 2;
    - only integral ``col_indices`` dtypes are accepted by the size estimator;
    - a zero-nnz ``col_indices`` infers a zero *plain* extent, so the result is
      ``(n_block_rows * block_rows, 0)``;
    - the result aliases all three component tensors, like the explicit-size
      overload.
    """
    logger.debug("GEMS SPARSE_BSR_TENSOR")
    _check_bsr_layout(layout)
    inferred_size = _estimate_sparse_compressed_tensor_size(
        crow_indices, col_indices, values
    )
    return torch.ops.aten._sparse_bsr_tensor_unsafe(
        crow_indices,
        col_indices,
        values,
        inferred_size,
        dtype=dtype,
        layout=torch.sparse_bsr,
        device=device,
        pin_memory=pin_memory,
    )
