# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def legendre_polynomial_p_kernel(
    x_ptr,
    n_ptr,
    out_ptr,
    n_elements,
    MAX_N: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
    N_IS_SCALAR: tl.constexpr,
):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    # Load x
    x = tl.load(x_ptr + offsets, mask=mask, other=0.0)

    # Load n - if scalar, load once and broadcast; otherwise load with mask
    if N_IS_SCALAR:
        n = tl.load(n_ptr)  # Load the scalar value
        n_int = n.to(tl.int32)
    else:
        n = tl.load(n_ptr + offsets, mask=mask, other=0.0)
        n_int = n.to(tl.int32)

    # Compute in float32 for better precision
    x_f32 = x.to(tl.float32)

    # Initialize P_0 and P_1
    p_km1 = tl.full([BLOCK_SIZE], 1.0, tl.float32)  # P_0(x) = 1
    p_k = x_f32  # P_1(x) = x

    # Handle n == 0 and n == 1 directly
    result = tl.where(
        n_int == 0,
        p_km1,
        tl.where(n_int == 1, p_k, 0.0),  # Placeholder, will be overwritten
    )

    # For n >= 2, use recurrence:
    # P_k(x) = ((2*k-1) * x * P_{k-1}(x) - (k-1) * P_{k-2}(x)) / k
    for k in tl.static_range(2, MAX_N + 1):
        # Compute P_k only for elements where n >= k
        k_minus_1 = k - 1

        p_kp1 = (
            (tl.cast(k * 2 - 1, tl.float32) * x_f32 * p_k)
            - (tl.cast(k_minus_1, tl.float32) * p_km1)
        ) / tl.cast(k, tl.float32)

        # Update P_{k-2} and P_{k-1}
        p_km1 = p_k
        p_k = p_kp1

        # Update result for elements where n == k
        result = tl.where(n_int == k, p_k, result)

    # Cast back to input dtype and store
    tl.store(out_ptr + offsets, result.to(x.dtype), mask=mask)


def _launch_legendre_polynomial_p(
    x: torch.Tensor, n: torch.Tensor, out: torch.Tensor, max_n: int = 32
):
    assert x.device == n.device == out.device, "All tensors must be on the same device"
    # Handle scalar n (0-dimensional tensor) by broadcasting
    n_is_scalar = n.dim() == 0
    if not n_is_scalar:
        assert (
            x.numel() == n.numel() == out.numel()
        ), "All tensors must have the same number of elements"
    assert x.shape == out.shape, "x and out must have the same shape"

    n_elements = x.numel()
    if n_elements == 0:
        return

    BLOCK_SIZE = 1024
    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    with torch_device_fn.device(x.device):
        legendre_polynomial_p_kernel[grid](
            x, n, out, n_elements, max_n, BLOCK_SIZE=BLOCK_SIZE, N_IS_SCALAR=n_is_scalar
        )


def _max_finite_degree(n: torch.Tensor) -> int:
    if n.numel() == 0:
        return 0
    if n.is_floating_point():
        finite_n = torch.where(torch.isfinite(n) & (n > 0), n, 0)
        return int(finite_n.max().item())
    return max(int(n.max().item()), 0)


def _prepare_inputs(x: torch.Tensor, n: torch.Tensor):
    x_b, n_b = torch.broadcast_tensors(x, n)
    x_c = x_b.contiguous()
    if n.numel() == 1:
        n_c = n.reshape(()).contiguous()
    else:
        n_c = n_b.contiguous()
    return x_b, x_c, n_c


def legendre_polynomial_p(x: torch.Tensor, n: torch.Tensor) -> torch.Tensor:
    logger.debug("GEMS LEGENDRE_POLYNOMIAL_P")
    _, x_c, n_c = _prepare_inputs(x, n)
    out = torch.empty_like(x_c)

    max_n = max(_max_finite_degree(n_c), 1)

    _launch_legendre_polynomial_p(x_c, n_c, out, max_n)
    return out


def legendre_polynomial_p_out(
    x: torch.Tensor, n: torch.Tensor, out: torch.Tensor
) -> torch.Tensor:
    logger.debug("GEMS LEGENDRE_POLYNOMIAL_P_OUT")
    if out.dtype != x.dtype:
        raise TypeError("out dtype must match input dtype")
    if out.device != x.device:
        raise TypeError("out device must match input device")

    x_b, x_c, n_c = _prepare_inputs(x, n)
    if out.shape != x_b.shape:
        out.resize_(x_b.shape)
    out_c = out.contiguous()

    max_n = max(_max_finite_degree(n_c), 1)

    _launch_legendre_polynomial_p(x_c, n_c, out_c, max_n)
    if out_c.data_ptr() != out.data_ptr():
        out.copy_(out_c)
    return out
